#include "core.h"

/* GitHub issue #13: 0x0800FC70-0x08010A0C, continuing the physics/
 * collision subsystem (see game_loop17.c's header comment and
 * docs/matching/issue-13-graphics-fc70.md). */

/* A per-frame position-wrap advance: `self+0x4c` is a signed "speed"
 * (defaulting to 1 when 0), `self+0x44` a signed Q8-ish countdown
 * ("remaining"). When `remaining == 0` the whole function is a no-op.
 * Otherwise it sets the global one-shot flag byte `gUnknown_030012B0`,
 * then loops, once per unit of `speed`, folding `remaining` toward
 * zero by +-0x100 (or +-0x40, when the viewport's own
 * `gUnknown_030012D8`-relative `+0x88` byte reads 1 - a "half speed"
 * mode) while accumulating the matching step into `self+0x4`; each
 * time `remaining` crosses to <=0 it re-derives the wrap via the
 * `gStaticData_0816BBC4[self+0x4e]` per-state table and, depending on
 * that table's value and `self+0x48`/`self+0x4d`'s state, dispatches
 * `sub_800EEF0`/`sub_800E620` on `self` and its whole `sub_8010708`
 * "get next" neighbor-list chain (the same list `sub_800FEB0`/
 * `sub_80106DC`, game_loop22.c/game_loop23.c, already establish). At
 * the end, `self+0x4`'s accumulated step is folded into `self`'s own
 * position (`self+0`/`self+4`), and `self+0x4c`'s "speed" byte is
 * either cleared (when `remaining` ended up exactly 0) or incremented
 * toward a clamped max of 5 (saturating, never decremented back down
 * by this function).
 *
 * Written as NAKED asm, not plain C: the ROM keeps both `sb` and `r8`
 * live as extra callee-saved accumulators for the whole function -
 * the same "two extra high-register accumulators live throughout" gap
 * already parked (and later NAKED-transcribed) for `sub_800D040`
 * (game_loop6.c) and its own `sub_8007B98` precedent in this exact
 * physics/collision subsystem, see
 * docs/matching/issue-12-physics-collision.md. Every instruction below
 * is checked byte-identical to the ROM. */
NAKED void sub_800FC70(void *selfArg)
{
    asm(
        "push {r4, r5, r6, r7, lr}\n\t"
        "mov r7, sb\n\t"
        "mov r6, r8\n\t"
        "push {r6, r7}\n\t"
        "add r5, r0, #0\n\t"
        "ldr r7, [r5, #0x44]\n\t"
        "cmp r7, #0\n\t"
        "bne 1f\n\t"
        "b 23f\n\t"
    "1:\n\t"
        "ldr r0, 4f\n\t"
        "mov r1, #1\n\t"
        "strb r1, [r0]\n\t"
        "add r0, r5, #0\n\t"
        "add r0, #0x4c\n\t"
        "mov r6, #0\n\t"
        "ldrsb r6, [r0, r6]\n\t"
        "mov sb, r0\n\t"
        "cmp r6, #0\n\t"
        "bne 2f\n\t"
        "mov r6, #1\n\t"
    "2:\n\t"
        "mov r0, #0\n\t"
        "mov r8, r0\n\t"
        "ldr r1, [r5]\n\t"
        "cmp r6, #0\n\t"
        "bge 6f\n\t"
        "ldr r2, 5f\n\t"
        "mov r0, #0x80\n\t"
        "lsl r0, r0, #1\n\t"
    "3:\n\t"
        "add r8, r2\n\t"
        "add r7, r7, r0\n\t"
        "add r6, #1\n\t"
        "cmp r6, #0\n\t"
        "bne 3b\n\t"
        "b 20f\n\t"
        ".align 2, 0\n"
    "4: .4byte gUnknown_030012B0\n"
    "5: .4byte 0xFFFFFF00\n"
    "6:\n\t"
        "cmp r7, #0\n\t"
        "ble 10f\n\t"
        "ldr r0, 7f\n\t"
        "ldr r0, [r0]\n\t"
        "add r0, #0x88\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r0, #1\n\t"
        "bne 8f\n\t"
        "mov r1, #0x40\n\t"
        "add r8, r1\n\t"
        "sub r7, #0x40\n\t"
        "sub r6, #1\n\t"
        "b 19f\n\t"
        ".align 2, 0\n"
    "7: .4byte gUnknown_030012D8\n"
    "8:\n\t"
        "mov r0, #0x80\n\t"
        "lsl r0, r0, #1\n\t"
        "add r8, r0\n\t"
        "ldr r1, 9f\n\t"
        "add r7, r7, r1\n\t"
        "sub r6, #1\n\t"
        "b 19f\n\t"
        ".align 2, 0\n"
    "9: .4byte 0xFFFFFF00\n"
    "10:\n\t"
        "mov r6, #1\n\t"
        "ldr r1, [r5, #0x40]\n\t"
        "str r1, [r5, #4]\n\t"
        "mov r0, #0\n\t"
        "mov r8, r0\n\t"
        "str r7, [r5, #0x44]\n\t"
        "ldr r0, 11f\n\t"
        "add r1, r5, #0\n\t"
        "add r1, #0x4e\n\t"
        "ldrb r1, [r1]\n\t"
        "add r0, r1, r0\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r0, #0\n\t"
        "beq 15f\n\t"
        "ldr r0, [r5, #0x48]\n\t"
        "cmp r0, #0\n\t"
        "bne 12f\n\t"
        "cmp r1, #0xa\n\t"
        "bne 13f\n\t"
    "12:\n\t"
        "add r1, r5, #0\n\t"
        "add r1, #0x4d\n\t"
        "mov r0, #0x7f\n\t"
        "ldrb r1, [r1]\n\t"
        "and r0, r0, r1\n\t"
        "cmp r0, #0\n\t"
        "bne 15f\n\t"
        "add r0, r5, #0\n\t"
        "mov r1, #0\n\t"
        "bl sub_800EEF0\n\t"
        "b 15f\n\t"
        ".align 2, 0\n"
    "11: .4byte gStaticData_0816BBC4\n"
    "13:\n\t"
        "cmp r1, #0xe\n\t"
        "bne 15f\n\t"
        "add r0, r5, #0\n\t"
        "bl sub_801070C\n\t"
        "add r4, r0, #0\n\t"
        "add r0, r5, #0\n\t"
        "bl sub_8010708\n\t"
        "cmp r4, #0\n\t"
        "bne 14f\n\t"
        "cmp r0, #0\n\t"
        "bne 15f\n\t"
    "14:\n\t"
        "add r0, r5, #0\n\t"
        "bl sub_800E620\n\t"
    "15:\n\t"
        "add r0, r5, #0\n\t"
        "bl sub_8010708\n\t"
        "add r4, r0, #0\n\t"
        "sub r6, #1\n\t"
        "cmp r4, #0\n\t"
        "beq 19f\n\t"
        "b 18f\n\t"
    "16:\n\t"
        "add r0, r4, #0\n\t"
        "add r0, #0x4e\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r0, #0xe\n\t"
        "bne 17f\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_800E620\n\t"
    "17:\n\t"
        "add r0, r4, #0\n\t"
    "18:\n\t"
        "bl sub_8010708\n\t"
        "add r4, r0, #0\n\t"
        "cmp r4, #0\n\t"
        "bne 16b\n\t"
    "19:\n\t"
        "ldr r1, [r5]\n\t"
        "cmp r6, #0\n\t"
        "bne 6b\n\t"
    "20:\n\t"
        "ldr r0, [r5, #4]\n\t"
        "add r0, r8\n\t"
        "str r1, [r5]\n\t"
        "str r0, [r5, #4]\n\t"
        "str r7, [r5, #0x44]\n\t"
        "cmp r7, #0\n\t"
        "bne 21f\n\t"
        "mov r1, sb\n\t"
        "strb r7, [r1]\n\t"
        "b 23f\n\t"
    "21:\n\t"
        "mov r2, sb\n\t"
        "ldrb r1, [r2]\n\t"
        "add r1, #1\n\t"
        "strb r1, [r2]\n\t"
        "lsl r0, r1, #0x18\n\t"
        "cmp r0, #0\n\t"
        "bne 22f\n\t"
        "add r0, r1, #1\n\t"
        "strb r0, [r2]\n\t"
    "22:\n\t"
        "mov r1, sb\n\t"
        "mov r0, #0\n\t"
        "ldrsb r0, [r1, r0]\n\t"
        "cmp r0, #5\n\t"
        "ble 23f\n\t"
        "mov r0, #5\n\t"
        "strb r0, [r1]\n\t"
    "23:\n\t"
        "pop {r3, r4}\n\t"
        "mov r8, r3\n\t"
        "mov sb, r4\n\t"
        "pop {r4, r5, r6, r7}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
    );
}
/* Trailing byte-padding mismatch fix: the function body is 342 bytes
 * (not 4-aligned), and the ROM pads the 2-byte gap before the next
 * function (sub_800FDC8) with a zero halfword rather than the
 * assembler's default `nop` (`mov r8, r8`) - see
 * matching_decomp_alignment_fix memory. */
asm(".align 2, 0");
