#include "core.h"

/* GitHub issue #12: 0x0800D040-0x0800FC70, the physics/collision
 * subsystem (see game_loop6.c's header comment and
 * docs/matching/issue-12-physics-collision.md). Phase 2, higher-address
 * half: the twelve functions from `sub_800EEF0` through `sub_800F990`
 * (0x0800EEF0-0x0800FC70, the end of this whole cluster), all direct or
 * transitive callees of `sub_0800D18C`'s and `sub_800E08C`'s per-edge
 * jump table (game_loop47.c) - see that issue doc's "Phase 2 grouping
 * hint" for the confirmed dispatch map this group is built from. Real
 * bytes formerly the tail of asm/code_3_2_17_e560.s (from
 * `sub_800EEF0` onward - the head, `sub_800E560` through `sub_800EDBC`,
 * is a sibling pass's territory and untouched here).
 *
 * All twelve are NAKED transcriptions, not decompiled C, for the same
 * reason as this issue's other parked/NAKED functions
 * (`sub_800D040`/`sub_800E494`/`sub_800E4E4`/`sub_0800D18C`/
 * `sub_800E08C`): every one of them re-triggers the same
 * gcc-2.9-resistant register shapes already documented there (the
 * `self+0x20`/`+0x2d`/28-byte-stride AABB-record idiom, or plain
 * high-register/cross-block reuse under -O2 that this compiler's
 * allocator doesn't reproduce), and given the size of this batch,
 * transcription was the reliable path to a byte-exact result for all of
 * them at once rather than re-fighting each function's register
 * allocation individually. Mnemonics translated from the disassembler's
 * unified syntax to the plain/divided syntax this project's other
 * `NAKED` functions use (`adds`->`add`, `movs`->`mov`, `ands`->`and`,
 * `lsls`/`lsrs`->`lsl`/`lsr`, `asrs`->`asr`, `orrs`->`orr`,
 * `eors`->`eor`, `rsbs rX,rX,#0`->`neg rX,rX`), with the original
 * `_08XXXXXX:` labels renumbered to GNU-as local numeric labels
 * (per-function, first-definition order). */


/* Per-edge jump table's **case 4 handler**
 * (`sub_0800D18C(self+0x4d & 0x7f == 0) -> sub_800EEF0(self, 1)`, and
 * `sub_800E08C`'s own case 4, per game_loop47.c's confirmed dispatch
 * map). Also called by several of this file's own sibling functions
 * (`sub_800F06C`, `sub_800F258`, `sub_800F6B8`, `sub_800F8E0`) whenever
 * their own overlap/state checks land on the same "commit an edge
 * collision" outcome, always with `arg1` (a `u8`) as either 0 or 1.
 *
 * Early-outs when `self+0x4d & 0x7f == 1` (already committed). Clears
 * `self+0x4f`, clears `self+0x4d`'s low 7 bits, resets
 * `gUnknown_030012D8+0x80`, sets `self+0xc` bit `0x10` (a "collision
 * response active" render/update flag matched elsewhere in this
 * subsystem), and calls `sub_8009150(gUnknown_0300130C, self)` (adds
 * `self` back onto the shared active-object list). Sets `self+0x4d`'s
 * `0x80` bit unconditionally, then ORs in `arg1` on top of that -
 * `arg1` ends up as the low bit of `self+0x4d`.
 *
 * If `self+0x4e == 0xa` (a specific collision state id), rewinds
 * `self+0x4e` by `0x21` (`0xa -> ... ` - stores through
 * `self+0x4e - 0x21`, i.e. a computed offset elsewhere in `self`'s
 * struct) instead of the usual `self+0x2d = 0x21` tag write, then in
 * either case calls the `sub_80087C0`/`sub_80087B4`/`sub_800872C`
 * triplet (the "set tag, refresh sprite/animation" idiom shared by
 * every state-transition function in this cluster - see
 * `sub_800F2BC`/`sub_800F368`/`sub_800F5B8`/`sub_800F8E0` below for the
 * same three-call pattern).
 *
 * Looks up `gStaticData_0816BB98[self+0x4e]` and, if nonzero, calls
 * `sub_8022FEC(gUnknown_030012C0)` (an external subsystem, unread -
 * likely a screen-shake/particle trigger). Sets a bit in
 * `gUnknown_030012B4`'s 32x32 collision-cell bitmap from `self+8`'s
 * position (`>>5` row, `&0x1f` column - the same cell-grid convention
 * `sub_0800D18C` itself uses for `gUnknown_030012D8`'s own state), then
 * plays a fixed sound (`gUnknown_030012BC`, id 4). Calls
 * `sub_800EDBC(self)` (already matched elsewhere in this cluster - a
 * sibling's territory).
 *
 * Tail: reads `gUnknown_0300082C`'s `+0xc` byte bit `0x40` (a "combo
 * scoring active" flag elsewhere in the ROM); if set, and
 * `gUnknown_030012D8+0x8c` (a running counter) hasn't exceeded
 * `gUnknown_0300082C`'s threshold, and `self`'s position is within 0x1d
 * px of `gUnknown_030012D8`'s (the player) on both axes (or `arg1`
 * itself is 0), calls `sub_803AD88` (the `bx r4` sound/particle
 * trampoline from `self+0x18+0x68`) with args `(0, 4, 0)`. Finally, if
 * `self+0x4e != 0xa`, forces `self+0x4e = 0x13` (a shared "settle"
 * state most of this cluster's state machines converge on - see
 * `sub_800F8E0` below). */

NAKED void sub_800EEF0(void *self, u8 arg1)
{
    asm(
        "push {r4, r5, r6, r7, lr}\n\t"
        "add r4, r0, #0\n\t"
        "lsl r1, r1, #0x18\n\t"
        "lsr r7, r1, #0x18\n\t"
        "add r5, r4, #0\n\t"
        "add r5, #0x4d\n\t"
        "mov r2, #0x7f\n\t"
        "add r0, r2, #0\n\t"
        "ldrb r1, [r5]\n\t"
        "and r0, r1\n\t"
        "cmp r0, #1\n\t"
        "bne 1f\n\t"
        "b 11f\n\t"
    "1:\n\t"
        "add r0, r4, #0\n\t"
        "add r0, #0x4f\n\t"
        "mov r1, #0\n\t"
        "strb r1, [r0]\n\t"
        "add r0, r2, #0\n\t"
        "ldrb r2, [r5]\n\t"
        "and r0, r2\n\t"
        "strb r0, [r5]\n\t"
        "ldr r0, 2f\n\t"
        "ldr r0, [r0]\n\t"
        "add r0, #0x80\n\t"
        "strb r1, [r0]\n\t"
        "mov r0, #0x10\n\t"
        "ldrb r3, [r4, #0xc]\n\t"
        "orr r0, r3\n\t"
        "strb r0, [r4, #0xc]\n\t"
        "ldr r0, 3f\n\t"
        "ldr r0, [r0]\n\t"
        "add r1, r4, #0\n\t"
        "bl sub_8009150\n\t"
        "mov r1, #1\n\t"
        "mov r0, #0x80\n\t"
        "ldrb r2, [r5]\n\t"
        "and r0, r2\n\t"
        "orr r0, r1\n\t"
        "strb r0, [r5]\n\t"
        "add r0, r4, #0\n\t"
        "add r0, #0x4e\n\t"
        "add r6, r0, #0\n\t"
        "ldrb r3, [r6]\n\t"
        "cmp r3, #0xa\n\t"
        "bne 4f\n\t"
        "sub r0, #0x21\n\t"
        "strb r1, [r0]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087C0\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087B4\n\t"
        "add r0, r4, #0\n\t"
        "mov r1, #0\n\t"
        "bl sub_800872C\n\t"
        "b 5f\n\t"
        ".align 2, 0\n"
    "2: .4byte gUnknown_030012D8\n"
    "3: .4byte gUnknown_0300130C\n"
    "4:\n\t"
        "mov r0, #0x21\n\t"
        "add r1, r4, #0\n\t"
        "add r1, #0x2d\n\t"
        "strb r0, [r1]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087C0\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087B4\n\t"
        "add r0, r4, #0\n\t"
        "mov r1, #0\n\t"
        "bl sub_800872C\n\t"
    "5:\n\t"
        "ldr r0, 12f\n\t"
        "ldrb r5, [r6]\n\t"
        "add r0, r5, r0\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r0, #0\n\t"
        "beq 6f\n\t"
        "ldr r0, 13f\n\t"
        "ldr r0, [r0]\n\t"
        "bl sub_8022FEC\n\t"
    "6:\n\t"
        "ldrh r3, [r4, #8]\n\t"
        "ldr r0, 14f\n\t"
        "ldr r2, [r0]\n\t"
        "add r0, r3, #0\n\t"
        "asr r0, r0, #5\n\t"
        "lsl r1, r0, #2\n\t"
        "mov r5, #0x84\n\t"
        "lsl r5, r5, #1\n\t"
        "add r2, r2, r5\n\t"
        "add r2, r2, r1\n\t"
        "lsl r0, r0, #5\n\t"
        "sub r0, r3, r0\n\t"
        "mov r1, #1\n\t"
        "lsl r1, r0\n\t"
        "ldr r0, [r2]\n\t"
        "orr r0, r1\n\t"
        "str r0, [r2]\n\t"
        "ldr r0, 15f\n\t"
        "ldr r0, [r0]\n\t"
        "mov r2, #0x80\n\t"
        "lsl r2, r2, #1\n\t"
        "mov r1, #4\n\t"
        "bl PlaySfx\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_800EDBC\n\t"
        "ldr r0, 16f\n\t"
        "ldr r3, [r0]\n\t"
        "ldrb r1, [r3, #0xc]\n\t"
        "lsr r0, r1, #6\n\t"
        "mov r1, #1\n\t"
        "and r0, r1\n\t"
        "cmp r0, #0\n\t"
        "beq 10f\n\t"
        "mov r5, #0\n\t"
        "add r0, r3, #0\n\t"
        "add r0, #0x8c\n\t"
        "ldr r1, 17f\n\t"
        "ldr r2, [r0]\n\t"
        "ldr r0, [r1]\n\t"
        "cmp r2, r0\n\t"
        "bls 7f\n\t"
        "mov r5, #1\n\t"
    "7:\n\t"
        "cmp r5, #0\n\t"
        "bne 10f\n\t"
        "ldr r0, [r3]\n\t"
        "asr r0, r0, #8\n\t"
        "ldr r1, [r4]\n\t"
        "asr r1, r1, #8\n\t"
        "sub r0, r0, r1\n\t"
        "asr r1, r0, #0x1f\n\t"
        "eor r0, r1\n\t"
        "sub r0, r0, r1\n\t"
        "cmp r0, #0x1d\n\t"
        "bgt 8f\n\t"
        "ldr r0, [r3, #4]\n\t"
        "asr r0, r0, #8\n\t"
        "ldr r1, [r4, #4]\n\t"
        "asr r1, r1, #8\n\t"
        "sub r0, r0, r1\n\t"
        "asr r1, r0, #0x1f\n\t"
        "eor r0, r1\n\t"
        "sub r0, r0, r1\n\t"
        "cmp r0, #0x1d\n\t"
        "ble 9f\n\t"
    "8:\n\t"
        "cmp r7, #0\n\t"
        "beq 10f\n\t"
    "9:\n\t"
        "ldr r0, 16f\n\t"
        "ldr r0, [r0]\n\t"
        "ldr r1, [r0, #0x18]\n\t"
        "add r1, #0x68\n\t"
        "mov r3, #0\n\t"
        "ldrsh r2, [r1, r3]\n\t"
        "add r0, r0, r2\n\t"
        "ldr r4, [r1, #4]\n\t"
        "mov r1, #0\n\t"
        "mov r2, #4\n\t"
        "mov r3, #0\n\t"
        "bl sub_803AD88\n\t"
    "10:\n\t"
        "ldrb r5, [r6]\n\t"
        "cmp r5, #0xa\n\t"
        "beq 11f\n\t"
        "mov r0, #0x13\n\t"
        "strb r0, [r6]\n\t"
    "11:\n\t"
        "pop {r4, r5, r6, r7}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
        ".align 2, 0\n"
    "12: .4byte gStaticData_0816BB98\n"
    "13: .4byte gUnknown_030012C0\n"
    "14: .4byte gUnknown_030012B4\n"
    "15: .4byte gUnknown_030012BC\n"
    "16: .4byte gUnknown_030012D8\n"
    "17: .4byte gUnknown_0300082C\n"
    );
}

/* Called from `sub_800F798` (`sub_800F06C(self, 0x14)` /
 * `sub_800F06C(self, 0x28)`, gated on `self+0x30 == 3` / `== 6`) with
 * `arg1` a small proximity-radius constant (0x14 or 0x28 px). Walks
 * `gUnknown_0300130C`'s whole object list twice:
 *
 * - First pass: for every other object whose `sub_803AD7C`
 *   overlap-classification against `self` returns `3` (a "close enough
 *   to interact" code shared with several siblings below) and whose
 *   Chebyshev-ish `|dx|+|dy|` distance to `self` is within `arg1`,
 *   looks up `gStaticData_0816BBC4[other+0x4e]`: if nonzero, calls
 *   `sub_800E7A8(other, 1, 0, 0)`; else if the *other* object's own
 *   `gStaticData_0816BBAE` byte (keyed by that lookup's result) is set,
 *   calls `sub_800E7A8(other, 1, 0, 0)`; else dispatches on that byte's
 *   value (`3` -> `sub_800F368(other)`, `6` -> `sub_800F2BC(other)`) -
 *   but only when `other+0x4d & 0x7f == 0` and it's not already flagged
 *   via `gUnknown_030012EC`. (Every object that passes the overlap
 *   check but isn't otherwise routed still gets `sub_800EEF0(other, 0)`
 *   when `gUnknown_030012EC[other+0x4e]` is nonzero, before falling
 *   into that dispatch.)
 * - Second pass over `gUnknown_030012EC`'s smaller secondary list:
 *   objects with `sub_803AD7C == 2` and the same distance gate get
 *   `sub_8011448(other, 1)` (already matched elsewhere) and an
 *   `other+0xc` bit-`0x10` set (same render/update flag `sub_800EEF0`
 *   sets above).
 *
 * Ends by resetting `self+0x48` to `-1` (0xFFFFFFFF), a sentinel this
 * whole cluster uses for "no pending sub-state timer". */

NAKED void sub_800F06C(void *self, u32 arg1)
{
    asm(
        "push {r4, r5, r6, r7, lr}\n\t"
        "mov r7, r8\n\t"
        "push {r7}\n\t"
        "add r6, r0, #0\n\t"
        "mov r8, r1\n\t"
        "mov r5, #0\n\t"
        "ldr r0, 2f\n\t"
        "ldr r0, [r0]\n\t"
        "ldr r0, [r0]\n\t"
        "cmp r5, r0\n\t"
        "bge 9f\n\t"
        "ldr r7, 3f\n\t"
    "1:\n\t"
        "ldr r0, 2f\n\t"
        "ldr r0, [r0]\n\t"
        "ldr r1, [r0, #8]\n\t"
        "lsl r0, r5, #2\n\t"
        "add r0, r0, r1\n\t"
        "ldr r4, [r0]\n\t"
        "ldr r1, [r4, #0x18]\n\t"
        "add r1, #0x48\n\t"
        "mov r2, #0\n\t"
        "ldrsh r0, [r1, r2]\n\t"
        "add r0, r4, r0\n\t"
        "ldr r1, [r1, #4]\n\t"
        "bl sub_803AD7C\n\t"
        "cmp r0, #3\n\t"
        "bne 8f\n\t"
        "ldr r2, [r4]\n\t"
        "asr r2, r2, #8\n\t"
        "ldr r0, [r6]\n\t"
        "asr r0, r0, #8\n\t"
        "sub r2, r2, r0\n\t"
        "asr r0, r2, #0x1f\n\t"
        "eor r2, r0\n\t"
        "sub r2, r2, r0\n\t"
        "ldr r1, [r4, #4]\n\t"
        "asr r1, r1, #8\n\t"
        "ldr r0, [r6, #4]\n\t"
        "asr r0, r0, #8\n\t"
        "sub r1, r1, r0\n\t"
        "asr r0, r1, #0x1f\n\t"
        "eor r1, r0\n\t"
        "sub r1, r1, r0\n\t"
        "add r2, r2, r1\n\t"
        "cmp r2, r8\n\t"
        "bgt 8f\n\t"
        "add r1, r4, #0\n\t"
        "add r1, #0x4d\n\t"
        "mov r0, #0x7f\n\t"
        "ldrb r1, [r1]\n\t"
        "and r0, r1\n\t"
        "cmp r0, #0\n\t"
        "bne 8f\n\t"
        "add r0, r4, #0\n\t"
        "add r0, #0x4e\n\t"
        "ldrb r1, [r0]\n\t"
        "add r0, r1, r7\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r0, #0\n\t"
        "beq 4f\n\t"
        "add r0, r4, #0\n\t"
        "mov r1, #0\n\t"
        "bl sub_800EEF0\n\t"
        "b 8f\n\t"
        ".align 2, 0\n"
    "2: .4byte gUnknown_0300130C\n"
    "3: .4byte gStaticData_0816BBC4\n"
    "4:\n\t"
        "ldr r0, 5f\n\t"
        "add r0, r1, r0\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r0, #0\n\t"
        "beq 6f\n\t"
        "add r0, r4, #0\n\t"
        "mov r1, #1\n\t"
        "mov r2, #0\n\t"
        "mov r3, #0\n\t"
        "bl sub_800E7A8\n\t"
        "b 8f\n\t"
        ".align 2, 0\n"
    "5: .4byte gStaticData_0816BBAE\n"
    "6:\n\t"
        "cmp r1, #3\n\t"
        "bne 7f\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_800F368\n\t"
        "b 8f\n\t"
    "7:\n\t"
        "cmp r1, #6\n\t"
        "bne 8f\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_800F2BC\n\t"
    "8:\n\t"
        "add r5, #1\n\t"
        "ldr r0, 13f\n\t"
        "ldr r0, [r0]\n\t"
        "ldr r0, [r0]\n\t"
        "cmp r5, r0\n\t"
        "blt 1b\n\t"
    "9:\n\t"
        "mov r5, #0\n\t"
        "ldr r1, 14f\n\t"
        "ldr r0, [r1]\n\t"
        "ldr r0, [r0, #4]\n\t"
        "cmp r5, r0\n\t"
        "bge 12f\n\t"
        "add r7, r1, #0\n\t"
    "10:\n\t"
        "ldr r0, [r7]\n\t"
        "ldr r1, [r0, #0xc]\n\t"
        "lsl r0, r5, #2\n\t"
        "add r0, r0, r1\n\t"
        "ldr r4, [r0]\n\t"
        "ldr r1, [r4, #0x18]\n\t"
        "add r1, #0x48\n\t"
        "mov r2, #0\n\t"
        "ldrsh r0, [r1, r2]\n\t"
        "add r0, r4, r0\n\t"
        "ldr r1, [r1, #4]\n\t"
        "bl sub_803AD7C\n\t"
        "cmp r0, #2\n\t"
        "bne 11f\n\t"
        "ldr r2, [r4]\n\t"
        "asr r2, r2, #8\n\t"
        "ldr r0, [r6]\n\t"
        "asr r0, r0, #8\n\t"
        "sub r2, r2, r0\n\t"
        "asr r0, r2, #0x1f\n\t"
        "eor r2, r0\n\t"
        "sub r2, r2, r0\n\t"
        "ldr r1, [r4, #4]\n\t"
        "asr r1, r1, #8\n\t"
        "ldr r0, [r6, #4]\n\t"
        "asr r0, r0, #8\n\t"
        "sub r1, r1, r0\n\t"
        "asr r0, r1, #0x1f\n\t"
        "eor r1, r0\n\t"
        "sub r1, r1, r0\n\t"
        "add r2, r2, r1\n\t"
        "cmp r2, r8\n\t"
        "bgt 11f\n\t"
        "add r0, r4, #0\n\t"
        "mov r1, #1\n\t"
        "bl sub_8011448\n\t"
        "mov r0, #0x10\n\t"
        "ldrb r1, [r4, #0xc]\n\t"
        "orr r0, r1\n\t"
        "strb r0, [r4, #0xc]\n\t"
    "11:\n\t"
        "add r5, #1\n\t"
        "ldr r0, [r7]\n\t"
        "ldr r0, [r0, #4]\n\t"
        "cmp r5, r0\n\t"
        "blt 10b\n\t"
    "12:\n\t"
        "mov r0, #0xff\n\t"
        "str r0, [r6, #0x48]\n\t"
        "pop {r3}\n\t"
        "mov r8, r3\n\t"
        "pop {r4, r5, r6, r7}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
        ".align 2, 0\n"
    "13: .4byte gUnknown_0300130C\n"
    "14: .4byte gUnknown_030012EC\n"
    );
}

/* Takes no arguments - a pure `gUnknown_0300130C` list-scan helper,
 * called from the still-raw `sub_80232C8`/`0x08023A1C` caller elsewhere
 * (outside this issue's scope). First calls `sub_800F258` (below) to
 * settle any pending case-`0xa` collisions, then loops
 * `gUnknown_0300130C` up to twice (an outer `do { ... } while
 * (gUnknown_030012B0)` driven by a one-shot re-scan flag stored at
 * `gUnknown_030012B0`): for every object whose `sub_803AD7C`
 * classification against `self` is `3` and whose `+0xc` bit `1` is set,
 * calls `sub_8009AA0(list, index)` (an already-elsewhere-matched
 * list-removal helper) and, if that object is still non-NULL
 * afterward, `sub_803AD80(other, 3, ...)` (a variant of the
 * `sub_803AD7C` overlap-classifier that also *mutates* state, per the
 * `3` id) - decrementing the loop index to re-visit the same slot next
 * iteration since the list just shrank. Objects that overlap but don't
 * have that `+0xc` flag instead get a plain `sub_803AD7C` call against
 * a *different* box (`other+0x18+0x18`/`+0x1c`, not `+0x48`/`+4`) with
 * no further action - just a classification side effect. */

NAKED void sub_800F1B8(void)
{
    asm(
        "push {r4, r5, r6, r7, lr}\n\t"
        "mov r7, r8\n\t"
        "push {r7}\n\t"
        "bl sub_800F258\n\t"
        "ldr r0, 4f\n\t"
        "mov r8, r0\n\t"
    "1:\n\t"
        "mov r0, #0\n\t"
        "mov r1, r8\n\t"
        "strb r0, [r1]\n\t"
        "mov r5, #0\n\t"
        "ldr r7, 5f\n\t"
        "ldr r0, [r7]\n\t"
        "ldr r0, [r0]\n\t"
        "cmp r5, r0\n\t"
        "bge 8f\n\t"
        "add r6, r7, #0\n\t"
    "2:\n\t"
        "ldr r0, [r6]\n\t"
        "ldr r1, [r0, #8]\n\t"
        "lsl r0, r5, #2\n\t"
        "add r0, r0, r1\n\t"
        "ldr r4, [r0]\n\t"
        "ldr r1, [r4, #0x18]\n\t"
        "add r1, #0x48\n\t"
        "mov r2, #0\n\t"
        "ldrsh r0, [r1, r2]\n\t"
        "add r0, r4, r0\n\t"
        "ldr r1, [r1, #4]\n\t"
        "bl sub_803AD7C\n\t"
        "cmp r0, #3\n\t"
        "bne 7f\n\t"
        "mov r0, #1\n\t"
        "ldrb r1, [r4, #0xc]\n\t"
        "and r0, r1\n\t"
        "cmp r0, #0\n\t"
        "beq 6f\n\t"
        "ldr r0, [r6]\n\t"
        "add r1, r5, #0\n\t"
        "bl sub_8009AA0\n\t"
        "cmp r4, #0\n\t"
        "beq 3f\n\t"
        "ldr r1, [r4, #0x18]\n\t"
        "add r1, #0x50\n\t"
        "mov r2, #0\n\t"
        "ldrsh r0, [r1, r2]\n\t"
        "add r0, r4, r0\n\t"
        "ldr r2, [r1, #4]\n\t"
        "mov r1, #3\n\t"
        "bl sub_803AD80\n\t"
    "3:\n\t"
        "sub r5, #1\n\t"
        "b 7f\n\t"
        ".align 2, 0\n"
    "4: .4byte gUnknown_030012B0\n"
    "5: .4byte gUnknown_0300130C\n"
    "6:\n\t"
        "ldr r1, [r4, #0x18]\n\t"
        "mov r2, #0x18\n\t"
        "ldrsh r0, [r1, r2]\n\t"
        "add r0, r4, r0\n\t"
        "ldr r1, [r1, #0x1c]\n\t"
        "bl sub_803AD7C\n\t"
    "7:\n\t"
        "add r5, #1\n\t"
        "ldr r0, [r7]\n\t"
        "ldr r0, [r0]\n\t"
        "cmp r5, r0\n\t"
        "blt 2b\n\t"
    "8:\n\t"
        "mov r1, r8\n\t"
        "ldrb r0, [r1]\n\t"
        "cmp r0, #0\n\t"
        "bne 1b\n\t"
        "pop {r3}\n\t"
        "mov r8, r3\n\t"
        "pop {r4, r5, r6, r7}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
        ".align 2, 0\n"
    );
}

/* Takes no arguments. A short `gUnknown_0300130C` list-scan: for every
 * object whose `sub_803AD7C` overlap-classification against `self` is
 * `3`, whose `+0x4e` state is `0xa`, and whose `+0x4d & 0x7f` is clear,
 * calls `sub_800EEF0(other, 0)` - i.e. settles any object still parked
 * in the "pending edge-4 commit, state 0xa" condition `sub_800EEF0`
 * itself creates (see that function's own doc comment above). Called
 * as the first step of both `sub_800F1B8` (above) and `sub_800F2BC`
 * (below), always as a "flush anything left over from a previous
 * frame" pass before running this frame's own dispatch. */

NAKED void sub_800F258(void)
{
    asm(
        "push {r4, r5, r6, lr}\n\t"
        "mov r5, #0\n\t"
        "ldr r1, 4f\n\t"
        "ldr r0, [r1]\n\t"
        "ldr r0, [r0]\n\t"
        "cmp r5, r0\n\t"
        "bge 3f\n\t"
        "add r6, r1, #0\n\t"
    "1:\n\t"
        "ldr r0, [r6]\n\t"
        "ldr r1, [r0, #8]\n\t"
        "lsl r0, r5, #2\n\t"
        "add r0, r0, r1\n\t"
        "ldr r4, [r0]\n\t"
        "ldr r1, [r4, #0x18]\n\t"
        "add r1, #0x48\n\t"
        "mov r2, #0\n\t"
        "ldrsh r0, [r1, r2]\n\t"
        "add r0, r4, r0\n\t"
        "ldr r1, [r1, #4]\n\t"
        "bl sub_803AD7C\n\t"
        "cmp r0, #3\n\t"
        "bne 2f\n\t"
        "add r0, r4, #0\n\t"
        "add r0, #0x4e\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r0, #0xa\n\t"
        "bne 2f\n\t"
        "add r1, r4, #0\n\t"
        "add r1, #0x4d\n\t"
        "mov r0, #0x7f\n\t"
        "ldrb r1, [r1]\n\t"
        "and r0, r1\n\t"
        "cmp r0, #0\n\t"
        "bne 2f\n\t"
        "add r0, r4, #0\n\t"
        "mov r1, #0\n\t"
        "bl sub_800EEF0\n\t"
    "2:\n\t"
        "add r5, #1\n\t"
        "ldr r0, [r6]\n\t"
        "ldr r0, [r0]\n\t"
        "cmp r5, r0\n\t"
        "blt 1b\n\t"
    "3:\n\t"
        "pop {r4, r5, r6}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
        ".align 2, 0\n"
    "4: .4byte gUnknown_0300130C\n"
    );
}

/* Per-edge jump table's **case 0/1 handler when the dispatch-id row is
 * 6** (`sub_0800D18C`'s/`sub_800E08C`'s shared case 0/1 target - see
 * game_loop47.c's confirmed dispatch map). Early-outs when `self+0x48`
 * is already nonzero (a pending sub-state timer, same field
 * `sub_800F06C` resets to `-1`).
 *
 * Sets `self+0x4d` bit `0x80`, `gUnknown_030012D8+0x80 = 1`, tags
 * `self+0x2d = 0x23` (a "bounced/deflected" state constant, matching
 * this cluster's numbering - `sub_800F368` below uses `0x22` for a
 * closely related case), then runs the
 * `sub_80087C0`/`sub_80087B4`/`sub_800872C` "set tag, refresh
 * sprite/animation" triplet every state-transition function in this
 * cluster shares. Looks up `self`'s hitbox-record row
 * (`self+0x20`-table/`self+0x2d`-tag/28-byte-stride, this subsystem's
 * standard AABB convention) and calls `sub_8006DF8` with its `+0x14`
 * byte to compute a direction/animation nibble, folded into `self+0x29`
 * (low nibble replaced, high nibble kept - `(x & 0xf) | (old & ~0xf)`).
 * Calls `sub_800F258` (flush any pending case-0xa commits), then
 * `sub_8028474(gUnknown_03001318)` (external, unread - likely a score
 * or combo-counter bump) and plays a fixed sound
 * (`gUnknown_030012BC`, id 4). Sets `self+0x48 = 1` (arms the sub-state
 * timer `sub_800F06C` later drains back to `-1`) and calls
 * `sub_802306C(gUnknown_030012C0)` (external, unread). */

NAKED void sub_800F2BC(void *self)
{
    asm(
        "push {r4, r5, r6, lr}\n\t"
        "add r6, r0, #0\n\t"
        "ldr r0, [r6, #0x48]\n\t"
        "cmp r0, #0\n\t"
        "bne 1f\n\t"
        "add r1, r6, #0\n\t"
        "add r1, #0x4d\n\t"
        "mov r0, #0x80\n\t"
        "ldrb r2, [r1]\n\t"
        "orr r0, r2\n\t"
        "strb r0, [r1]\n\t"
        "ldr r0, 2f\n\t"
        "ldr r0, [r0]\n\t"
        "mov r4, #1\n\t"
        "add r0, #0x80\n\t"
        "strb r4, [r0]\n\t"
        "mov r0, #0x23\n\t"
        "add r5, r6, #0\n\t"
        "add r5, #0x2d\n\t"
        "strb r0, [r5]\n\t"
        "add r0, r6, #0\n\t"
        "bl sub_80087C0\n\t"
        "add r0, r6, #0\n\t"
        "bl sub_80087B4\n\t"
        "add r0, r6, #0\n\t"
        "mov r1, #0\n\t"
        "bl sub_800872C\n\t"
        "ldr r0, [r6, #0x20]\n\t"
        "ldr r1, [r0]\n\t"
        "ldrb r3, [r5]\n\t"
        "lsl r0, r3, #3\n\t"
        "sub r0, r0, r3\n\t"
        "lsl r0, r0, #2\n\t"
        "add r1, r1, r0\n\t"
        "ldr r0, 3f\n\t"
        "ldr r0, [r0]\n\t"
        "ldrb r1, [r1, #0x14]\n\t"
        "bl sub_8006DF8\n\t"
        "lsl r0, r0, #0x18\n\t"
        "lsr r0, r0, #0x18\n\t"
        "add r2, r6, #0\n\t"
        "add r2, #0x29\n\t"
        "mov r1, #0xf\n\t"
        "and r0, r1\n\t"
        "mov r1, #0x10\n\t"
        "neg r1, r1\n\t"
        "ldrb r3, [r2]\n\t"
        "and r1, r3\n\t"
        "orr r1, r0\n\t"
        "strb r1, [r2]\n\t"
        "bl sub_800F258\n\t"
        "ldr r0, 4f\n\t"
        "ldr r0, [r0]\n\t"
        "bl sub_8028474\n\t"
        "ldr r0, 5f\n\t"
        "ldr r0, [r0]\n\t"
        "mov r2, #0x80\n\t"
        "lsl r2, r2, #1\n\t"
        "mov r1, #4\n\t"
        "bl PlaySfx\n\t"
        "str r4, [r6, #0x48]\n\t"
        "ldr r0, 6f\n\t"
        "ldr r0, [r0]\n\t"
        "bl sub_802306C\n\t"
    "1:\n\t"
        "pop {r4, r5, r6}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
        ".align 2, 0\n"
    "2: .4byte gUnknown_030012D8\n"
    "3: .4byte gUnknown_030012B8\n"
    "4: .4byte gUnknown_03001318\n"
    "5: .4byte gUnknown_030012BC\n"
    "6: .4byte gUnknown_030012C0\n"
    );
}

/* Per-edge jump table's **case 0/1 handler when the dispatch-id row is
 * 3** (the sibling of `sub_800F2BC` above, same dispatch-map entry, and
 * also called directly by `sub_800F06C`'s/`sub_800F6B8`'s/
 * `sub_800D040`'s own dispatch). Early-outs when `self+0x48` is already
 * `-1` or `0` cleared to the "already handled" sentinels (i.e. only
 * proceeds while it's some other in-progress value) - the inverse
 * early-out shape from `sub_800F2BC`'s simple "nonzero" check.
 *
 * Sets `self+0xc` bit `0x10`, calls `sub_8009150(gUnknown_0300130C,
 * self)` (re-adds `self` to the active list, same call `sub_800EEF0`
 * makes), sets `self+0x4d` bit `0x80` and `gUnknown_030012D8+0x80 = 1`,
 * tags `self+0x2d = 0x22` (this case's own state constant), and runs
 * the same `sub_80087C0`/`sub_80087B4`/`sub_800872C` triplet plus the
 * `sub_8006DF8`-driven `self+0x29` nibble update `sub_800F2BC` uses.
 * Calls `sub_8025A0C(gUnknown_030012B4, self+8)` (marks `self`'s
 * position in the same 32x32 collision-cell bitmap `sub_800EEF0`
 * touches).
 *
 * Then walks `gUnknown_0300130C`'s whole list a *second* time (distinct
 * from the `sub_803AD7C`-classification passes above): collects up to
 * 0x20 other objects whose `sub_803AD7C` result is `3`, `+0x4d & 0x7f
 * == 0`, `+0x4e == 5`, and `+0x50` matches `self+0x50`, into a local
 * stack array, calling `sub_8025A0C` on each of *their* positions too.
 * If any were collected, allocates a heap block sized for the count
 * (`sub_8026EC0`), sets `self+0x59 = 1`, and copies the collected
 * pointer array into it before storing the block at `self+0x48` -
 * building a "linked group of simultaneously-triggered neighbors" list.
 * If none were collected, `self+0x48` gets the `-1` sentinel instead.
 * Tail: clears `self+0x4f` and copies `self+0x4c`'s byte into
 * `self+0x4f` (per-object throttle fields also touched by
 * `sub_800F4F4`/`sub_800F5B8` below). */

NAKED void sub_800F368(void *self)
{
    asm(
        "push {r4, r5, r6, r7, lr}\n\t"
        "mov r7, sl\n\t"
        "mov r6, sb\n\t"
        "mov r5, r8\n\t"
        "push {r5, r6, r7}\n\t"
        "sub sp, #0x80\n\t"
        "add r6, r0, #0\n\t"
        "mov r7, #0\n\t"
        "ldr r1, [r6, #0x48]\n\t"
        "mov r0, #1\n\t"
        "neg r0, r0\n\t"
        "cmp r1, r0\n\t"
        "bne 1f\n\t"
        "b 14f\n\t"
    "1:\n\t"
        "cmp r1, #0\n\t"
        "beq 2f\n\t"
        "b 14f\n\t"
    "2:\n\t"
        "mov r0, #0x10\n\t"
        "ldrb r1, [r6, #0xc]\n\t"
        "orr r0, r1\n\t"
        "strb r0, [r6, #0xc]\n\t"
        "ldr r4, 8f\n\t"
        "ldr r0, [r4]\n\t"
        "add r1, r6, #0\n\t"
        "bl sub_8009150\n\t"
        "add r1, r6, #0\n\t"
        "add r1, #0x4d\n\t"
        "mov r0, #0x80\n\t"
        "ldrb r2, [r1]\n\t"
        "orr r0, r2\n\t"
        "strb r0, [r1]\n\t"
        "ldr r0, 9f\n\t"
        "ldr r0, [r0]\n\t"
        "mov r1, #1\n\t"
        "add r0, #0x80\n\t"
        "strb r1, [r0]\n\t"
        "mov r0, #0x22\n\t"
        "add r5, r6, #0\n\t"
        "add r5, #0x2d\n\t"
        "strb r0, [r5]\n\t"
        "add r0, r6, #0\n\t"
        "bl sub_80087C0\n\t"
        "add r0, r6, #0\n\t"
        "bl sub_80087B4\n\t"
        "add r0, r6, #0\n\t"
        "mov r1, #0\n\t"
        "bl sub_800872C\n\t"
        "ldr r0, [r6, #0x20]\n\t"
        "ldr r1, [r0]\n\t"
        "ldrb r3, [r5]\n\t"
        "lsl r0, r3, #3\n\t"
        "sub r0, r0, r3\n\t"
        "lsl r0, r0, #2\n\t"
        "add r1, r1, r0\n\t"
        "ldr r0, 10f\n\t"
        "ldr r0, [r0]\n\t"
        "ldrb r1, [r1, #0x14]\n\t"
        "bl sub_8006DF8\n\t"
        "lsl r0, r0, #0x18\n\t"
        "lsr r0, r0, #0x18\n\t"
        "add r2, r6, #0\n\t"
        "add r2, #0x29\n\t"
        "mov r1, #0xf\n\t"
        "and r0, r1\n\t"
        "mov r1, #0x10\n\t"
        "neg r1, r1\n\t"
        "ldrb r3, [r2]\n\t"
        "and r1, r3\n\t"
        "orr r1, r0\n\t"
        "strb r1, [r2]\n\t"
        "ldr r0, 11f\n\t"
        "ldr r0, [r0]\n\t"
        "ldrh r1, [r6, #8]\n\t"
        "bl sub_8025A0C\n\t"
        "mov r5, #0\n\t"
        "ldr r0, [r4]\n\t"
        "ldr r0, [r0]\n\t"
        "mov r1, #0x50\n\t"
        "add r1, r1, r6\n\t"
        "mov r8, r1\n\t"
        "mov r2, #0x4c\n\t"
        "add r2, r2, r6\n\t"
        "mov sb, r2\n\t"
        "mov r3, #0x4f\n\t"
        "add r3, r3, r6\n\t"
        "mov sl, r3\n\t"
        "cmp r7, r0\n\t"
        "bge 5f\n\t"
    "3:\n\t"
        "ldr r0, 8f\n\t"
        "ldr r0, [r0]\n\t"
        "ldr r1, [r0, #8]\n\t"
        "lsl r0, r5, #2\n\t"
        "add r0, r0, r1\n\t"
        "ldr r4, [r0]\n\t"
        "ldr r1, [r4, #0x18]\n\t"
        "add r1, #0x48\n\t"
        "mov r2, #0\n\t"
        "ldrsh r0, [r1, r2]\n\t"
        "add r0, r4, r0\n\t"
        "ldr r1, [r1, #4]\n\t"
        "bl sub_803AD7C\n\t"
        "cmp r0, #3\n\t"
        "bne 4f\n\t"
        "add r1, r4, #0\n\t"
        "add r1, #0x4d\n\t"
        "mov r0, #0x7f\n\t"
        "ldrb r1, [r1]\n\t"
        "and r0, r1\n\t"
        "cmp r0, #0\n\t"
        "bne 4f\n\t"
        "add r0, r4, #0\n\t"
        "add r0, #0x4e\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r0, #5\n\t"
        "bne 4f\n\t"
        "add r0, r4, #0\n\t"
        "add r0, #0x50\n\t"
        "ldrb r0, [r0]\n\t"
        "mov r3, r8\n\t"
        "ldrb r3, [r3]\n\t"
        "cmp r0, r3\n\t"
        "bne 4f\n\t"
        "lsl r0, r7, #2\n\t"
        "add r0, sp\n\t"
        "str r4, [r0]\n\t"
        "add r7, #1\n\t"
        "mov r0, #0x1f\n\t"
        "and r7, r0\n\t"
        "ldr r0, 11f\n\t"
        "ldr r0, [r0]\n\t"
        "ldrh r1, [r4, #8]\n\t"
        "bl sub_8025A0C\n\t"
    "4:\n\t"
        "add r5, #1\n\t"
        "ldr r0, 8f\n\t"
        "ldr r0, [r0]\n\t"
        "ldr r0, [r0]\n\t"
        "cmp r5, r0\n\t"
        "blt 3b\n\t"
    "5:\n\t"
        "cmp r7, #0\n\t"
        "beq 12f\n\t"
        "add r0, r7, #1\n\t"
        "lsl r0, r0, #2\n\t"
        "bl sub_8026EC0\n\t"
        "add r2, r0, #0\n\t"
        "add r1, r6, #0\n\t"
        "add r1, #0x59\n\t"
        "mov r0, #1\n\t"
        "strb r0, [r1]\n\t"
        "str r7, [r2]\n\t"
        "cmp r7, #0\n\t"
        "ble 7f\n\t"
        "mov r3, sp\n\t"
        "add r1, r2, #0\n\t"
        "add r5, r7, #0\n\t"
    "6:\n\t"
        "ldm r3!, {r0}\n\t"
        "str r0, [r1, #4]\n\t"
        "add r1, #4\n\t"
        "sub r5, #1\n\t"
        "cmp r5, #0\n\t"
        "bne 6b\n\t"
    "7:\n\t"
        "str r2, [r6, #0x48]\n\t"
        "b 13f\n\t"
        ".align 2, 0\n"
    "8: .4byte gUnknown_0300130C\n"
    "9: .4byte gUnknown_030012D8\n"
    "10: .4byte gUnknown_030012B8\n"
    "11: .4byte gUnknown_030012B4\n"
    "12:\n\t"
        "mov r0, #1\n\t"
        "neg r0, r0\n\t"
        "str r0, [r6, #0x48]\n\t"
    "13:\n\t"
        "mov r0, #0\n\t"
        "mov r1, r8\n\t"
        "strb r0, [r1]\n\t"
        "mov r2, sb\n\t"
        "ldrb r0, [r2]\n\t"
        "mov r3, sl\n\t"
        "strb r0, [r3]\n\t"
    "14:\n\t"
        "add sp, #0x80\n\t"
        "pop {r3, r4, r5}\n\t"
        "mov r8, r3\n\t"
        "mov sb, r4\n\t"
        "mov sl, r5\n\t"
        "pop {r4, r5, r6, r7}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
    );
}

/* Called from `sub_800F5B8`'s own jump-table-driven state machine
 * indirectly via re-entry (see below) and from the still-raw
 * `0x080104E4` continuation (outside this issue's scope) whenever
 * `self+0x4e` is in `0x13`-`0x15`. Bumps `self+0x50` (a per-object
 * "successive triggers" counter) and compares it against `self+0x51`
 * (a per-object cap). Once the cap is reached: if `self+0x48` (the
 * linked-group pointer `sub_800F368` builds) holds more than one
 * element, calls `sub_8026EB4` (frees it, already-elsewhere-matched);
 * resets `self+0x48` to `-1` and `self+0x4e = 7` (a distinct "group
 * exhausted" state).
 *
 * While still under the cap: if `self+0x48`'s group has more than one
 * member, walks every member whose own `+0x4e == 5` and `+0x51 <=
 * self`'s own cached `+0x4c` throttle byte, calling `sub_800F5B8`
 * (below) on each - recursively settling every other object in the
 * same triggered group - and plays a single shared sound
 * (`gUnknown_030012BC`, id 0xf) the first time any member is actually
 * settled this call (a `once`-flag local keeps it from repeating per
 * member). */

NAKED void sub_800F4F4(void *self)
{
    asm(
        "push {r4, r5, r6, r7, lr}\n\t"
        "mov r7, sb\n\t"
        "mov r6, r8\n\t"
        "push {r6, r7}\n\t"
        "add r4, r0, #0\n\t"
        "add r3, r4, #0\n\t"
        "add r3, #0x4f\n\t"
        "ldrb r5, [r3]\n\t"
        "cmp r5, #0\n\t"
        "bne 7f\n\t"
        "add r1, r4, #0\n\t"
        "add r1, #0x50\n\t"
        "ldrb r0, [r1]\n\t"
        "add r0, #1\n\t"
        "strb r0, [r1]\n\t"
        "add r2, r4, #0\n\t"
        "add r2, #0x51\n\t"
        "lsl r0, r0, #0x18\n\t"
        "lsr r0, r0, #0x18\n\t"
        "add r7, r1, #0\n\t"
        "ldrb r2, [r2]\n\t"
        "cmp r0, r2\n\t"
        "blo 3f\n\t"
        "ldr r1, [r4, #0x48]\n\t"
        "add r0, r1, #1\n\t"
        "cmp r0, #1\n\t"
        "bls 2f\n\t"
        "cmp r1, #0\n\t"
        "beq 1f\n\t"
        "add r0, r1, #0\n\t"
        "bl sub_8026EB4\n\t"
    "1:\n\t"
        "add r0, r4, #0\n\t"
        "add r0, #0x59\n\t"
        "strb r5, [r0]\n\t"
    "2:\n\t"
        "mov r0, #1\n\t"
        "neg r0, r0\n\t"
        "str r0, [r4, #0x48]\n\t"
        "mov r1, #7\n\t"
        "add r0, r4, #0\n\t"
        "add r0, #0x4e\n\t"
        "strb r1, [r0]\n\t"
        "b 7f\n\t"
    "3:\n\t"
        "ldr r1, [r4, #0x48]\n\t"
        "add r0, r1, #1\n\t"
        "mov sb, r3\n\t"
        "add r4, #0x4c\n\t"
        "mov r8, r4\n\t"
        "cmp r0, #1\n\t"
        "bls 6f\n\t"
        "ldm r1!, {r2}\n\t"
        "add r0, r1, #0\n\t"
        "mov r6, #0\n\t"
        "cmp r2, #0\n\t"
        "ble 6f\n\t"
        "add r4, r0, #0\n\t"
        "add r5, r2, #0\n\t"
    "4:\n\t"
        "ldr r0, [r4]\n\t"
        "add r1, r0, #0\n\t"
        "add r1, #0x4e\n\t"
        "ldrb r1, [r1]\n\t"
        "cmp r1, #5\n\t"
        "bne 5f\n\t"
        "add r1, r0, #0\n\t"
        "add r1, #0x51\n\t"
        "ldrb r2, [r7]\n\t"
        "ldrb r1, [r1]\n\t"
        "cmp r2, r1\n\t"
        "blo 5f\n\t"
        "bl sub_800F5B8\n\t"
        "cmp r6, #0\n\t"
        "bne 5f\n\t"
        "ldr r0, 8f\n\t"
        "ldr r0, [r0]\n\t"
        "mov r1, #0xf\n\t"
        "mov r2, #0x80\n\t"
        "lsl r2, r2, #1\n\t"
        "bl PlaySfx\n\t"
        "mov r6, #1\n\t"
    "5:\n\t"
        "add r4, #4\n\t"
        "sub r5, #1\n\t"
        "cmp r5, #0\n\t"
        "bne 4b\n\t"
    "6:\n\t"
        "mov r1, r8\n\t"
        "ldrb r0, [r1]\n\t"
        "mov r2, sb\n\t"
        "strb r0, [r2]\n\t"
    "7:\n\t"
        "pop {r3, r4}\n\t"
        "mov r8, r3\n\t"
        "mov sb, r4\n\t"
        "pop {r4, r5, r6, r7}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
        ".align 2, 0\n"
    "8: .4byte gUnknown_030012BC\n"
    );
}

/* Called by `sub_800F4F4` above (settling every member of a triggered
 * group) and directly from the still-raw `0x080104E4` continuation for
 * `self+0x4e` in `0x13`-`0x15` (outside this issue's scope). Decrements
 * `self+0x48` by `0x15` into `self+0x4e` (reusing the incoming state id
 * as a byte offset into itself - a compact re-dispatch trick this
 * function uses instead of a separate id field), then runs a
 * 0x13-entry jump table (`self+0x4e` post-subtraction, `bhi` gated at
 * `0x12`) that maps each of 15 distinct sub-cases to one of a small set
 * of `self+0x2d` tag constants (`0x1f, 0x1a, 0x17, 0x18, 4, 0x20, 2, 5,
 * 0x19 (with a nested self+0x48 = -0x2a store), 6, 0x11, 0xe, 0xf, 0x10
 * (a distinct "no group" tag)`), each falling into the same shared
 * `sub_80087C0`/`sub_80087B4`/`sub_800872C` triplet, plus 4 cases
 * (`3, 5, 9, 11`, per the raw table's own indices) that skip straight
 * to the tail instead. Tail (`self+0x29` nibble update via
 * `sub_800815C(self)`) matches the same `(x & 0xf) | (old & ~0xf)` fold
 * `sub_800F2BC`/`sub_800F368` use, just via a different lookup helper
 * (`sub_800815C` instead of `sub_8006DF8` directly - presumably an
 * already-classified variant). */

NAKED void sub_800F5B8(void *self)
{
    asm(
        "push {r4, lr}\n\t"
        "add r4, r0, #0\n\t"
        "ldr r0, [r4, #0x48]\n\t"
        "sub r0, #0x15\n\t"
        "add r1, r4, #0\n\t"
        "add r1, #0x4e\n\t"
        "strb r0, [r1]\n\t"
        "ldrb r0, [r1]\n\t"
        "cmp r0, #0x12\n\t"
        "bhi 18f\n\t"
        "lsl r0, r0, #2\n\t"
        "ldr r1, 1f\n\t"
        "add r0, r0, r1\n\t"
        "ldr r0, [r0]\n\t"
        "mov pc, r0\n\t"
        ".align 2, 0\n"
    "1: .4byte 2f\n"
    "2:\n\t"
        ".4byte 3f\n\t"
        ".4byte 4f\n\t"
        ".4byte 5f\n\t"
        ".4byte 18f\n\t"
        ".4byte 6f\n\t"
        ".4byte 18f\n\t"
        ".4byte 7f\n\t"
        ".4byte 8f\n\t"
        ".4byte 9f\n\t"
        ".4byte 18f\n\t"
        ".4byte 10f\n\t"
        ".4byte 18f\n\t"
        ".4byte 11f\n\t"
        ".4byte 12f\n\t"
        ".4byte 13f\n\t"
        ".4byte 18f\n\t"
        ".4byte 14f\n\t"
        ".4byte 15f\n\t"
        ".4byte 17f\n\t"
    "3:\n\t"
        "mov r0, #0x1f\n\t"
        "b 16f\n\t"
    "4:\n\t"
        "mov r0, #0x1a\n\t"
        "b 16f\n\t"
    "5:\n\t"
        "mov r0, #0x17\n\t"
        "b 16f\n\t"
    "6:\n\t"
        "mov r0, #0x18\n\t"
        "b 16f\n\t"
    "7:\n\t"
        "mov r0, #4\n\t"
        "b 16f\n\t"
    "8:\n\t"
        "mov r0, #0x20\n\t"
        "b 16f\n\t"
    "9:\n\t"
        "mov r0, #2\n\t"
        "b 16f\n\t"
    "10:\n\t"
        "mov r0, #5\n\t"
        "b 16f\n\t"
    "11:\n\t"
        "mov r0, #0x2a\n\t"
        "neg r0, r0\n\t"
        "str r0, [r4, #0x48]\n\t"
        "mov r0, #0x19\n\t"
        "b 16f\n\t"
    "12:\n\t"
        "mov r0, #6\n\t"
        "b 16f\n\t"
    "13:\n\t"
        "mov r0, #0x11\n\t"
        "b 16f\n\t"
    "14:\n\t"
        "mov r0, #0xe\n\t"
        "b 16f\n\t"
    "15:\n\t"
        "mov r0, #0xf\n\t"
    "16:\n\t"
        "add r1, r4, #0\n\t"
        "add r1, #0x2d\n\t"
        "strb r0, [r1]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087C0\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087B4\n\t"
        "add r0, r4, #0\n\t"
        "mov r1, #0\n\t"
        "bl sub_800872C\n\t"
        "b 18f\n\t"
    "17:\n\t"
        "mov r0, #0x10\n\t"
        "add r1, r4, #0\n\t"
        "add r1, #0x2d\n\t"
        "strb r0, [r1]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087C0\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087B4\n\t"
        "add r0, r4, #0\n\t"
        "mov r1, #0\n\t"
        "bl sub_800872C\n\t"
    "18:\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_800815C\n\t"
        "add r2, r4, #0\n\t"
        "add r2, #0x29\n\t"
        "mov r1, #0xf\n\t"
        "and r0, r1\n\t"
        "mov r1, #0x10\n\t"
        "neg r1, r1\n\t"
        "ldrb r3, [r2]\n\t"
        "and r1, r3\n\t"
        "orr r1, r0\n\t"
        "strb r1, [r2]\n\t"
        "pop {r4}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
    );
}

/* `sub_800F6B8(s32 x, s32 y, s32 arg2, s32 arg3)` - the one function in
 * this group taking a raw position/box instead of a `self` pointer (see
 * `src/graphics/actor_part38.c`'s existing extern: called as
 * `sub_800F6B8(part->x >> 8, part->y >> 8, 0x40, 0x12)`, a fixed
 * 0x40x0x12 probe box around an actor-part's own position). Walks
 * `gUnknown_0300130C`'s whole list: for every object whose
 * `sub_803AD7C` classification against the probe box is `3`, whose
 * Chebyshev distance is within `(arg2, arg3)` on X/Y respectively, and
 * whose `+0x4d & 0x7f == 0`, looks up
 * `gStaticData_0816BBC4[other+0x4e]`: if that row's
 * `gStaticData_0816BBAE` byte is set, dispatches `1` ->
 * `sub_800E6B0(other)`, else `sub_800E7A8(other, 0, 0, 0)`; if the row
 * itself is `0`, calls `sub_800EEF0(other, 0)` instead. The same
 * "settle nearby objects against a probe box" shape as
 * `sub_800F06C`/`sub_800F798`, just driven by an explicit box rather
 * than `self`'s own hitbox record. */

NAKED void sub_800F6B8(s32 x, s32 y, s32 arg2, s32 arg3)
{
    asm(
        "push {r4, r5, r6, r7, lr}\n\t"
        "mov r7, sl\n\t"
        "mov r6, sb\n\t"
        "mov r5, r8\n\t"
        "push {r5, r6, r7}\n\t"
        "mov sb, r0\n\t"
        "mov r8, r1\n\t"
        "add r7, r2, #0\n\t"
        "add r6, r3, #0\n\t"
        "mov r5, #0\n\t"
        "ldr r0, 2f\n\t"
        "ldr r0, [r0]\n\t"
        "ldr r0, [r0]\n\t"
        "cmp r5, r0\n\t"
        "bge 8f\n\t"
        "ldr r0, 3f\n\t"
        "mov sl, r0\n\t"
    "1:\n\t"
        "ldr r0, 2f\n\t"
        "ldr r0, [r0]\n\t"
        "ldr r1, [r0, #8]\n\t"
        "lsl r0, r5, #2\n\t"
        "add r0, r0, r1\n\t"
        "ldr r4, [r0]\n\t"
        "ldr r1, [r4, #0x18]\n\t"
        "add r1, #0x48\n\t"
        "mov r2, #0\n\t"
        "ldrsh r0, [r1, r2]\n\t"
        "add r0, r4, r0\n\t"
        "ldr r1, [r1, #4]\n\t"
        "bl sub_803AD7C\n\t"
        "cmp r0, #3\n\t"
        "bne 7f\n\t"
        "ldr r1, [r4]\n\t"
        "asr r1, r1, #8\n\t"
        "mov r0, sb\n\t"
        "sub r1, r1, r0\n\t"
        "asr r0, r1, #0x1f\n\t"
        "eor r1, r0\n\t"
        "sub r1, r1, r0\n\t"
        "ldr r0, [r4, #4]\n\t"
        "asr r0, r0, #8\n\t"
        "mov r2, r8\n\t"
        "sub r0, r0, r2\n\t"
        "asr r2, r0, #0x1f\n\t"
        "eor r0, r2\n\t"
        "sub r0, r0, r2\n\t"
        "add r1, r1, r0\n\t"
        "cmp r1, r7\n\t"
        "bgt 7f\n\t"
        "cmp r0, r6\n\t"
        "bge 7f\n\t"
        "add r1, r4, #0\n\t"
        "add r1, #0x4d\n\t"
        "mov r0, #0x7f\n\t"
        "ldrb r1, [r1]\n\t"
        "and r0, r1\n\t"
        "cmp r0, #0\n\t"
        "bne 7f\n\t"
        "add r0, r4, #0\n\t"
        "add r0, #0x4e\n\t"
        "ldrb r1, [r0]\n\t"
        "mov r2, sl\n\t"
        "add r0, r1, r2\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r0, #0\n\t"
        "beq 4f\n\t"
        "add r0, r4, #0\n\t"
        "mov r1, #0\n\t"
        "bl sub_800EEF0\n\t"
        "b 7f\n\t"
        ".align 2, 0\n"
    "2: .4byte gUnknown_0300130C\n"
    "3: .4byte gStaticData_0816BBC4\n"
    "4:\n\t"
        "ldr r0, 5f\n\t"
        "add r0, r1, r0\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r0, #0\n\t"
        "beq 7f\n\t"
        "cmp r1, #1\n\t"
        "bne 6f\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_800E6B0\n\t"
        "b 7f\n\t"
        ".align 2, 0\n"
    "5: .4byte gStaticData_0816BBAE\n"
    "6:\n\t"
        "add r0, r4, #0\n\t"
        "mov r1, #0\n\t"
        "mov r2, #0\n\t"
        "mov r3, #0\n\t"
        "bl sub_800E7A8\n\t"
    "7:\n\t"
        "add r5, #1\n\t"
        "ldr r0, 9f\n\t"
        "ldr r0, [r0]\n\t"
        "ldr r0, [r0]\n\t"
        "cmp r5, r0\n\t"
        "blt 1b\n\t"
    "8:\n\t"
        "pop {r3, r4, r5}\n\t"
        "mov r8, r3\n\t"
        "mov sb, r4\n\t"
        "mov sl, r5\n\t"
        "pop {r4, r5, r6, r7}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
        ".align 2, 0\n"
    "9: .4byte gUnknown_0300130C\n"
    );
}

/* Called from the still-raw `0x080104E4` continuation
 * (`self+0x4d & 0x7f == 1` case, outside this issue's scope) - the
 * per-edge jump table's shared entry point once `self`'s own commit is
 * already underway. Looks up `gStaticData_0816BBC4[self+0x4e]`: if
 * nonzero and `self+0x34 == 0` (no pending sub-effect), dispatches on
 * `self+0x30` (`3` -> `sub_800F06C(self, 0x14)`, `6` ->
 * `sub_800F06C(self, 0x28)` - see that function's own doc comment).
 *
 * If `self+0x38` is set (a "linked to neighbors" flag), re-links
 * `self`'s `sub_8010708`/`sub_801070C` neighbor-list pointers
 * (`sub_8010710`/`sub_8010714`, already-elsewhere-matched splice
 * helpers) to remove `self` from the list. Unless `self+0x4e == 1`,
 * marks `self` "visited this frame" in `gUnknown_030012B0`'s per-cell
 * bitmap (the same 32x32-grid convention `sub_800EEF0`/`sub_800F368`
 * use, here against `gUnknown_030012B4`) and walks
 * `gUnknown_030012D8+0x94`'s "recently touched" ring buffer
 * (`sub_0800D18C`'s own 5-slot buffer, per game_loop47.c's doc comment)
 * clearing each slot's `+0x94` re-visit flag once it matches `self`.
 *
 * If `self+0x38` was clear instead, and `self+0x4e != 1`, sets
 * `gUnknown_030012B0 = 1` (a one-shot "re-scan next pass" flag -
 * `sub_800F1B8`'s own outer loop condition above) unconditionally. */

NAKED void sub_800F798(void *self)
{
    asm(
        "push {r4, r5, r6, lr}\n\t"
        "add r6, r0, #0\n\t"
        "ldr r0, 1f\n\t"
        "add r1, r6, #0\n\t"
        "add r1, #0x4e\n\t"
        "ldrb r1, [r1]\n\t"
        "add r0, r1, r0\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r0, #0\n\t"
        "beq 3f\n\t"
        "ldr r0, [r6, #0x34]\n\t"
        "cmp r0, #0\n\t"
        "bne 3f\n\t"
        "ldr r0, [r6, #0x30]\n\t"
        "cmp r0, #3\n\t"
        "bne 2f\n\t"
        "add r0, r6, #0\n\t"
        "mov r1, #0x14\n\t"
        "bl sub_800F06C\n\t"
        "b 3f\n\t"
        ".align 2, 0\n"
    "1: .4byte gStaticData_0816BBC4\n"
    "2:\n\t"
        "cmp r0, #6\n\t"
        "bne 3f\n\t"
        "add r0, r6, #0\n\t"
        "mov r1, #0x28\n\t"
        "bl sub_800F06C\n\t"
    "3:\n\t"
        "add r0, r6, #0\n\t"
        "add r0, #0x38\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r0, #0\n\t"
        "beq 17f\n\t"
        "add r0, r6, #0\n\t"
        "bl sub_8010708\n\t"
        "add r5, r0, #0\n\t"
        "add r0, r6, #0\n\t"
        "bl sub_801070C\n\t"
        "add r4, r0, #0\n\t"
        "cmp r5, #0\n\t"
        "beq 4f\n\t"
        "cmp r4, #0\n\t"
        "beq 5f\n\t"
        "add r1, r5, #0\n\t"
        "bl sub_8010710\n\t"
        "add r0, r5, #0\n\t"
        "add r1, r4, #0\n\t"
        "bl sub_8010714\n\t"
        "b 6f\n\t"
    "4:\n\t"
        "cmp r4, #0\n\t"
        "beq 5f\n\t"
        "add r0, r4, #0\n\t"
        "mov r1, #0\n\t"
        "bl sub_8010710\n\t"
        "b 6f\n\t"
    "5:\n\t"
        "cmp r5, #0\n\t"
        "beq 6f\n\t"
        "add r0, r5, #0\n\t"
        "mov r1, #0\n\t"
        "bl sub_8010714\n\t"
    "6:\n\t"
        "add r0, r6, #0\n\t"
        "add r0, #0x4e\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r0, #1\n\t"
        "beq 18f\n\t"
        "ldr r0, 10f\n\t"
        "mov r1, #1\n\t"
        "strb r1, [r0]\n\t"
        "ldrb r0, [r6, #0xc]\n\t"
        "orr r1, r0\n\t"
        "strb r1, [r6, #0xc]\n\t"
        "ldr r0, 11f\n\t"
        "ldrh r1, [r6, #8]\n\t"
        "cmp r1, r0\n\t"
        "beq 7f\n\t"
        "ldrh r3, [r6, #8]\n\t"
        "ldr r0, 12f\n\t"
        "ldr r2, [r0]\n\t"
        "add r0, r3, #0\n\t"
        "asr r0, r0, #5\n\t"
        "lsl r1, r0, #2\n\t"
        "mov r4, #0x84\n\t"
        "lsl r4, r4, #1\n\t"
        "add r2, r2, r4\n\t"
        "add r2, r2, r1\n\t"
        "lsl r0, r0, #5\n\t"
        "sub r0, r3, r0\n\t"
        "mov r1, #1\n\t"
        "lsl r1, r0\n\t"
        "ldr r0, [r2]\n\t"
        "orr r0, r1\n\t"
        "str r0, [r2]\n\t"
    "7:\n\t"
        "mov r3, #0\n\t"
        "ldr r1, 13f\n\t"
        "ldr r0, [r1]\n\t"
        "add r0, #0x94\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r3, r0\n\t"
        "bge 18f\n\t"
        "add r4, r1, #0\n\t"
    "8:\n\t"
        "ldr r2, [r4]\n\t"
        "add r0, r2, #0\n\t"
        "add r0, #0x88\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r0, #0\n\t"
        "bne 14f\n\t"
        "cmp r3, #4\n\t"
        "ble 9f\n\t"
        "add r0, r2, #0\n\t"
        "add r0, #0x94\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r3, r0\n\t"
        "bge 14f\n\t"
    "9:\n\t"
        "lsl r1, r3, #2\n\t"
        "add r0, r2, #0\n\t"
        "add r0, #0x98\n\t"
        "add r0, r0, r1\n\t"
        "ldr r0, [r0]\n\t"
        "b 15f\n\t"
        ".align 2, 0\n"
    "10: .4byte gUnknown_030012B0\n"
    "11: .4byte 0x0000FFFF\n"
    "12: .4byte gUnknown_030012B4\n"
    "13: .4byte gUnknown_030012D8\n"
    "14:\n\t"
        "mov r0, #0\n\t"
    "15:\n\t"
        "cmp r0, r6\n\t"
        "bne 16f\n\t"
        "ldr r0, [r4]\n\t"
        "add r0, #0x94\n\t"
        "mov r1, #0\n\t"
        "strb r1, [r0]\n\t"
    "16:\n\t"
        "add r3, #1\n\t"
        "ldr r0, [r4]\n\t"
        "add r0, #0x94\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r3, r0\n\t"
        "blt 8b\n\t"
        "b 18f\n\t"
    "17:\n\t"
        "add r0, r6, #0\n\t"
        "add r0, #0x4e\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r0, #1\n\t"
        "beq 18f\n\t"
        "ldr r1, 19f\n\t"
        "mov r0, #1\n\t"
        "strb r0, [r1]\n\t"
    "18:\n\t"
        "pop {r4, r5, r6}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
        ".align 2, 0\n"
    "19: .4byte gUnknown_030012B0\n"
    );
}

/* Called from `sub_800EEF0` indirectly (both converge on
 * `self+0x4e` settling to `0x13`) and reachable from the per-edge
 * dispatch whenever a settled object's state lands in `0x13`-`0x15`.
 * Early-outs when `self+0x4f` (the per-object throttle byte
 * `sub_800F368` seeds from `self+0x4c`) is already nonzero. Otherwise
 * dispatches on `self+0x4e`:
 *
 * - `0x14`: tags `self+0x2d = 0x12`, runs the
 *   `sub_80087C0`/`sub_80087B4`/`sub_800872C` triplet, plays a sound
 *   (`gUnknown_030012BC`, id 0x11), then falls into the shared tail
 *   with `self+0x4e = 0x13`, `self+0x4f = 0x3c` (a ~1-second cooldown
 *   at 60 fps).
 * - `> 0x14` (only `0x15` reaches here, `bgt` from the `0x14` compare):
 *   same triplet + sound + tail, but tags `0x13` first and re-enters
 *   with `self+0x4e = 0x14` instead - a one-step state regression
 *   rather than the terminal settle the `0x14` case takes.
 * - `0x13`: if `self+0x4d & 0x7f == 0`, calls `sub_800EEF0(self, 0)` -
 *   the same "commit the edge collision" call the per-edge dispatch
 *   itself makes, closing the loop back into `sub_800EEF0` above.
 * - anything else: no-op. */

NAKED void sub_800F8E0(void *self)
{
    asm(
        "push {r4, r5, r6, lr}\n\t"
        "add r4, r0, #0\n\t"
        "add r6, r4, #0\n\t"
        "add r6, #0x4f\n\t"
        "ldrb r0, [r6]\n\t"
        "cmp r0, #0\n\t"
        "bne 7f\n\t"
        "add r5, r4, #0\n\t"
        "add r5, #0x4e\n\t"
        "ldrb r0, [r5]\n\t"
        "add r1, r0, #0\n\t"
        "cmp r0, #0x14\n\t"
        "beq 3f\n\t"
        "cmp r0, #0x14\n\t"
        "bgt 1f\n\t"
        "cmp r0, #0x13\n\t"
        "beq 6f\n\t"
        "b 7f\n\t"
    "1:\n\t"
        "cmp r1, #0x15\n\t"
        "bne 7f\n\t"
        "mov r0, #0x13\n\t"
        "add r1, r4, #0\n\t"
        "add r1, #0x2d\n\t"
        "strb r0, [r1]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087C0\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087B4\n\t"
        "add r0, r4, #0\n\t"
        "mov r1, #0\n\t"
        "bl sub_800872C\n\t"
        "ldr r0, 2f\n\t"
        "ldr r0, [r0]\n\t"
        "mov r2, #0x80\n\t"
        "lsl r2, r2, #1\n\t"
        "mov r1, #0x11\n\t"
        "bl PlaySfx\n\t"
        "mov r0, #0x14\n\t"
        "b 4f\n\t"
        ".align 2, 0\n"
    "2: .4byte gUnknown_030012BC\n"
    "3:\n\t"
        "mov r0, #0x12\n\t"
        "add r1, r4, #0\n\t"
        "add r1, #0x2d\n\t"
        "strb r0, [r1]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087C0\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087B4\n\t"
        "add r0, r4, #0\n\t"
        "mov r1, #0\n\t"
        "bl sub_800872C\n\t"
        "ldr r0, 5f\n\t"
        "ldr r0, [r0]\n\t"
        "mov r2, #0x80\n\t"
        "lsl r2, r2, #1\n\t"
        "mov r1, #0x11\n\t"
        "bl PlaySfx\n\t"
        "mov r0, #0x13\n\t"
    "4:\n\t"
        "strb r0, [r5]\n\t"
        "mov r0, #0x3c\n\t"
        "strb r0, [r6]\n\t"
        "b 7f\n\t"
        ".align 2, 0\n"
    "5: .4byte gUnknown_030012BC\n"
    "6:\n\t"
        "add r1, r4, #0\n\t"
        "add r1, #0x4d\n\t"
        "mov r0, #0x7f\n\t"
        "ldrb r1, [r1]\n\t"
        "and r0, r1\n\t"
        "cmp r0, #0\n\t"
        "bne 7f\n\t"
        "add r0, r4, #0\n\t"
        "mov r1, #0\n\t"
        "bl sub_800EEF0\n\t"
    "7:\n\t"
        "pop {r4, r5, r6}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
    );
}

/* The largest and last function in this cluster
 * (0x0800F990-0x0800FC70, ~736 B). Called from the still-raw
 * `0x080104E4` continuation (`self+0x4e == 0xf`, outside this issue's
 * scope) - a **per-frame position-wrap/edge-scan advance**, structurally
 * similar to the already-parked `sub_800FC70`
 * (docs/matching/issue-13-fc70-continuation.md) that immediately
 * follows this whole cluster.
 *
 * First, unless `self+0x48` already has its `0xc0` high bits set,
 * clamps `self`'s position to within 0x4f/0x3f px of
 * `gUnknown_030012D8` (the player) on X/Y respectively, folding the
 * result into `self+0x48`'s packed byte (`(x & 0x3f) | 0x40`, masked
 * against `0xc7`, then `| 0x10`) - a "snap into range" step. Early-outs
 * entirely (jumps to the tail) once `self+0x4f` is nonzero.
 *
 * The bulk of the function is a small state cycle keyed by
 * `self+0x48 & 7`, advanced via `(x+1) & 3` each call and masked back
 * into `self+0x48`'s low 3 bits - a 4-phase rotation (only entered when
 * `self+0x2d == 8`, a specific tag this cluster's other functions write
 * via the `sub_80087C0` triplet) that dispatches each phase (`0`, `1`,
 * `2`, `3`, sub-split further by the *previous* phase value in a nested
 * compare) into per-phase blocks. These re-tag `self+0x2d`, re-run the
 * `sub_80087C0`/`sub_80087B4`/`sub_800872C` triplet, and (per the
 * `0xc0`-bit branch taken near the top) call `sub_8010A50(self)` -
 * already matched elsewhere (`game_loop30.c` family) - to decide
 * whether the phase cycle continues or the object's position gets
 * finally committed. Given the size and self-contained nature of this
 * state cycle (no calls out to any other function in this cluster), a
 * full branch-by-branch semantic write-up was not attempted for this
 * pass - the NAKED transcription is verified byte-exact independent of
 * that understanding. */

NAKED void sub_800F990(void *self)
{
    asm(
        "push {r4, r5, r6, r7, lr}\n\t"
        "mov r7, sb\n\t"
        "mov r6, r8\n\t"
        "push {r6, r7}\n\t"
        "add r4, r0, #0\n\t"
        "ldr r2, [r4, #0x48]\n\t"
        "mov r0, #0xc0\n\t"
        "and r0, r2\n\t"
        "cmp r0, #0\n\t"
        "bne 3f\n\t"
        "ldr r0, 8f\n\t"
        "ldr r3, [r0]\n\t"
        "ldr r0, [r3]\n\t"
        "asr r1, r0, #8\n\t"
        "ldr r0, [r4]\n\t"
        "asr r0, r0, #8\n\t"
        "sub r1, r1, r0\n\t"
        "cmp r1, #0\n\t"
        "bge 1f\n\t"
        "neg r1, r1\n\t"
    "1:\n\t"
        "cmp r1, #0x4f\n\t"
        "bgt 3f\n\t"
        "ldr r0, [r3, #4]\n\t"
        "asr r1, r0, #8\n\t"
        "ldr r0, [r4, #4]\n\t"
        "asr r0, r0, #8\n\t"
        "sub r1, r1, r0\n\t"
        "cmp r1, #0\n\t"
        "bge 2f\n\t"
        "neg r1, r1\n\t"
    "2:\n\t"
        "cmp r1, #0x3f\n\t"
        "bgt 3f\n\t"
        "mov r0, #0x3f\n\t"
        "and r2, r0\n\t"
        "mov r0, #0x40\n\t"
        "orr r2, r0\n\t"
        "mov r0, #0xc7\n\t"
        "and r2, r0\n\t"
        "mov r0, #0x10\n\t"
        "orr r2, r0\n\t"
        "str r2, [r4, #0x48]\n\t"
    "3:\n\t"
        "add r0, r4, #0\n\t"
        "add r0, #0x4f\n\t"
        "ldrb r1, [r0]\n\t"
        "mov sb, r0\n\t"
        "cmp r1, #0\n\t"
        "beq 4f\n\t"
        "b 31f\n\t"
    "4:\n\t"
        "ldr r0, [r4, #0x48]\n\t"
        "mov r1, #7\n\t"
        "and r1, r0\n\t"
        "mov r2, #4\n\t"
        "and r1, r2\n\t"
        "add r2, r0, #0\n\t"
        "add r5, r4, #0\n\t"
        "add r5, #0x2d\n\t"
        "cmp r1, #0\n\t"
        "bne 5f\n\t"
        "b 24f\n\t"
    "5:\n\t"
        "ldrb r0, [r5]\n\t"
        "cmp r0, #8\n\t"
        "beq 6f\n\t"
        "b 24f\n\t"
    "6:\n\t"
        "mov r6, #0\n\t"
        "mov r1, #0x29\n\t"
        "add r1, r1, r4\n\t"
        "mov r8, r1\n\t"
        "mov r7, #7\n\t"
    "7:\n\t"
        "ldr r1, [r4, #0x48]\n\t"
        "add r0, r1, #0\n\t"
        "and r0, r7\n\t"
        "add r2, r0, #1\n\t"
        "mov r0, #3\n\t"
        "and r2, r0\n\t"
        "add r3, r2, #0\n\t"
        "mov r0, #0xf8\n\t"
        "and r1, r0\n\t"
        "orr r1, r2\n\t"
        "str r1, [r4, #0x48]\n\t"
        "cmp r2, #1\n\t"
        "beq 16f\n\t"
        "cmp r2, #1\n\t"
        "bgt 9f\n\t"
        "cmp r2, #0\n\t"
        "beq 10f\n\t"
        "b 20f\n\t"
        ".align 2, 0\n"
    "8: .4byte gUnknown_030012D8\n"
    "9:\n\t"
        "cmp r3, #2\n\t"
        "beq 17f\n\t"
        "cmp r3, #3\n\t"
        "beq 19f\n\t"
        "b 20f\n\t"
    "10:\n\t"
        "strb r7, [r5]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087C0\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087B4\n\t"
        "add r0, r4, #0\n\t"
        "mov r1, #0\n\t"
        "bl sub_800872C\n\t"
        "ldr r0, [r4, #0x48]\n\t"
        "mov r6, #0xc0\n\t"
        "and r0, r6\n\t"
        "cmp r0, #0\n\t"
        "beq 21f\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_8010A50\n\t"
        "lsl r0, r0, #0x18\n\t"
        "lsr r0, r0, #0x18\n\t"
        "cmp r0, #0\n\t"
        "beq 11f\n\t"
        "sub r2, r0, #1\n\t"
        "lsl r2, r2, #0x18\n\t"
        "ldr r1, [r4, #0x48]\n\t"
        "mov r0, #0xc7\n\t"
        "and r1, r0\n\t"
        "lsr r2, r2, #0x15\n\t"
        "orr r1, r2\n\t"
        "str r1, [r4, #0x48]\n\t"
    "11:\n\t"
        "ldr r2, [r4, #0x48]\n\t"
        "mov r0, #0x38\n\t"
        "and r0, r2\n\t"
        "cmp r0, #0\n\t"
        "bne 21f\n\t"
        "mov r1, #0xc7\n\t"
        "and r1, r2\n\t"
        "mov r0, #0x10\n\t"
        "orr r1, r0\n\t"
        "str r1, [r4, #0x48]\n\t"
        "add r0, r1, #0\n\t"
        "and r0, r6\n\t"
        "lsr r0, r0, #6\n\t"
        "cmp r0, #2\n\t"
        "beq 14f\n\t"
        "cmp r0, #2\n\t"
        "bgt 12f\n\t"
        "cmp r0, #1\n\t"
        "beq 13f\n\t"
        "b 21f\n\t"
    "12:\n\t"
        "cmp r0, #3\n\t"
        "beq 15f\n\t"
        "b 21f\n\t"
    "13:\n\t"
        "mov r0, #0x3f\n\t"
        "and r1, r0\n\t"
        "mov r0, #0x80\n\t"
        "orr r1, r0\n\t"
        "str r1, [r4, #0x48]\n\t"
        "b 21f\n\t"
    "14:\n\t"
        "mov r0, #0x3f\n\t"
        "and r1, r0\n\t"
        "orr r1, r6\n\t"
        "str r1, [r4, #0x48]\n\t"
        "b 21f\n\t"
    "15:\n\t"
        "mov r0, #0x20\n\t"
        "strb r0, [r5]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087C0\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087B4\n\t"
        "add r0, r4, #0\n\t"
        "mov r1, #0\n\t"
        "bl sub_800872C\n\t"
        "add r0, r4, #0\n\t"
        "add r0, #0x4e\n\t"
        "strb r7, [r0]\n\t"
        "b 21f\n\t"
    "16:\n\t"
        "add r1, r4, #0\n\t"
        "add r1, #0x50\n\t"
        "mov r0, #2\n\t"
        "ldrb r1, [r1]\n\t"
        "and r0, r1\n\t"
        "cmp r0, #0\n\t"
        "beq 20f\n\t"
        "mov r0, #9\n\t"
        "b 18f\n\t"
    "17:\n\t"
        "add r1, r4, #0\n\t"
        "add r1, #0x50\n\t"
        "mov r0, #1\n\t"
        "ldrb r1, [r1]\n\t"
        "and r0, r1\n\t"
        "cmp r0, #0\n\t"
        "beq 20f\n\t"
        "mov r0, #0xb\n\t"
    "18:\n\t"
        "strb r0, [r5]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087C0\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087B4\n\t"
        "add r0, r4, #0\n\t"
        "mov r1, #0\n\t"
        "bl sub_800872C\n\t"
        "b 21f\n\t"
    "19:\n\t"
        "add r1, r4, #0\n\t"
        "add r1, #0x50\n\t"
        "mov r0, #4\n\t"
        "ldrb r1, [r1]\n\t"
        "and r0, r1\n\t"
        "cmp r0, #0\n\t"
        "beq 20f\n\t"
        "mov r0, #0xd\n\t"
        "strb r0, [r5]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087C0\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087B4\n\t"
        "add r0, r4, #0\n\t"
        "mov r1, #0\n\t"
        "bl sub_800872C\n\t"
        "mov r6, #1\n\t"
    "20:\n\t"
        "cmp r6, #0\n\t"
        "bne 21f\n\t"
        "b 7b\n\t"
    "21:\n\t"
        "ldr r0, [r4, #0x20]\n\t"
        "ldr r1, [r0]\n\t"
        "ldrb r2, [r5]\n\t"
        "lsl r0, r2, #3\n\t"
        "sub r0, r0, r2\n\t"
        "lsl r0, r0, #2\n\t"
        "add r1, r1, r0\n\t"
        "ldr r0, 22f\n\t"
        "ldr r0, [r0]\n\t"
        "ldrb r1, [r1, #0x14]\n\t"
        "bl sub_8006DF8\n\t"
        "lsl r0, r0, #0x18\n\t"
        "lsr r0, r0, #0x18\n\t"
        "mov r1, #0xf\n\t"
        "and r0, r1\n\t"
        "mov r1, #0x10\n\t"
        "neg r1, r1\n\t"
        "mov r3, r8\n\t"
        "ldrb r3, [r3]\n\t"
        "and r1, r3\n\t"
        "orr r1, r0\n\t"
        "mov r0, r8\n\t"
        "strb r1, [r0]\n\t"
        "ldr r0, [r4, #0x48]\n\t"
        "mov r1, #0xc0\n\t"
        "and r0, r1\n\t"
        "lsr r0, r0, #6\n\t"
        "ldr r1, 23f\n\t"
        "add r0, r0, r1\n\t"
        "ldrb r0, [r0]\n\t"
        "mov r1, sb\n\t"
        "strb r0, [r1]\n\t"
        "b 31f\n\t"
        ".align 2, 0\n"
    "22: .4byte gUnknown_030012B8\n"
    "23: .4byte gStaticData_0816BB94\n"
    "24:\n\t"
        "mov r1, #7\n\t"
        "and r1, r2\n\t"
        "mov r0, #4\n\t"
        "orr r1, r0\n\t"
        "mov r0, #0xf8\n\t"
        "and r0, r2\n\t"
        "orr r1, r0\n\t"
        "str r1, [r4, #0x48]\n\t"
        "mov r0, #1\n\t"
        "mov r2, sb\n\t"
        "strb r0, [r2]\n\t"
        "ldrb r0, [r5]\n\t"
        "cmp r0, #0xc\n\t"
        "beq 27f\n\t"
        "cmp r0, #0xa\n\t"
        "bne 25f\n\t"
        "mov r0, #8\n\t"
        "b 28f\n\t"
    "25:\n\t"
        "ldr r0, [r4, #0x48]\n\t"
        "mov r1, #0xc0\n\t"
        "and r0, r1\n\t"
        "lsr r0, r0, #6\n\t"
        "cmp r0, #2\n\t"
        "beq 27f\n\t"
        "cmp r0, #2\n\t"
        "ble 26f\n\t"
        "cmp r0, #3\n\t"
        "beq 29f\n\t"
        "b 30f\n\t"
    "26:\n\t"
        "cmp r0, #0\n\t"
        "blt 30f\n\t"
        "mov r0, #0xc\n\t"
        "b 28f\n\t"
    "27:\n\t"
        "mov r0, #0xa\n\t"
    "28:\n\t"
        "strb r0, [r5]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087C0\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087B4\n\t"
        "add r0, r4, #0\n\t"
        "mov r1, #0\n\t"
        "bl sub_800872C\n\t"
        "b 30f\n\t"
    "29:\n\t"
        "mov r0, #8\n\t"
        "strb r0, [r5]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087C0\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_80087B4\n\t"
        "add r0, r4, #0\n\t"
        "mov r1, #0\n\t"
        "bl sub_800872C\n\t"
    "30:\n\t"
        "ldr r0, [r4, #0x20]\n\t"
        "ldr r1, [r0]\n\t"
        "ldrb r3, [r5]\n\t"
        "lsl r0, r3, #3\n\t"
        "sub r0, r0, r3\n\t"
        "lsl r0, r0, #2\n\t"
        "add r1, r1, r0\n\t"
        "ldr r0, 32f\n\t"
        "ldr r0, [r0]\n\t"
        "ldrb r1, [r1, #0x14]\n\t"
        "bl sub_8006DF8\n\t"
        "lsl r0, r0, #0x18\n\t"
        "lsr r0, r0, #0x18\n\t"
        "add r2, r4, #0\n\t"
        "add r2, #0x29\n\t"
        "mov r1, #0xf\n\t"
        "and r0, r1\n\t"
        "mov r1, #0x10\n\t"
        "neg r1, r1\n\t"
        "ldrb r3, [r2]\n\t"
        "and r1, r3\n\t"
        "orr r1, r0\n\t"
        "strb r1, [r2]\n\t"
        "ldr r0, [r4, #0x48]\n\t"
        "mov r1, #0xc0\n\t"
        "and r0, r1\n\t"
        "cmp r0, #0\n\t"
        "beq 31f\n\t"
        "ldr r0, 33f\n\t"
        "ldr r0, [r0]\n\t"
        "mov r2, #0x80\n\t"
        "lsl r2, r2, #1\n\t"
        "mov r1, #0x10\n\t"
        "bl PlaySfx\n\t"
    "31:\n\t"
        "pop {r3, r4}\n\t"
        "mov r8, r3\n\t"
        "mov sb, r4\n\t"
        "pop {r4, r5, r6, r7}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
        ".align 2, 0\n"
    "32: .4byte gUnknown_030012B8\n"
    "33: .4byte gUnknown_030012BC\n"
    );
}
