#include "core.h"

/* GitHub issue #19: continuation of actor_part86.c's chunk
 * (0x080159F8-0x08015FD0). `actor_part86.c` holds the first two of
 * this chunk's three jump-table dispatchers (`sub_80159F8`/
 * `sub_8015C6C`, also NAKED-parked); this one is split into its own
 * file/unit purely to keep each `report_units.py` unit's real ROM
 * range self-contained - see tools/report_units.py's convention of
 * `base_object = None` for NAKED transcriptions and
 * docs/matching/issue-19-0x08015840-actor.md. */

extern void sub_8025BAC(void);
extern void sub_80172D0(void);
extern void sub_8015FDC(void);

/* Dispatches on `self+8` (a "kind" tag, 2/3/else) to pick three tuning
 * constants - a Q8 "mag" magnitude (always 0x12C, redundantly
 * recomputed in each of the three branches, matching the ROM exactly)
 * and two duration-ish values ("valB"/"valA", the 0x14/0x1e-0x20/0xf
 * and 0x1e/0x20/5 pairs). Rolls the D-pad-remap kind
 * (`sub_8000760`) that becomes the 9-case dispatch below. On a 1-in-128
 * frame-counter tick, with a coin-flip (`sub_8000E1C(2)`), spawns a
 * `kind 4` object via `sub_8025BAC` at the part's de-Q8'd position
 * (y offset by -0x14, mirrored by `part+0x28` bit 4) and clears its
 * `+0xc` bit 0/bit 2 (`& ~5`) if the spawn succeeded. The final 9-case
 * jump table feeds `sub_80172D0` (still raw) and `sub_8015FDC` (matched,
 * `actor_part57b.c`) with a `(valB*3)/4` or `(mag*3)/4` timing value
 * (sign selected by which case, per-axis) matching the Q14
 * rounding-division idiom already documented for `sub_8015FDC` itself.
 *
 * Written as NAKED asm, not plain C: every field access, RNG/SFX call,
 * and the spawn-clear sequence reconstruct cleanly and matched
 * byte-for-byte on the first attempt (see the sibling `sub_80159F8`/
 * `sub_8015C6C` in actor_part86.c for the identical `part+0x28` bit-4
 * idiom and shared-tail `goto` technique that worked there) - but the
 * 9-case dispatch's `(valB*3)/4`/`(mag*3)/4` computations resist it:
 * ROM always routes the pre-shift product through an extra scratch
 * register copy (e.g. `adds r5,r0,r5` / `adds r1,r5,#0` / `asrs r6,r1,#2`
 * - three steps, the middle one a pure register-to-register copy) that
 * gcc 2.9 collapses to two steps (`lsls r1,r5,#1` / `adds r1,r1,r5` /
 * `asrs r6,r1,#2`, no separate copy) no matter how the intermediate is
 * named, register-pinned, or reassigned in the C source - confirmed
 * with an isolated `register s32 t asm("r1")` copy-forcing attempt that
 * still got folded away. Separately, `mag`'s divide-by-4 (`r8`, a
 * register-pinned high register) always emitted the ROM's
 * `cmp;bge;add #3` round-toward-zero adjustment for a plain `/4` even
 * on the provably-non-negative branches where ROM has none - `>> 2`
 * fixed that specific gap (matching ROM's plain `asr`), but not the
 * scratch-copy gap above. Transcribed instruction-for-instruction from
 * the ROM disassembly instead, the same escape hatch used for
 * `sub_80145E4` (`actor_part18b.c`) and `sub_8001CB8`/`sub_8001DB4`
 * (`src/system/link_cable.c`). */
NAKED void sub_8015DF8(void *selfArg)
{
    asm(
        "push {r4, r5, r6, r7, lr}\n\t"
        "mov r7, r8\n\t"
        "push {r7}\n\t"
        "sub sp, #8\n\t"
        "add r6, r0, #0\n\t"
        "ldr r0, [r6, #8]\n\t"
        "cmp r0, #2\n\t"
        "bne 1f\n\t"
        "mov r0, #0x96\n\t"
        "lsl r0, r0, #1\n\t"
        "mov r8, r0\n\t"
        "mov r5, #0x14\n\t"
        "mov r4, #0x1e\n\t"
        "b 2f\n\t"
        "1:\n\t"
        "cmp r0, #3\n\t"
        "bne 3f\n\t"
        "mov r1, #0x96\n\t"
        "lsl r1, r1, #1\n\t"
        "mov r8, r1\n\t"
        "mov r5, #0x14\n\t"
        "mov r4, #0x20\n\t"
        "b 2f\n\t"
        "3:\n\t"
        "mov r2, #0x96\n\t"
        "lsl r2, r2, #1\n\t"
        "mov r8, r2\n\t"
        "mov r5, #0xf\n\t"
        "mov r4, #5\n\t"
        "2:\n\t"
        "ldr r0, 30f\n\t"
        "ldr r0, [r0]\n\t"
        "bl sub_8000760\n\t"
        "lsl r0, r0, #0x18\n\t"
        "lsr r7, r0, #0x18\n\t"
        "ldr r0, 31f\n\t"
        "ldr r0, [r0]\n\t"
        "mov r1, #0x7f\n\t"
        "and r0, r1\n\t"
        "cmp r0, #0\n\t"
        "bne 4f\n\t"
        "mov r0, #2\n\t"
        "bl sub_8000E1C\n\t"
        "lsl r0, r0, #0x10\n\t"
        "cmp r0, #0\n\t"
        "bne 4f\n\t"
        "ldr r0, [r6, #0x10]\n\t"
        "ldr r3, [r0]\n\t"
        "asr r3, r3, #8\n\t"
        "ldr r2, [r0, #4]\n\t"
        "asr r2, r2, #8\n\t"
        "sub r2, #0x14\n\t"
        "add r0, #0x28\n\t"
        "ldrb r0, [r0]\n\t"
        "lsl r1, r0, #0x1b\n\t"
        "lsr r1, r1, #0x1f\n\t"
        "ldr r0, 32f\n\t"
        "ldr r0, [r0]\n\t"
        "str r2, [sp]\n\t"
        "str r1, [sp, #4]\n\t"
        "mov r1, #0x28\n\t"
        "mov r2, #4\n\t"
        "bl sub_8025BAC\n\t"
        "add r1, r0, #0\n\t"
        "cmp r1, #0\n\t"
        "beq 4f\n\t"
        "mov r0, #5\n\t"
        "neg r0, r0\n\t"
        "ldrb r2, [r1, #0xc]\n\t"
        "and r0, r2\n\t"
        "strb r0, [r1, #0xc]\n\t"
        "4:\n\t"
        "cmp r7, #8\n\t"
        "bls 5f\n\t"
        "b 20f\n\t"
        "5:\n\t"
        "lsl r0, r7, #2\n\t"
        "ldr r1, 33f\n\t"
        "add r0, r0, r1\n\t"
        "ldr r0, [r0]\n\t"
        "mov pc, r0\n\t"
        ".align 2, 0\n"
        "30: .4byte gUnknown_03001304\n"
        "31: .4byte gUnknown_0300082C\n"
        "32: .4byte gUnknown_030012E4\n"
        "33: .4byte 34f\n"
        ".align 2, 0\n"
        "34:\n\t"
        ".4byte 12f\n\t"
        ".4byte 17f\n\t"
        ".4byte 19f\n\t"
        ".4byte 14f\n\t"
        ".4byte 15f\n\t"
        ".4byte 6f\n\t"
        ".4byte 7f\n\t"
        ".4byte 10f\n\t"
        ".4byte 9f\n\t"
        "6:\n\t"
        "lsl r0, r5, #1\n\t"
        "add r5, r0, r5\n\t"
        "add r1, r5, #0\n\t"
        "asr r6, r1, #2\n\t"
        "mov r0, r8\n\t"
        "neg r1, r0\n\t"
        "lsl r0, r1, #1\n\t"
        "add r4, r0, r1\n\t"
        "add r2, r4, #0\n\t"
        "cmp r4, #0\n\t"
        "bge 21f\n\t"
        "add r2, r4, #3\n\t"
        "21:\n\t"
        "asr r5, r2, #2\n\t"
        "mov r0, #0\n\t"
        "add r1, r6, #0\n\t"
        "add r2, r5, #0\n\t"
        "bl sub_80172D0\n\t"
        "b 8f\n\t"
        "7:\n\t"
        "lsl r0, r5, #1\n\t"
        "add r4, r0, r5\n\t"
        "add r1, r4, #0\n\t"
        "asr r5, r1, #2\n\t"
        "mov r1, r8\n\t"
        "lsl r0, r1, #1\n\t"
        "add r0, r8\n\t"
        "asr r2, r0, #2\n\t"
        "mov r0, #0\n\t"
        "add r1, r5, #0\n\t"
        "bl sub_80172D0\n\t"
        "mov r2, r8\n\t"
        "neg r1, r2\n\t"
        "lsl r0, r1, #1\n\t"
        "add r0, r0, r1\n\t"
        "cmp r0, #0\n\t"
        "bge 22f\n\t"
        "add r0, #3\n\t"
        "22:\n\t"
        "asr r2, r0, #2\n\t"
        "b 11f\n\t"
        "9:\n\t"
        "lsl r0, r5, #1\n\t"
        "add r5, r0, r5\n\t"
        "add r1, r5, #0\n\t"
        "asr r6, r1, #2\n\t"
        "mov r1, r8\n\t"
        "lsl r0, r1, #1\n\t"
        "add r4, r0, r1\n\t"
        "add r2, r4, #0\n\t"
        "asr r5, r2, #2\n\t"
        "mov r0, #0\n\t"
        "add r1, r6, #0\n\t"
        "add r2, r5, #0\n\t"
        "bl sub_80172D0\n\t"
        "8:\n\t"
        "mov r0, #0\n\t"
        "add r1, r6, #0\n\t"
        "add r2, r5, #0\n\t"
        "bl sub_8015FDC\n\t"
        "b 20f\n\t"
        "10:\n\t"
        "lsl r0, r5, #1\n\t"
        "add r4, r0, r5\n\t"
        "add r1, r4, #0\n\t"
        "asr r5, r1, #2\n\t"
        "mov r2, r8\n\t"
        "neg r1, r2\n\t"
        "lsl r0, r1, #1\n\t"
        "add r0, r0, r1\n\t"
        "cmp r0, #0\n\t"
        "bge 23f\n\t"
        "add r0, #3\n\t"
        "23:\n\t"
        "asr r2, r0, #2\n\t"
        "mov r0, #0\n\t"
        "add r1, r5, #0\n\t"
        "bl sub_80172D0\n\t"
        "mov r1, r8\n\t"
        "lsl r0, r1, #1\n\t"
        "add r0, r8\n\t"
        "asr r2, r0, #2\n\t"
        "b 11f\n\t"
        "12:\n\t"
        "mov r0, #0\n\t"
        "add r1, r4, #0\n\t"
        "mov r2, #0\n\t"
        "bl sub_8015FDC\n\t"
        "mov r0, #0\n\t"
        "add r1, r4, #0\n\t"
        "mov r2, #0\n\t"
        "bl sub_80172D0\n\t"
        "b 20f\n\t"
        "14:\n\t"
        "mov r0, r8\n\t"
        "neg r2, r0\n\t"
        "mov r0, #0\n\t"
        "add r1, r5, #0\n\t"
        "b 16f\n\t"
        "15:\n\t"
        "mov r0, #0\n\t"
        "add r1, r5, #0\n\t"
        "mov r2, r8\n\t"
        "16:\n\t"
        "bl sub_80172D0\n\t"
        "mov r0, #0\n\t"
        "add r1, r4, #0\n\t"
        "mov r2, #0\n\t"
        "bl sub_8015FDC\n\t"
        "b 20f\n\t"
        "17:\n\t"
        "mov r0, #0\n\t"
        "add r1, r4, #0\n\t"
        "mov r2, #0\n\t"
        "bl sub_80172D0\n\t"
        "mov r1, r8\n\t"
        "neg r2, r1\n\t"
        "11:\n\t"
        "mov r0, #0\n\t"
        "add r1, r5, #0\n\t"
        "bl sub_8015FDC\n\t"
        "b 20f\n\t"
        "19:\n\t"
        "mov r0, #0\n\t"
        "add r1, r4, #0\n\t"
        "mov r2, #0\n\t"
        "bl sub_80172D0\n\t"
        "mov r0, #0\n\t"
        "add r1, r5, #0\n\t"
        "mov r2, r8\n\t"
        "bl sub_8015FDC\n\t"
        "20:\n\t"
        "add sp, #8\n\t"
        "pop {r3}\n\t"
        "mov r8, r3\n\t"
        "pop {r4, r5, r6, r7}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
    );
}
asm(".align 2, 0");
