#include "core.h"

/* NAKED - sets up the currently-selected category's runtime state:
 * `gUnknown_03001418` = `&gStaticData_081756C4[type]` (the category's
 * shared vtable, `type` being the first argument), `gUnknown_03001414`
 * = the 4th argument (a variant-selector byte), `gUnknown_03001400` =
 * the 2nd argument (the category's `sub_effect_table` array pointer,
 * see `struct sub_effect_record` in actor_part94.c/include/actor_anim.h),
 * resets `gUnknown_03001404`/`gUnknown_0300141C`/`gUnknown_03001420` to
 * 0, draws the vtable's slot-0 function pointer via `sub_803AD84`
 * (arg2/arg3 as x/y - the 5th argument, stack-passed, per the ROM's own
 * `ldr r6, [sp, #0x20]`), then runs a two-pass scan over the
 * `gUnknown_03001400[]` array comparing each entry's threshold field
 * (see `struct sub_effect_record.field_00`) plus `gUnknown_03001420`'s
 * offset against `gUnknown_03001418->fn[8]` (the vtable's own +0x20
 * slot, reinterpreted as a threshold): the first pass finds the last
 * entry whose adjusted threshold the vtable slot still exceeds
 * (`gUnknown_03001404`, an index into the table), the second draws
 * every entry from index 0 up to that point via `sub_803AD84`, mem_
 * alloc's a 0xc8-byte scratch buffer (`gUnknown_03001408`), and fires
 * one more `sub_803AD7C` visibility check if the vtable's own +8 slot
 * is set, before resetting `gUnknown_03001424`'s call counter to 0.
 *
 * Fully understood; a real-C attempt reproduces every instruction but
 * needed one more live register (`r9`) than the ROM's own `sb`/`r8`
 * pair to keep the vtable pointer, the sub_effect_table pointer, and
 * the loop index simultaneously live across the scan's inner branches
 * - the same "more live values than the ROM's own build needed"
 * register-pressure gap this project's docs/matching.md catalogs
 * throughout. NAKED per docs/workflow.md's escape hatch; every
 * instruction below is transcribed directly from the ROM disassembly
 * (`asm/code_3_2_20_8b7c_9ed0.s`, since cut from
 * `asm/code_3_2_20_8b7c.s`) and verified byte-for-byte against
 * `baserom.gba`. */
NAKED void SelectActorCategory(s32 type, void *subEffectTable, s32 x, s32 variantByte, s32 y)
{
    asm(
        "push {r4, r5, r6, r7, lr}\n\t"
        "mov r7, sb\n\t"
        "mov r6, r8\n\t"
        "push {r6, r7}\n\t"
        "ldr r6, [sp, #0x20]\n\t"
        "ldr r4, 1f\n\t"
        "mov sb, r4\n\t"
        "mov r4, #0x34\n\t"
        "mul r4, r0, r4\n\t"
        "ldr r0, 2f\n\t"
        "add r4, r4, r0\n\t"
        "mov r0, sb\n\t"
        "str r4, [r0]\n\t"
        "ldr r0, 3f\n\t"
        "strb r3, [r0]\n\t"
        "ldr r5, 4f\n\t"
        "str r1, [r5]\n\t"
        "ldr r7, 5f\n\t"
        "mov r1, #0\n\t"
        "str r1, [r7]\n\t"
        "ldr r0, 6f\n\t"
        "strb r1, [r0]\n\t"
        "ldr r0, 7f\n\t"
        "str r1, [r0]\n\t"
        "ldr r3, [r4]\n\t"
        "add r0, r2, #0\n\t"
        "add r1, r6, #0\n\t"
        "bl sub_803AD84\n\t"
        "bl sub_8029B2C\n\t"
        "mov r8, r0\n\t"
        "ldr r5, [r5]\n\t"
        "ldr r1, [r7]\n\t"
        "ldr r0, [r5, #4]\n\t"
        "cmp r1, r0\n\t"
        "bge 8f\n\t"
        "lsl r0, r1, #2\n\t"
        "add r0, r0, r1\n\t"
        "lsl r0, r0, #2\n\t"
        "add r2, r5, #0\n\t"
        "add r2, #0x14\n\t"
        "add r0, r2, r0\n\t"
        "mov r3, sb\n\t"
        "ldr r1, [r3]\n\t"
        "ldr r1, [r1, #0x20]\n\t"
        "add r1, r8\n\t"
        "ldr r0, [r0]\n\t"
        "cmp r0, r1\n\t"
        "bge 8f\n\t"
        "add r3, r7, #0\n\t"
        "mov r4, sb\n\t"
        "9:\n\t"
        "ldr r0, [r3]\n\t"
        "add r1, r0, #1\n\t"
        "str r1, [r3]\n\t"
        "ldr r0, [r5, #4]\n\t"
        "cmp r1, r0\n\t"
        "bge 8f\n\t"
        "lsl r0, r1, #2\n\t"
        "add r0, r0, r1\n\t"
        "lsl r0, r0, #2\n\t"
        "add r0, r2, r0\n\t"
        "ldr r1, [r4]\n\t"
        "ldr r1, [r1, #0x20]\n\t"
        "add r1, r8\n\t"
        "ldr r0, [r0]\n\t"
        "cmp r0, r1\n\t"
        "blt 9b\n\t"
        "8:\n\t"
        "ldr r4, 10f\n\t"
        "mov r1, #0x80\n\t"
        "lsl r1, r1, #0x18\n\t"
        "mov r0, #0xc8\n\t"
        "bl mem_alloc\n\t"
        "str r0, [r4]\n\t"
        "ldr r4, 1f\n\t"
        "ldr r0, [r4]\n\t"
        "ldr r1, [r0, #8]\n\t"
        "cmp r1, #0\n\t"
        "beq 11f\n\t"
        "ldr r0, [sp, #0x1c]\n\t"
        "bl sub_803AD7C\n\t"
        "11:\n\t"
        "ldr r7, 5f\n\t"
        "ldr r3, 4f\n\t"
        "ldr r1, [r3]\n\t"
        "ldr r2, [r7]\n\t"
        "ldr r0, [r1, #4]\n\t"
        "cmp r2, r0\n\t"
        "bge 12f\n\t"
        "lsl r0, r2, #2\n\t"
        "add r0, r0, r2\n\t"
        "lsl r0, r0, #2\n\t"
        "add r1, #0x14\n\t"
        "add r1, r1, r0\n\t"
        "ldr r0, [r4]\n\t"
        "ldr r0, [r0, #0x1c]\n\t"
        "add r0, r8\n\t"
        "ldr r1, [r1]\n\t"
        "cmp r1, r0\n\t"
        "bgt 12f\n\t"
        "add r6, r4, #0\n\t"
        "add r5, r3, #0\n\t"
        "add r4, r7, #0\n\t"
        "13:\n\t"
        "ldr r2, [r6]\n\t"
        "ldr r0, [r4]\n\t"
        "lsl r1, r0, #2\n\t"
        "add r1, r1, r0\n\t"
        "lsl r1, r1, #2\n\t"
        "add r1, #8\n\t"
        "ldr r0, [r5]\n\t"
        "add r0, r0, r1\n\t"
        "ldr r1, 3f\n\t"
        "ldrb r1, [r1]\n\t"
        "ldr r3, [r2, #4]\n\t"
        "mov r2, #0\n\t"
        "bl sub_803AD84\n\t"
        "ldr r0, [r4]\n\t"
        "add r2, r0, #1\n\t"
        "str r2, [r4]\n\t"
        "ldr r1, [r5]\n\t"
        "ldr r0, [r1, #4]\n\t"
        "cmp r2, r0\n\t"
        "bge 12f\n\t"
        "lsl r0, r2, #2\n\t"
        "add r0, r0, r2\n\t"
        "lsl r0, r0, #2\n\t"
        "add r1, #0x14\n\t"
        "add r1, r1, r0\n\t"
        "ldr r0, [r6]\n\t"
        "ldr r0, [r0, #0x1c]\n\t"
        "add r0, r8\n\t"
        "ldr r1, [r1]\n\t"
        "cmp r1, r0\n\t"
        "ble 13b\n\t"
        "12:\n\t"
        "ldr r1, 14f\n\t"
        "mov r0, #0\n\t"
        "str r0, [r1]\n\t"
        "pop {r3, r4}\n\t"
        "mov r8, r3\n\t"
        "mov sb, r4\n\t"
        "pop {r4, r5, r6, r7}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
        ".align 2, 0\n"
        "1: .4byte gUnknown_03001418\n"
        "2: .4byte gStaticData_081756C4\n"
        "3: .4byte gUnknown_03001414\n"
        "4: .4byte gUnknown_03001400\n"
        "5: .4byte gUnknown_03001404\n"
        "6: .4byte gUnknown_0300141C\n"
        "7: .4byte gUnknown_03001420\n"
        "10: .4byte gUnknown_03001408\n"
        "14: .4byte gUnknown_03001424\n"
    );
}
