#include "core.h"
#include "actor.h"

extern void sub_8009008(void *manager, void *item);
extern void sub_803A94C(void *src, void *dst, s32 control);
extern s32 sub_803AD80(void *arg0, void *arg1, void *fn);
extern void *sub_803AD7C(void *arg0, void *fn);
extern void *gUnknown_03001308;

/* A per-frame spatial-hash-grid maintenance pass over `manager`'s
 * `struct pool_manager` (`actor_part12.c`), scoped to the 3-bucket
 * window `[baseIdx, baseIdx+2]` around `baseIdx` (the same
 * `max(gUnknown_03001308`'s sub-object's own `x >> 8`, `0)` bucket
 * index `sub_800944C`/`sub_8009528` compute), plus the special "large
 * object" bucket 255 in a second pass - not a full 0-255 sweep like
 * those two sibling functions.
 *
 * For each node's object (`part`) in the windowed buckets:
 *  - If `part->flags` bit 4 ("large object") is set and this node has
 *    no bucket-255 secondary link yet (`node+0xc == 0`), lazily creates
 *    one - an inline copy of `sub_8009150`'s own body (pop a node off
 *    the free list, wrap `part` in it, splice it into bucket 255's
 *    head/tail list, cross-link the two nodes via `+0xc`).
 *  - Otherwise, if `part->flags` bit 0 is set (a "pending removal"
 *    flag), removes `part` from `manager`'s active-object array the
 *    same way `sub_8009A30` does (linear search, `sub_8009008` to
 *    unlink the grid node(s), `sub_803A94C`-based compaction), then
 *    fires a `part->table+0x50/0x54`-driven trampoline via
 *    `sub_803AD80` with constant arg `3` - the exact same "destroy"
 *    trampoline `sub_8009914`'s teardown loop fires.
 *  - Otherwise, tests `part` against a computed box (the tracked
 *    sub-object's position, offset by fixed constants `-0x6400`/
 *    `-0x3C00` in Q8 and sized `0x1B8`x`0x118` in Q8 - an "extended"
 *    region wider than the plain 240x160 screen box `sub_800944C`/
 *    `sub_8009528` use, meaning/purpose not yet confirmed) via a
 *    `part->table+0x40/0x44`-driven trampoline; on a hit, fires a
 *    `part->table+0x18/0x1c`-driven trampoline and marks the node
 *    (`node+0x10 = 1`) so the bucket-255 second pass knows to skip a
 *    node already handled via its primary bucket (clearing the mark
 *    instead), mirroring `sub_800944C`'s own primary/secondary-pass
 *    marking convention (there via `node+0x11`).
 *
 * Written as NAKED asm, not plain C: the semantics above are fully
 * confirmed (every branch, field offset, and call argument traced
 * against the ROM disassembly), but this function juggles more live
 * cross-branch state across three high registers (`r8`/`sb`/`sl`, each
 * reused for a different purpose in each of the three inner-loop
 * branches) than any C-level reconstruction attempted here reproduced
 * exactly - the same category of many-register allocation gap already
 * documented for `sub_8008F20`/`sub_8009914` in `actor_part11.c`.
 * Parked as a direct transcription of the ROM's own confirmed-correct
 * instructions instead. */
NAKED void sub_80091D4(void *manager)
{
    asm(
        "push {r4, r5, r6, r7, lr}\n\t"
        "mov r7, sl\n\t"
        "mov r6, sb\n\t"
        "mov r5, r8\n\t"
        "push {r5, r6, r7}\n\t"
        "sub sp, #0x1c\n\t"
        "add r7, r0, #0\n\t"
        "mov r0, #0xdc\n\t"
        "lsl r0, r0, #9\n\t"
        "mov r1, #0x8c\n\t"
        "lsl r1, r1, #9\n\t"
        "str r0, [sp, #8]\n\t"
        "str r1, [sp, #0xc]\n\t"
        "ldr r0, 6f\n\t"
        "ldr r0, [r0]\n\t"
        "ldr r2, [r0, #0x10]\n\t"
        "ldr r1, [r2]\n\t"
        "lsl r1, r1, #8\n\t"
        "ldr r0, 7f\n\t"
        "add r1, r1, r0\n\t"
        "ldr r0, [r2, #4]\n\t"
        "lsl r0, r0, #8\n\t"
        "ldr r3, 8f\n\t"
        "add r0, r0, r3\n\t"
        "str r1, [sp]\n\t"
        "str r0, [sp, #4]\n\t"
        "ldr r2, [r2]\n\t"
        "asr r2, r2, #8\n\t"
        "str r2, [sp, #0x10]\n\t"
        "cmp r2, #0\n\t"
        "bge 1f\n\t"
        "mov r0, #0\n\t"
        "str r0, [sp, #0x10]\n\t"
    "1:\n\t"
        "ldr r1, [sp, #0x10]\n\t"
        "add r1, #2\n\t"
        "add r2, r7, #0\n\t"
        "add r2, #0x10\n\t"
        "str r2, [sp, #0x18]\n\t"
        "ldr r3, 9f\n\t"
        "add r3, r3, r7\n\t"
        "mov sl, r3\n\t"
    "2:\n\t"
        "lsl r0, r1, #2\n\t"
        "ldr r2, [sp, #0x18]\n\t"
        "add r0, r2, r0\n\t"
        "ldr r0, [r0]\n\t"
        "mov r8, r0\n\t"
        "sub r1, #1\n\t"
        "str r1, [sp, #0x14]\n\t"
        "cmp r0, #0\n\t"
        "bne 3f\n\t"
        "b 19f\n\t"
    "3:\n\t"
        "mov r3, r8\n\t"
        "ldr r2, [r3]\n\t"
        "ldrb r0, [r2, #0xc]\n\t"
        "lsr r1, r0, #4\n\t"
        "mov r0, #1\n\t"
        "and r1, r0\n\t"
        "add r5, r2, #0\n\t"
        "cmp r1, #0\n\t"
        "beq 12f\n\t"
        "ldr r4, [r3, #0xc]\n\t"
        "cmp r4, #0\n\t"
        "bne 12f\n\t"
        "ldr r1, 10f\n\t"
        "add r2, r7, r1\n\t"
        "ldr r1, [r2]\n\t"
        "ldr r3, [r1]\n\t"
        "ldr r0, [r1, #4]\n\t"
        "str r0, [r2]\n\t"
        "str r4, [r1, #4]\n\t"
        "str r5, [r3]\n\t"
        "str r4, [r3, #4]\n\t"
        "mov r2, r8\n\t"
        "str r2, [r3, #0xc]\n\t"
        "strb r4, [r3, #0x10]\n\t"
        "strb r4, [r3, #0x11]\n\t"
        "mov r1, sl\n\t"
        "ldr r0, [r1]\n\t"
        "cmp r0, #0\n\t"
        "bne 4f\n\t"
        "str r3, [r1]\n\t"
    "4:\n\t"
        "ldr r2, 11f\n\t"
        "add r1, r7, r2\n\t"
        "ldr r0, [r1]\n\t"
        "cmp r0, #0\n\t"
        "beq 5f\n\t"
        "str r3, [r0, #4]\n\t"
    "5:\n\t"
        "str r3, [r1]\n\t"
        "mov r0, r8\n\t"
        "str r3, [r0, #0xc]\n\t"
        "b 18f\n\t"
        ".align 2, 0\n"
    "6: .4byte gUnknown_03001308\n"
    "7: .4byte 0xFFFF9C00\n"
    "8: .4byte 0xFFFFC400\n"
    "9: .4byte 0x0000040C\n"
    "10: .4byte 0x00000814\n"
    "11: .4byte 0x0000080C\n"
    "12:\n\t"
        "mov r4, #1\n\t"
        "add r0, r4, #0\n\t"
        "ldrb r1, [r5, #0xc]\n\t"
        "and r0, r1\n\t"
        "cmp r0, #0\n\t"
        "beq 17f\n\t"
        "mov sb, r5\n\t"
        "mov ip, r5\n\t"
        "mov r6, #0\n\t"
        "ldr r2, [r7, #4]\n\t"
        "add r4, r2, #0\n\t"
        "cmp r6, r4\n\t"
        "bge 15f\n\t"
        "ldr r0, [r7, #8]\n\t"
        "ldr r1, [r0]\n\t"
        "add r3, r0, #0\n\t"
        "cmp r1, r5\n\t"
        "beq 14f\n\t"
        "add r1, r3, #0\n\t"
    "13:\n\t"
        "add r1, #4\n\t"
        "add r6, #1\n\t"
        "cmp r6, r2\n\t"
        "bge 15f\n\t"
        "ldr r0, [r1]\n\t"
        "cmp r0, ip\n\t"
        "bne 13b\n\t"
    "14:\n\t"
        "cmp r6, r4\n\t"
        "bge 15f\n\t"
        "lsl r4, r6, #2\n\t"
        "add r0, r4, r3\n\t"
        "ldr r1, [r0]\n\t"
        "add r0, r7, #0\n\t"
        "bl sub_8009008\n\t"
        "add r0, r4, #4\n\t"
        "ldr r1, [r7, #8]\n\t"
        "add r0, r1, r0\n\t"
        "add r1, r1, r4\n\t"
        "ldr r2, [r7]\n\t"
        "sub r2, r2, r6\n\t"
        "ldr r3, 16f\n\t"
        "and r2, r3\n\t"
        "mov r3, #0x80\n\t"
        "lsl r3, r3, #0x13\n\t"
        "orr r2, r3\n\t"
        "bl sub_803A94C\n\t"
        "ldr r2, [r7]\n\t"
        "ldr r1, [r7, #8]\n\t"
        "lsl r0, r2, #2\n\t"
        "add r0, r0, r1\n\t"
        "sub r0, #4\n\t"
        "mov r1, #0\n\t"
        "str r1, [r0]\n\t"
        "sub r2, #1\n\t"
        "str r2, [r7]\n\t"
    "15:\n\t"
        "mov r2, sb\n\t"
        "cmp r2, #0\n\t"
        "beq 18f\n\t"
        "ldr r1, [r2, #0x18]\n\t"
        "add r1, #0x50\n\t"
        "mov r3, #0\n\t"
        "ldrsh r0, [r1, r3]\n\t"
        "add r0, sb\n\t"
        "ldr r2, [r1, #4]\n\t"
        "mov r1, #3\n\t"
        "bl sub_803AD80\n\t"
        "b 18f\n\t"
        ".align 2, 0\n"
    "16: .4byte 0x001FFFFF\n"
    "17:\n\t"
        "ldr r1, [r5, #0x18]\n\t"
        "add r1, #0x40\n\t"
        "mov r2, #0\n\t"
        "ldrsh r0, [r1, r2]\n\t"
        "add r0, r5, r0\n\t"
        "ldr r2, [r1, #4]\n\t"
        "mov r1, sp\n\t"
        "bl sub_803AD80\n\t"
        "lsl r0, r0, #0x18\n\t"
        "cmp r0, #0\n\t"
        "beq 18f\n\t"
        "mov r3, r8\n\t"
        "ldr r0, [r3]\n\t"
        "ldr r2, [r0, #0x18]\n\t"
        "mov r3, #0x18\n\t"
        "ldrsh r1, [r2, r3]\n\t"
        "add r0, r0, r1\n\t"
        "ldr r1, [r2, #0x1c]\n\t"
        "bl sub_803AD7C\n\t"
        "mov r0, r8\n\t"
        "strb r4, [r0, #0x10]\n\t"
    "18:\n\t"
        "mov r1, r8\n\t"
        "ldr r1, [r1, #4]\n\t"
        "mov r8, r1\n\t"
        "cmp r1, #0\n\t"
        "beq 19f\n\t"
        "b 3b\n\t"
    "19:\n\t"
        "ldr r1, [sp, #0x14]\n\t"
        "ldr r2, [sp, #0x10]\n\t"
        "cmp r1, r2\n\t"
        "blt 20f\n\t"
        "b 2b\n\t"
    "20:\n\t"
        "mov r3, sl\n\t"
        "ldr r3, [r3]\n\t"
        "mov r8, r3\n\t"
        "cmp r3, #0\n\t"
        "beq 29f\n\t"
    "21:\n\t"
        "mov r0, r8\n\t"
        "ldr r2, [r0]\n\t"
        "mov r3, #1\n\t"
        "ldrb r1, [r2, #0xc]\n\t"
        "and r3, r1\n\t"
        "cmp r3, #0\n\t"
        "beq 26f\n\t"
        "mov sl, r2\n\t"
        "mov sb, r2\n\t"
        "mov r5, #0\n\t"
        "ldr r6, [r7, #4]\n\t"
        "add r4, r6, #0\n\t"
        "cmp r5, r4\n\t"
        "bge 24f\n\t"
        "ldr r0, [r7, #8]\n\t"
        "ldr r1, [r0]\n\t"
        "add r3, r0, #0\n\t"
        "cmp r1, r2\n\t"
        "beq 23f\n\t"
        "add r1, r3, #0\n\t"
    "22:\n\t"
        "add r1, #4\n\t"
        "add r5, #1\n\t"
        "cmp r5, r6\n\t"
        "bge 24f\n\t"
        "ldr r0, [r1]\n\t"
        "cmp r0, sb\n\t"
        "bne 22b\n\t"
    "23:\n\t"
        "cmp r5, r4\n\t"
        "bge 24f\n\t"
        "lsl r4, r5, #2\n\t"
        "add r0, r4, r3\n\t"
        "ldr r1, [r0]\n\t"
        "add r0, r7, #0\n\t"
        "bl sub_8009008\n\t"
        "add r0, r4, #4\n\t"
        "ldr r1, [r7, #8]\n\t"
        "add r0, r1, r0\n\t"
        "add r1, r1, r4\n\t"
        "ldr r2, [r7]\n\t"
        "sub r2, r2, r5\n\t"
        "ldr r3, 25f\n\t"
        "and r2, r3\n\t"
        "mov r3, #0x80\n\t"
        "lsl r3, r3, #0x13\n\t"
        "orr r2, r3\n\t"
        "bl sub_803A94C\n\t"
        "ldr r2, [r7]\n\t"
        "ldr r1, [r7, #8]\n\t"
        "lsl r0, r2, #2\n\t"
        "add r0, r0, r1\n\t"
        "sub r0, #4\n\t"
        "mov r1, #0\n\t"
        "str r1, [r0]\n\t"
        "sub r2, #1\n\t"
        "str r2, [r7]\n\t"
    "24:\n\t"
        "mov r2, sl\n\t"
        "cmp r2, #0\n\t"
        "beq 28f\n\t"
        "ldr r1, [r2, #0x18]\n\t"
        "add r1, #0x50\n\t"
        "mov r3, #0\n\t"
        "ldrsh r0, [r1, r3]\n\t"
        "add r0, sl\n\t"
        "ldr r2, [r1, #4]\n\t"
        "mov r1, #3\n\t"
        "bl sub_803AD80\n\t"
        "b 28f\n\t"
        ".align 2, 0\n"
    "25: .4byte 0x001FFFFF\n"
    "26:\n\t"
        "mov r0, r8\n\t"
        "ldr r1, [r0, #0xc]\n\t"
        "ldrb r0, [r1, #0x10]\n\t"
        "cmp r0, #0\n\t"
        "bne 27f\n\t"
        "ldr r1, [r2, #0x18]\n\t"
        "mov r3, #0x18\n\t"
        "ldrsh r0, [r1, r3]\n\t"
        "add r0, r2, r0\n\t"
        "ldr r1, [r1, #0x1c]\n\t"
        "bl sub_803AD7C\n\t"
        "b 28f\n\t"
    "27:\n\t"
        "strb r3, [r1, #0x10]\n\t"
    "28:\n\t"
        "mov r0, r8\n\t"
        "ldr r0, [r0, #4]\n\t"
        "mov r8, r0\n\t"
        "cmp r0, #0\n\t"
        "bne 21b\n\t"
    "29:\n\t"
        "add sp, #0x1c\n\t"
        "pop {r3, r4, r5}\n\t"
        "mov r8, r3\n\t"
        "mov sb, r4\n\t"
        "mov sl, r5\n\t"
        "pop {r4, r5, r6, r7}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
    );
}
asm(".align 2, 0");
