#include "core.h"

/* This cluster (`sub_802A018`, `sub_802A110`, `sub_802A208`, `sub_802A3AC`,
 * ROM 0x0802A018-0x0802A4D4) sits inside the "actor" chunk starting at
 * `SetupActorVramPool` (0x080291A4). `sub_802A018`/`sub_802A110` are
 * near-identical: translate `gUnknown_03000884` (the player/list-sentinel
 * object)'s and `self`'s own 12-byte `{s16 x,y,z,sizeX,sizeY,sizeZ}` AABB
 * record (`self+0x38`, world-translated by `self+0x1c/0x20/0x24 >>8`) into
 * two stack scratch boxes via `sub_800014C` (a real, byte-verified
 * `memcpy(dst,dst,0xc)` self-copy - see src/graphics/actor_part74.c's own
 * definition/doc comment), then run the same 3-axis (Z,Y,X order) overlap
 * test already established throughout this ROM
 * (sub_802D7B0/sub_802DD9C/sub_802C7A8/sub_8031378 etc - see
 * docs/matching/issue-53-actor-c7a8.md, issue-54-actor-d3a8.md,
 * issue-58-0x08030574-actor.md). `sub_802A3AC` is the same test wrapped in
 * an outer walk of the whole `gUnknown_03000884`-rooted circular list
 * (`self+0x4c`), gated by a `sub_803AD7C` per-node visibility check first
 * (same shape as `sub_802C7A8`).
 *
 * All three hit this project's CONFIRMED CATEGORICAL gcc-2.9 `r7`
 * register-allocation bug: this compiler's unforced allocator never
 * reaches `r7` for the second scratch AABB box's address held live across
 * both `sub_800014C` calls and the whole comparison chain, no matter how
 * the C is phrased (tried: struct-typed locals with sequential field
 * updates matching the ROM's own store order, pointer-cast raw offsets,
 * splitting the translate step into separate statements). A real-C
 * attempt at `sub_802A018` reproduces the exact same logic and
 * instruction *shape* but allocates different low registers throughout
 * and needs the `sub_800014C` self-copy pair, diverging from the ROM's
 * own register choices - see docs/matching/naked-spatial-grid-tail.md
 * and this doc's sibling entries for the general pattern. NAKED per
 * docs/workflow.md's escape hatch; every instruction below is
 * transcribed directly from the ROM disassembly
 * (`asm/code_3_2_20_8b7c.s`) and verified byte-for-byte against
 * `baserom.gba` (dd + objdump -b binary --disassembler-options=force-thumb),
 * not inferred. */

extern void *gUnknown_03000884;
extern u8 gUnknown_030014A0;
extern u8 gUnknown_03001506;

extern void *sub_800014C(void *dst, const void *src, u32 byteCount);

NAKED s32 sub_802A018(void *self)
{
    asm(
        "push {r4, r5, r6, lr}\n\t"
        "sub sp, #0x24\n\t"
        "add r5, r0, #0\n\t"
        "ldr r2, 1f\n\t"
        "ldr r0, 2f\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r0, #0\n\t"
        "bne 3f\n\t"
        "ldr r2, [r2]\n\t"
        "add r1, sp, #0xc\n\t"
        "add r0, r2, #0\n\t"
        "add r0, #0x38\n\t"
        "ldm r0!, {r3, r4, r6}\n\t"
        "stm r1!, {r3, r4, r6}\n\t"
        "ldr r0, [r2, #0x1c]\n\t"
        "asr r0, r0, #8\n\t"
        "ldr r3, [r2, #0x20]\n\t"
        "asr r3, r3, #8\n\t"
        "ldr r1, [r2, #0x24]\n\t"
        "asr r1, r1, #8\n\t"
        "add r4, sp, #0xc\n\t"
        "ldrh r2, [r4]\n\t"
        "add r0, r2, r0\n\t"
        "strh r0, [r4]\n\t"
        "ldrh r0, [r4, #2]\n\t"
        "add r0, r0, r3\n\t"
        "strh r0, [r4, #2]\n\t"
        "ldrh r3, [r4, #4]\n\t"
        "add r1, r3, r1\n\t"
        "strh r1, [r4, #4]\n\t"
        "mov r1, sp\n\t"
        "add r0, r4, #0\n\t"
        "ldm r0!, {r2, r3, r6}\n\t"
        "stm r1!, {r2, r3, r6}\n\t"
        "mov r0, sp\n\t"
        "mov r1, sp\n\t"
        "mov r2, #0xc\n\t"
        "bl sub_800014C\n\t"
        "add r1, sp, #0x18\n\t"
        "add r0, r5, #0\n\t"
        "add r0, #0x38\n\t"
        "ldm r0!, {r2, r3, r6}\n\t"
        "stm r1!, {r2, r3, r6}\n\t"
        "ldr r0, [r5, #0x1c]\n\t"
        "asr r0, r0, #8\n\t"
        "ldr r3, [r5, #0x20]\n\t"
        "asr r3, r3, #8\n\t"
        "ldr r2, [r5, #0x24]\n\t"
        "asr r2, r2, #8\n\t"
        "add r1, sp, #0x18\n\t"
        "ldrh r5, [r1]\n\t"
        "add r0, r5, r0\n\t"
        "strh r0, [r1]\n\t"
        "ldrh r0, [r1, #2]\n\t"
        "add r0, r0, r3\n\t"
        "strh r0, [r1, #2]\n\t"
        "ldrh r6, [r1, #4]\n\t"
        "add r2, r6, r2\n\t"
        "strh r2, [r1, #4]\n\t"
        "add r0, r4, #0\n\t"
        "ldm r1!, {r2, r3, r5}\n\t"
        "stm r0!, {r2, r3, r5}\n\t"
        "add r0, r4, #0\n\t"
        "add r1, r4, #0\n\t"
        "mov r2, #0xc\n\t"
        "bl sub_800014C\n\t"
        "mov r1, sp\n\t"
        "mov r6, #4\n\t"
        "ldrsh r2, [r1, r6]\n\t"
        "mov r0, #4\n\t"
        "ldrsh r3, [r4, r0]\n\t"
        "mov r5, #0xa\n\t"
        "ldrsh r0, [r4, r5]\n\t"
        "add r0, r3, r0\n\t"
        "cmp r2, r0\n\t"
        "bge 3f\n\t"
        "mov r6, #0xa\n\t"
        "ldrsh r0, [r1, r6]\n\t"
        "add r0, r2, r0\n\t"
        "cmp r0, r3\n\t"
        "ble 3f\n\t"
        "mov r0, #2\n\t"
        "ldrsh r2, [r1, r0]\n\t"
        "mov r5, #2\n\t"
        "ldrsh r3, [r4, r5]\n\t"
        "mov r6, #8\n\t"
        "ldrsh r0, [r4, r6]\n\t"
        "add r0, r3, r0\n\t"
        "cmp r2, r0\n\t"
        "bge 3f\n\t"
        "mov r5, #8\n\t"
        "ldrsh r0, [r1, r5]\n\t"
        "add r0, r2, r0\n\t"
        "cmp r0, r3\n\t"
        "ble 3f\n\t"
        "mov r6, #0\n\t"
        "ldrsh r2, [r1, r6]\n\t"
        "mov r0, #0\n\t"
        "ldrsh r3, [r4, r0]\n\t"
        "mov r5, #6\n\t"
        "ldrsh r0, [r4, r5]\n\t"
        "add r0, r3, r0\n\t"
        "cmp r2, r0\n\t"
        "bge 3f\n\t"
        "mov r6, #6\n\t"
        "ldrsh r0, [r1, r6]\n\t"
        "add r0, r2, r0\n\t"
        "cmp r0, r3\n\t"
        "bgt 4f\n\t"
        "3:\n\t"
        "mov r0, #0\n\t"
        "b 5f\n\t"
        ".align 2, 0\n"
        "1: .4byte gUnknown_03000884\n"
        "2: .4byte gUnknown_030014A0\n"
        "4:\n\t"
        "mov r0, #1\n\t"
        "5:\n\t"
        "add sp, #0x24\n\t"
        "pop {r4, r5, r6}\n\t"
        "pop {r1}\n\t"
        "bx r1\n\t"
    );
}

/* Byte-identical shape to `sub_802A018` above, gated on a different guard
 * byte (`gUnknown_03001506` instead of `gUnknown_030014A0`) - see that
 * function's doc comment for the full rationale. */
NAKED s32 sub_802A110(void *self)
{
    asm(
        "push {r4, r5, r6, lr}\n\t"
        "sub sp, #0x24\n\t"
        "add r5, r0, #0\n\t"
        "ldr r2, 1f\n\t"
        "ldr r0, 2f\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r0, #0\n\t"
        "bne 3f\n\t"
        "ldr r2, [r2]\n\t"
        "add r1, sp, #0xc\n\t"
        "add r0, r2, #0\n\t"
        "add r0, #0x38\n\t"
        "ldm r0!, {r3, r4, r6}\n\t"
        "stm r1!, {r3, r4, r6}\n\t"
        "ldr r0, [r2, #0x1c]\n\t"
        "asr r0, r0, #8\n\t"
        "ldr r3, [r2, #0x20]\n\t"
        "asr r3, r3, #8\n\t"
        "ldr r1, [r2, #0x24]\n\t"
        "asr r1, r1, #8\n\t"
        "add r4, sp, #0xc\n\t"
        "ldrh r2, [r4]\n\t"
        "add r0, r2, r0\n\t"
        "strh r0, [r4]\n\t"
        "ldrh r0, [r4, #2]\n\t"
        "add r0, r0, r3\n\t"
        "strh r0, [r4, #2]\n\t"
        "ldrh r3, [r4, #4]\n\t"
        "add r1, r3, r1\n\t"
        "strh r1, [r4, #4]\n\t"
        "mov r1, sp\n\t"
        "add r0, r4, #0\n\t"
        "ldm r0!, {r2, r3, r6}\n\t"
        "stm r1!, {r2, r3, r6}\n\t"
        "mov r0, sp\n\t"
        "mov r1, sp\n\t"
        "mov r2, #0xc\n\t"
        "bl sub_800014C\n\t"
        "add r1, sp, #0x18\n\t"
        "add r0, r5, #0\n\t"
        "add r0, #0x38\n\t"
        "ldm r0!, {r2, r3, r6}\n\t"
        "stm r1!, {r2, r3, r6}\n\t"
        "ldr r0, [r5, #0x1c]\n\t"
        "asr r0, r0, #8\n\t"
        "ldr r3, [r5, #0x20]\n\t"
        "asr r3, r3, #8\n\t"
        "ldr r2, [r5, #0x24]\n\t"
        "asr r2, r2, #8\n\t"
        "add r1, sp, #0x18\n\t"
        "ldrh r5, [r1]\n\t"
        "add r0, r5, r0\n\t"
        "strh r0, [r1]\n\t"
        "ldrh r0, [r1, #2]\n\t"
        "add r0, r0, r3\n\t"
        "strh r0, [r1, #2]\n\t"
        "ldrh r6, [r1, #4]\n\t"
        "add r2, r6, r2\n\t"
        "strh r2, [r1, #4]\n\t"
        "add r0, r4, #0\n\t"
        "ldm r1!, {r2, r3, r5}\n\t"
        "stm r0!, {r2, r3, r5}\n\t"
        "add r0, r4, #0\n\t"
        "add r1, r4, #0\n\t"
        "mov r2, #0xc\n\t"
        "bl sub_800014C\n\t"
        "mov r1, sp\n\t"
        "mov r6, #4\n\t"
        "ldrsh r2, [r1, r6]\n\t"
        "mov r0, #4\n\t"
        "ldrsh r3, [r4, r0]\n\t"
        "mov r5, #0xa\n\t"
        "ldrsh r0, [r4, r5]\n\t"
        "add r0, r3, r0\n\t"
        "cmp r2, r0\n\t"
        "bge 3f\n\t"
        "mov r6, #0xa\n\t"
        "ldrsh r0, [r1, r6]\n\t"
        "add r0, r2, r0\n\t"
        "cmp r0, r3\n\t"
        "ble 3f\n\t"
        "mov r0, #2\n\t"
        "ldrsh r2, [r1, r0]\n\t"
        "mov r5, #2\n\t"
        "ldrsh r3, [r4, r5]\n\t"
        "mov r6, #8\n\t"
        "ldrsh r0, [r4, r6]\n\t"
        "add r0, r3, r0\n\t"
        "cmp r2, r0\n\t"
        "bge 3f\n\t"
        "mov r5, #8\n\t"
        "ldrsh r0, [r1, r5]\n\t"
        "add r0, r2, r0\n\t"
        "cmp r0, r3\n\t"
        "ble 3f\n\t"
        "mov r6, #0\n\t"
        "ldrsh r2, [r1, r6]\n\t"
        "mov r0, #0\n\t"
        "ldrsh r3, [r4, r0]\n\t"
        "mov r5, #6\n\t"
        "ldrsh r0, [r4, r5]\n\t"
        "add r0, r3, r0\n\t"
        "cmp r2, r0\n\t"
        "bge 3f\n\t"
        "mov r6, #6\n\t"
        "ldrsh r0, [r1, r6]\n\t"
        "add r0, r2, r0\n\t"
        "cmp r0, r3\n\t"
        "bgt 4f\n\t"
        "3:\n\t"
        "mov r0, #0\n\t"
        "b 5f\n\t"
        ".align 2, 0\n"
        "1: .4byte gUnknown_03000884\n"
        "2: .4byte gUnknown_03001506\n"
        "4:\n\t"
        "mov r0, #1\n\t"
        "5:\n\t"
        "add sp, #0x24\n\t"
        "pop {r4, r5, r6}\n\t"
        "pop {r1}\n\t"
        "bx r1\n\t"
    );
}

/* `sub_802A208`: fires a "scroll enter/exit" trampoline pair off
 * `gUnknown_03001418->fn[3]`/`fn[0xa]` (the selected category's vtable,
 * `struct category_vtable`), drives a `gUnknown_03001400`-rooted
 * sub-effect-table draw loop (`sub_803AD84`, same record family as
 * `sub_802A504`/`sub_802A51C`/`sub_802A540`/`sub_802A558`/`sub_802A570`),
 * then walks the whole `gUnknown_03000884`-rooted circular actor list
 * twice: once unconditionally (drawing each node's own `self+0x50`
 * trampoline-record icon via `sub_803AD7C`), once collecting every node
 * with `self+0x2c` set into `gUnknown_03001408` (drawing that filtered
 * set through `sub_803AD80` then a second `sub_803AD7C` pass on a
 * different trampoline-record offset).
 *
 * A careful multi-iteration plain-C reconstruction reproduced the exact
 * same control flow, literal pool contents, and instruction shapes but
 * consistently needed one extra high register (`r9` on top of the ROM's
 * own single `r8`) to hold the function-lifetime
 * `gUnknown_03001418`/`gUnknown_03001400` addresses and the cached
 * `scroll` value simultaneously - the same "more live values than the
 * ROM's own build had to keep" register-pressure gap this project's
 * matching.md catalogs throughout (every attempt at re-deriving *which*
 * value the ROM's C source kept in a true local vs. re-read fresh from
 * the global at each use converged on the same 6-register shape, one
 * over the ROM's 5). NAKED per docs/workflow.md's escape hatch; every
 * instruction below is transcribed directly from the ROM disassembly
 * (`asm/code_3_2_20_8b7c.s`) and verified byte-for-byte against
 * `baserom.gba`, not inferred. */

extern void *gUnknown_03001408;
extern void *gUnknown_03000880;

NAKED s32 sub_802A208(void)
{
    asm(
        "push {r4, r5, r6, r7, lr}\n\t"
        "mov r7, r8\n\t"
        "push {r7}\n\t"
        "ldr r7, 11f\n\t"
        "ldr r0, [r7]\n\t"
        "ldr r0, [r0, #0xc]\n\t"
        "cmp r0, #0\n\t"
        "beq 1f\n\t"
        "bl sub_803AD78\n\t"
        "1:\n\t"
        "ldr r1, 12f\n\t"
        "mov r0, #0\n\t"
        "str r0, [r1]\n\t"
        "bl sub_8029B2C\n\t"
        "add r6, r0, #0\n\t"
        "ldr r5, 13f\n\t"
        "ldr r1, [r5]\n\t"
        "sub r1, r6, r1\n\t"
        "ldr r4, 14f\n\t"
        "ldr r0, [r4]\n\t"
        "ldr r0, [r0]\n\t"
        "cmp r1, r0\n\t"
        "ble 2f\n\t"
        "ldr r0, [r7]\n\t"
        "ldr r0, [r0, #0x28]\n\t"
        "bl sub_803AD78\n\t"
        "2:\n\t"
        "ldr r0, 15f\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r0, #0\n\t"
        "beq 3f\n\t"
        "bl sub_8029B8C\n\t"
        "ldr r1, [r5]\n\t"
        "add r1, r1, r0\n\t"
        "str r1, [r5]\n\t"
        "b 5f\n\t"
        ".align 2, 0\n"
        "11: .4byte gUnknown_03001418\n"
        "12: .4byte gUnknown_03001410\n"
        "13: .4byte gUnknown_03001420\n"
        "14: .4byte gUnknown_03001400\n"
        "15: .4byte gUnknown_0300141C\n"
        "3:\n\t"
        "ldr r0, 16f\n\t"
        "mov ip, r0\n\t"
        "ldr r3, [r4]\n\t"
        "ldr r2, [r0]\n\t"
        "ldr r0, [r3, #4]\n\t"
        "cmp r2, r0\n\t"
        "bge 5f\n\t"
        "lsl r1, r2, #2\n\t"
        "add r1, r1, r2\n\t"
        "lsl r1, r1, #2\n\t"
        "add r0, r3, #0\n\t"
        "add r0, #0x14\n\t"
        "add r0, r0, r1\n\t"
        "ldr r1, [r0]\n\t"
        "ldr r0, [r5]\n\t"
        "add r1, r1, r0\n\t"
        "ldr r0, [r7]\n\t"
        "ldr r0, [r0, #0x1c]\n\t"
        "add r0, r6, r0\n\t"
        "cmp r1, r0\n\t"
        "bgt 5f\n\t"
        "mov r8, r7\n\t"
        "add r7, r4, #0\n\t"
        "mov r4, ip\n\t"
        "4:\n\t"
        "mov r2, r8\n\t"
        "ldr r3, [r2]\n\t"
        "ldr r0, [r4]\n\t"
        "lsl r1, r0, #2\n\t"
        "add r1, r1, r0\n\t"
        "lsl r1, r1, #2\n\t"
        "add r1, #8\n\t"
        "ldr r0, [r7]\n\t"
        "add r0, r0, r1\n\t"
        "ldr r1, 17f\n\t"
        "ldrb r1, [r1]\n\t"
        "ldr r2, [r5]\n\t"
        "lsl r2, r2, #8\n\t"
        "ldr r3, [r3, #4]\n\t"
        "bl sub_803AD84\n\t"
        "ldr r0, [r4]\n\t"
        "add r2, r0, #1\n\t"
        "str r2, [r4]\n\t"
        "ldr r3, [r7]\n\t"
        "ldr r0, [r3, #4]\n\t"
        "cmp r2, r0\n\t"
        "bge 5f\n\t"
        "lsl r1, r2, #2\n\t"
        "add r1, r1, r2\n\t"
        "lsl r1, r1, #2\n\t"
        "add r0, r3, #0\n\t"
        "add r0, #0x14\n\t"
        "add r0, r0, r1\n\t"
        "ldr r1, [r0]\n\t"
        "ldr r0, [r5]\n\t"
        "add r1, r1, r0\n\t"
        "mov r3, r8\n\t"
        "ldr r0, [r3]\n\t"
        "ldr r0, [r0, #0x1c]\n\t"
        "add r0, r6, r0\n\t"
        "cmp r1, r0\n\t"
        "ble 4b\n\t"
        "5:\n\t"
        "ldr r0, 18f\n\t"
        "ldr r3, [r0]\n\t"
        "add r5, r0, #0\n\t"
        "6:\n\t"
        "ldr r4, [r3, #0x4c]\n\t"
        "ldr r1, [r3, #0x50]\n\t"
        "mov r2, #0x10\n\t"
        "ldrsh r0, [r1, r2]\n\t"
        "add r0, r3, r0\n\t"
        "ldr r1, [r1, #0x14]\n\t"
        "bl sub_803AD7C\n\t"
        "add r3, r4, #0\n\t"
        "ldr r0, [r5]\n\t"
        "cmp r3, r0\n\t"
        "bne 6b\n\t"
        "ldr r0, 19f\n\t"
        "mov r1, #0\n\t"
        "str r1, [r0]\n\t"
        "ldr r1, 18f\n\t"
        "ldr r3, [r1]\n\t"
        "add r5, r0, #0\n\t"
        "ldr r0, 20f\n\t"
        "mov r8, r0\n\t"
        "ldr r2, 21f\n\t"
        "mov ip, r2\n\t"
        "add r4, r5, #0\n\t"
        "mov r7, r8\n\t"
        "add r6, r1, #0\n\t"
        "7:\n\t"
        "add r0, r3, #0\n\t"
        "add r0, #0x2c\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r0, #0\n\t"
        "beq 8f\n\t"
        "ldr r0, [r4]\n\t"
        "ldr r2, [r7]\n\t"
        "lsl r1, r0, #2\n\t"
        "add r1, r1, r2\n\t"
        "str r3, [r1]\n\t"
        "add r0, #1\n\t"
        "str r0, [r4]\n\t"
        "8:\n\t"
        "ldr r3, [r3, #0x4c]\n\t"
        "ldr r0, [r6]\n\t"
        "cmp r3, r0\n\t"
        "bne 7b\n\t"
        "ldr r0, [r5]\n\t"
        "mov r3, r8\n\t"
        "ldr r1, [r3]\n\t"
        "mov r3, ip\n\t"
        "ldr r2, [r3]\n\t"
        "bl sub_803AD80\n\t"
        "mov r4, #0\n\t"
        "ldr r0, [r5]\n\t"
        "cmp r4, r0\n\t"
        "bge 10f\n\t"
        "9:\n\t"
        "ldr r0, 20f\n\t"
        "ldr r1, [r0]\n\t"
        "lsl r0, r4, #2\n\t"
        "add r0, r0, r1\n\t"
        "ldr r0, [r0]\n\t"
        "ldr r2, [r0, #0x50]\n\t"
        "mov r3, #0x18\n\t"
        "ldrsh r1, [r2, r3]\n\t"
        "add r0, r0, r1\n\t"
        "ldr r1, [r2, #0x1c]\n\t"
        "bl sub_803AD7C\n\t"
        "add r4, #1\n\t"
        "ldr r0, 19f\n\t"
        "ldr r0, [r0]\n\t"
        "cmp r4, r0\n\t"
        "blt 9b\n\t"
        "10:\n\t"
        "ldr r1, 22f\n\t"
        "ldr r0, [r1]\n\t"
        "add r0, #1\n\t"
        "str r0, [r1]\n\t"
        "ldr r0, 23f\n\t"
        "ldr r0, [r0]\n\t"
        "pop {r3}\n\t"
        "mov r8, r3\n\t"
        "pop {r4, r5, r6, r7}\n\t"
        "pop {r1}\n\t"
        "bx r1\n\t"
        ".align 2, 0\n"
        "16: .4byte gUnknown_03001404\n"
        "17: .4byte gUnknown_03001414\n"
        "18: .4byte gUnknown_03000884\n"
        "19: .4byte gUnknown_0300140C\n"
        "20: .4byte gUnknown_03001408\n"
        "21: .4byte gUnknown_03000880\n"
        "22: .4byte gUnknown_03001424\n"
        "23: .4byte gUnknown_03001410\n"
    );
}

/* `sub_802A3AC`: walks the whole `gUnknown_03000884`-rooted circular
 * actor list (`self+0x4c`) looking for the first OTHER node
 * (`self`'s own arg0, held live in `r8` for the whole function) that
 * passes a `sub_803AD7C` per-node visibility check and overlaps
 * `self`'s translated 12-byte AABB - the exact same categorical `r7`
 * register-allocation wall as `sub_802A018`/`sub_802A110` above (see
 * their doc comment), just with the AABB test's second scratch box now
 * additionally wrapped in an outer list-walk loop, and `self`'s own
 * pointer pinned in `r8` for the whole function on top of the already-
 * confirmed-unreachable `r7`. NAKED per docs/workflow.md's escape
 * hatch; every instruction below is transcribed directly from the ROM
 * disassembly (`asm/code_3_2_20_8b7c.s`) and verified byte-for-byte
 * against `baserom.gba`, not inferred. */
NAKED void *sub_802A3AC(void *self)
{
    asm(
        "push {r4, r5, r6, r7, lr}\n\t"
        "mov r7, r8\n\t"
        "push {r7}\n\t"
        "sub sp, #0x24\n\t"
        "mov r8, r0\n\t"
        "ldr r0, 8f\n\t"
        "ldr r0, [r0]\n\t"
        "ldr r5, [r0, #0x4c]\n\t"
        "add r7, sp, #0x18\n\t"
        "1:\n\t"
        "cmp r5, r8\n\t"
        "beq 2f\n\t"
        "ldr r1, [r5, #0x50]\n\t"
        "mov r2, #0x28\n\t"
        "ldrsh r0, [r1, r2]\n\t"
        "add r0, r5, r0\n\t"
        "ldr r1, [r1, #0x2c]\n\t"
        "bl sub_803AD7C\n\t"
        "lsl r0, r0, #0x18\n\t"
        "cmp r0, #0\n\t"
        "bne 2f\n\t"
        "add r1, sp, #0xc\n\t"
        "mov r0, r8\n\t"
        "add r0, #0x38\n\t"
        "ldm r0!, {r3, r4, r6}\n\t"
        "stm r1!, {r3, r4, r6}\n\t"
        "mov r1, r8\n\t"
        "ldr r0, [r1, #0x1c]\n\t"
        "asr r0, r0, #8\n\t"
        "ldr r2, [r1, #0x20]\n\t"
        "asr r2, r2, #8\n\t"
        "ldr r1, [r1, #0x24]\n\t"
        "asr r1, r1, #8\n\t"
        "add r4, sp, #0xc\n\t"
        "ldrh r3, [r4]\n\t"
        "add r0, r3, r0\n\t"
        "strh r0, [r4]\n\t"
        "ldrh r0, [r4, #2]\n\t"
        "add r0, r0, r2\n\t"
        "strh r0, [r4, #2]\n\t"
        "ldrh r6, [r4, #4]\n\t"
        "add r1, r6, r1\n\t"
        "strh r1, [r4, #4]\n\t"
        "mov r1, sp\n\t"
        "add r0, r4, #0\n\t"
        "ldm r0!, {r2, r3, r6}\n\t"
        "stm r1!, {r2, r3, r6}\n\t"
        "mov r0, sp\n\t"
        "mov r1, sp\n\t"
        "mov r2, #0xc\n\t"
        "bl sub_800014C\n\t"
        "add r1, sp, #0x18\n\t"
        "add r0, r5, #0\n\t"
        "add r0, #0x38\n\t"
        "ldm r0!, {r2, r3, r6}\n\t"
        "stm r1!, {r2, r3, r6}\n\t"
        "ldr r0, [r5, #0x1c]\n\t"
        "asr r0, r0, #8\n\t"
        "ldr r2, [r5, #0x20]\n\t"
        "asr r2, r2, #8\n\t"
        "ldr r1, [r5, #0x24]\n\t"
        "asr r1, r1, #8\n\t"
        "ldrh r3, [r7]\n\t"
        "add r0, r3, r0\n\t"
        "strh r0, [r7]\n\t"
        "ldrh r0, [r7, #2]\n\t"
        "add r0, r0, r2\n\t"
        "strh r0, [r7, #2]\n\t"
        "ldrh r6, [r7, #4]\n\t"
        "add r1, r6, r1\n\t"
        "strh r1, [r7, #4]\n\t"
        "add r1, r4, #0\n\t"
        "add r0, r7, #0\n\t"
        "ldm r0!, {r2, r3, r6}\n\t"
        "stm r1!, {r2, r3, r6}\n\t"
        "add r0, r4, #0\n\t"
        "add r1, r4, #0\n\t"
        "mov r2, #0xc\n\t"
        "bl sub_800014C\n\t"
        "mov r1, sp\n\t"
        "mov r0, #4\n\t"
        "ldrsh r2, [r1, r0]\n\t"
        "mov r6, #4\n\t"
        "ldrsh r3, [r4, r6]\n\t"
        "mov r6, #0xa\n\t"
        "ldrsh r0, [r4, r6]\n\t"
        "add r0, r3, r0\n\t"
        "cmp r2, r0\n\t"
        "bge 3f\n\t"
        "mov r6, #0xa\n\t"
        "ldrsh r0, [r1, r6]\n\t"
        "add r0, r2, r0\n\t"
        "cmp r0, r3\n\t"
        "ble 3f\n\t"
        "mov r0, #2\n\t"
        "ldrsh r2, [r1, r0]\n\t"
        "mov r6, #2\n\t"
        "ldrsh r3, [r4, r6]\n\t"
        "mov r6, #8\n\t"
        "ldrsh r0, [r4, r6]\n\t"
        "add r0, r3, r0\n\t"
        "cmp r2, r0\n\t"
        "bge 3f\n\t"
        "mov r6, #8\n\t"
        "ldrsh r0, [r1, r6]\n\t"
        "add r0, r2, r0\n\t"
        "cmp r0, r3\n\t"
        "ble 3f\n\t"
        "mov r0, #0\n\t"
        "ldrsh r2, [r1, r0]\n\t"
        "mov r6, #0\n\t"
        "ldrsh r3, [r4, r6]\n\t"
        "mov r0, #6\n\t"
        "ldrsh r4, [r4, r0]\n\t"
        "add r0, r3, r4\n\t"
        "cmp r2, r0\n\t"
        "bge 3f\n\t"
        "mov r4, #6\n\t"
        "ldrsh r0, [r1, r4]\n\t"
        "add r0, r2, r0\n\t"
        "cmp r0, r3\n\t"
        "bgt 4f\n\t"
        "3:\n\t"
        "mov r0, #0\n\t"
        "b 5f\n\t"
        ".align 2, 0\n"
        "8: .4byte gUnknown_03000884\n"
        "4:\n\t"
        "mov r0, #1\n\t"
        "5:\n\t"
        "cmp r0, #0\n\t"
        "beq 2f\n\t"
        "add r0, r5, #0\n\t"
        "b 6f\n\t"
        "2:\n\t"
        "ldr r5, [r5, #0x4c]\n\t"
        "ldr r0, 9f\n\t"
        "ldr r0, [r0]\n\t"
        "cmp r5, r0\n\t"
        "beq 7f\n\t"
        "b 1b\n\t"
        "7:\n\t"
        "mov r0, #0\n\t"
        "6:\n\t"
        "add sp, #0x24\n\t"
        "pop {r3}\n\t"
        "mov r8, r3\n\t"
        "pop {r4, r5, r6, r7}\n\t"
        "pop {r1}\n\t"
        "bx r1\n\t"
        ".align 2, 0\n"
        "9: .4byte gUnknown_03000884\n"
    );
}

asm(".align 2, 0");
