#include "core.h"
#include "icon_manager.h"
#include "pause_options_screen.h"

extern s32 sub_8028A30(void *mgr, s32 arg1);
extern s32 sub_8026F38(s32 arg0);
extern s32 sub_803AD80(void *arg0, void *arg1, void *arg2);
extern struct icon_manager *gUnknown_030012E0;
extern struct icon_manager *gUnknown_030012DC;

/* The functions below (0x08003B40, 0x08003BDC, 0x08003C90, 0x08003D3C,
 * 0x08003F30, 0x080041BC) are all fully understood and byte-exact
 * matched, but written as NAKED asm transcriptions rather than plain C
 * - they all hit this project's well-documented "last mile" gcc-2.9
 * scratch-register nondeterminism (see `sub_8006600`,
 * `src/graphics/oam_count.c`, and `src/util/printf_util.c`'s
 * `sub_8000CBC` for the established pattern/technique) where a
 * fully-traced C reconstruction gets every field/branch/call right but
 * can't be coaxed into the ROM's exact scratch-register choices. See
 * docs/matching.md's write-up for this chunk (and
 * docs/matching/issue-6-0x08003f30-overlay-ui.md for sub_8003F30's
 * semantics derivation) for the full register-allocation story that
 * motivated the NAKED conversion. Their siblings `sub_8004914`/
 * `sub_80049CC` hit the same difficulty class but live in
 * `src/graphics/settings_menu20.c` instead - `sub_800450C` (still
 * fully raw, real bytes in `asm/code_3_1_10_4.s`) sits at ROM
 * `0x0800450C`, between this file's `sub_80041BC` and
 * `src/graphics/settings_menu2.c`'s `0x080047F8`, forcing the object
 * split. */

extern void *sub_8026EDC(s32 size);
extern void sub_8002FCC(void *newObj, void *tmpl);
extern void sub_8002FD8(void *newObj);
extern void sub_80006A8(void);
extern void sub_80007AC(void *arg0);
extern void *gUnknown_03001304;
extern u32 gUnknown_030007E0;
extern u8 gUnknown_03000800;
extern void *gUnknown_03000804;
extern s32 sub_8001F50(void *arg0);
extern s32 sub_8002EFC(void *newObj);
extern s32 sub_8002FD4(void *newObj);
extern void sub_800014C(void *arg0, s32 arg1, s32 arg2);
extern void sub_8026ED0(void *newObj);

/* A "connecting..." SIO-handshake spinner dialog: allocates a small
 * icon object from self->field_8c's template, then loops VBlank-
 * waiting while polling input (cancel -> state 3), the link-active
 * flag gUnknown_03000800, and sub_8001F50 (the link-connection/
 * handshake driver documented in docs/rom_map.md's SIO/link-cable
 * section) until the spinner object's own state (sub_8002EFC) settles.
 * Returns that state; when it settles at 0, also feeds a result value
 * through self->field_90 via sub_800014C.
 *
 * Written as NAKED asm, not plain C: a full C reconstruction (kept in
 * git history) got every field/branch/call right, but this function
 * sits in the same "last mile" gcc-2.9 scratch-register
 * nondeterminism class as this file's other functions (see this file's
 * own header comment above for the general pattern) and wasn't worth a
 * fresh per-register archaeology pass given that track
 * record. Every instruction below is confirmed byte-identical to the
 * ROM - full NAKED transcription, like this project's other
 * hard-compiler-limitation cases (see `src/util/printf_util.c`'s
 * `sub_8000CBC` for the established pattern), is more honest than
 * continuing to chase these scratch-register choices through plain C. */
NAKED s32 sub_8003B40(struct pause_options_screen *self)
{
    asm(
        "push {r4, r5, r6, lr}\n\t"
        "add r6, r0, #0\n\t"
        "mov r0, #0x88\n\t"
        "lsl r0, r0, #2\n\t"
        "bl sub_8026EDC\n\t"
        "add r5, r0, #0\n\t"
        "add r0, r6, #0\n\t"
        "add r0, #0x8c\n\t"
        "ldr r1, [r0]\n\t"
        "add r0, r5, #0\n\t"
        "bl sub_8002FCC\n\t"
        "add r0, r5, #0\n\t"
        "bl sub_8002FD8\n\t"
    "1:\n\t"
        "bl sub_80006A8\n\t"
        "ldr r0, 2f\n\t"
        "ldr r0, [r0]\n\t"
        "bl sub_80007AC\n\t"
        "ldr r0, 3f\n\t"
        "ldr r0, [r0]\n\t"
        "mov r1, #2\n\t"
        "and r0, r1\n\t"
        "lsl r0, r0, #0x10\n\t"
        "lsr r1, r0, #0x10\n\t"
        "cmp r1, #0\n\t"
        "beq 4f\n\t"
        "mov r4, #3\n\t"
        "b 6f\n\t"
        ".align 2, 0\n\t"
    "2: .4byte gUnknown_03001304\n\t"
    "3: .4byte gUnknown_030007E0\n\t"
    "4:\n\t"
        "ldr r2, 8f\n\t"
        "ldrb r0, [r2]\n\t"
        "cmp r0, #0\n\t"
        "beq 5f\n\t"
        "strb r1, [r2]\n\t"
        "add r0, r5, #0\n\t"
        "bl sub_8002FD8\n\t"
    "5:\n\t"
        "ldr r0, 9f\n\t"
        "ldr r0, [r0]\n\t"
        "bl sub_8001F50\n\t"
        "add r0, r5, #0\n\t"
        "bl sub_8002EFC\n\t"
        "add r4, r0, #0\n\t"
    "6:\n\t"
        "cmp r4, #1\n\t"
        "beq 1b\n\t"
        "cmp r4, #0\n\t"
        "bne 7f\n\t"
        "add r0, r5, #0\n\t"
        "bl sub_8002FD4\n\t"
        "add r1, r0, #0\n\t"
        "add r0, r6, #0\n\t"
        "add r0, #0x90\n\t"
        "ldr r0, [r0]\n\t"
        "mov r2, #0x80\n\t"
        "lsl r2, r2, #2\n\t"
        "bl sub_800014C\n\t"
    "7:\n\t"
        "add r0, r5, #0\n\t"
        "bl sub_8026ED0\n\t"
        "add r0, r4, #0\n\t"
        "pop {r4, r5, r6}\n\t"
        "pop {r1}\n\t"
        "bx r1\n\t"
        ".align 2, 0\n\t"
    "8: .4byte gUnknown_03000800\n\t"
    "9: .4byte gUnknown_03000804\n\t"
    );
}

/* Draws `label1` (if non-zero) centered at Y=0x87, then `label2` (if
 * non-zero) centered at Y=0x91, both into gUnknown_030012DC.
 *
 * Written as NAKED asm, not plain C: a full C reconstruction (kept in
 * git history) hit the same "last mile" gcc-2.9 scratch-register
 * nondeterminism documented in this file's header comment above,
 * compounded here by the ROM spilling a constant through `ip`, which
 * plain C has no way to
 * request at all. Every instruction below is confirmed byte-identical
 * to the ROM - full NAKED transcription, like this project's other
 * hard-compiler-limitation cases (see `src/util/printf_util.c`'s
 * `sub_8000CBC` for the established pattern), is more honest than
 * continuing to chase these scratch-register choices through plain C. */
NAKED void sub_8003BDC(struct pause_options_screen *self, s32 label1, s32 label2)
{
    asm(
        "push {r4, r5, r6, r7, lr}\n\t"
        "add r5, r1, #0\n\t"
        "add r6, r2, #0\n\t"
        "ldr r7, 3f\n\t"
        "ldr r0, [r7]\n\t"
        "mov r1, #0\n\t"
        "bl sub_8028A30\n\t"
        "cmp r5, #0\n\t"
        "beq 1f\n\t"
        "ldr r0, [r7]\n\t"
        "mov r4, #0x98\n\t"
        "lsl r4, r4, #1\n\t"
        "add r1, r0, r4\n\t"
        "ldr r2, [r1]\n\t"
        "mov r3, #0x10\n\t"
        "ldrsh r1, [r2, r3]\n\t"
        "add r0, r0, r1\n\t"
        "ldr r2, [r2, #0x14]\n\t"
        "add r1, r5, #0\n\t"
        "bl sub_803AD80\n\t"
        "add r1, r0, #0\n\t"
        "mov r0, #0xf0\n\t"
        "sub r0, r0, r1\n\t"
        "asr r3, r0, #1\n\t"
        "ldr r0, [r7]\n\t"
        "mov r1, #0x87\n\t"
        "mov ip, r1\n\t"
        "mov r2, #0x88\n\t"
        "lsl r2, r2, #1\n\t"
        "add r1, r0, r2\n\t"
        "str r3, [r1]\n\t"
        "mov r3, #0x8a\n\t"
        "lsl r3, r3, #1\n\t"
        "add r1, r0, r3\n\t"
        "mov r2, ip\n\t"
        "str r2, [r1]\n\t"
        "add r4, r0, r4\n\t"
        "ldr r2, [r4]\n\t"
        "mov r3, #0x20\n\t"
        "ldrsh r1, [r2, r3]\n\t"
        "add r0, r0, r1\n\t"
        "ldr r2, [r2, #0x24]\n\t"
        "add r1, r5, #0\n\t"
        "bl sub_803AD80\n\t"
    "1:\n\t"
        "cmp r6, #0\n\t"
        "beq 2f\n\t"
        "ldr r0, [r7]\n\t"
        "mov r4, #0x98\n\t"
        "lsl r4, r4, #1\n\t"
        "add r1, r0, r4\n\t"
        "ldr r2, [r1]\n\t"
        "mov r5, #0x10\n\t"
        "ldrsh r1, [r2, r5]\n\t"
        "add r0, r0, r1\n\t"
        "ldr r2, [r2, #0x14]\n\t"
        "add r1, r6, #0\n\t"
        "bl sub_803AD80\n\t"
        "add r1, r0, #0\n\t"
        "mov r0, #0xf0\n\t"
        "sub r0, r0, r1\n\t"
        "asr r3, r0, #1\n\t"
        "ldr r0, [r7]\n\t"
        "mov r2, #0x91\n\t"
        "mov r5, #0x88\n\t"
        "lsl r5, r5, #1\n\t"
        "add r1, r0, r5\n\t"
        "str r3, [r1]\n\t"
        "mov r3, #0x8a\n\t"
        "lsl r3, r3, #1\n\t"
        "add r1, r0, r3\n\t"
        "str r2, [r1]\n\t"
        "add r4, r0, r4\n\t"
        "ldr r2, [r4]\n\t"
        "mov r5, #0x20\n\t"
        "ldrsh r1, [r2, r5]\n\t"
        "add r0, r0, r1\n\t"
        "ldr r2, [r2, #0x24]\n\t"
        "add r1, r6, #0\n\t"
        "bl sub_803AD80\n\t"
    "2:\n\t"
        "pop {r4, r5, r6, r7}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
        ".align 2, 0\n\t"
    "3: .4byte gUnknown_030012DC\n\t"
    );
}

/* Same centered-label shape as sub_80049CC (src/graphics/settings_menu20.c),
 * but always label 0x23, drawn into gUnknown_030012DC (not E0) at
 * fixed Y=0x87, and with a highlight-dependent initial visibility call.
 *
 * Written as NAKED asm, not plain C: a full C reconstruction (kept in
 * git history) came within one register-letter choice of matching (a
 * scratch register for reloading `mgr` before the posX/posY writes -
 * r0 in the reconstruction, r3 in the ROM) after reordering the
 * width->half computation ahead of the reload; several explicit-
 * register-pin attempts on just that one temporary didn't close it -
 * same "last mile" gcc-2.9 scratch-register nondeterminism documented
 * on `sub_80049CC`. Every instruction below is confirmed
 * byte-identical to the ROM - full NAKED transcription, like this
 * project's other hard-compiler-limitation cases (see
 * `src/util/printf_util.c`'s `sub_8000CBC` for the established
 * pattern), is more honest than continuing to chase this one register
 * choice through plain C. */
NAKED void sub_8003C90(struct pause_options_screen *self, u8 highlight)
{
    asm(
        "push {r4, r5, r6, lr}\n\t"
        "mov r6, r8\n\t"
        "push {r6}\n\t"
        "add r2, r0, #0\n\t"
        "lsl r1, r1, #0x18\n\t"
        "cmp r1, #0\n\t"
        "beq 3f\n\t"
        "ldr r0, 2f\n\t"
        "ldr r3, [r0]\n\t"
        "ldr r0, [r2, #4]\n\t"
        "asr r0, r0, #2\n\t"
        "mov r1, #1\n\t"
        "and r0, r1\n\t"
        "mov r1, #2\n\t"
        "cmp r0, #0\n\t"
        "beq 1f\n\t"
        "mov r1, #1\n\t"
    "1:\n\t"
        "add r0, r3, #0\n\t"
        "bl sub_8028A30\n\t"
        "b 4f\n\t"
        ".align 2, 0\n\t"
    "2: .4byte gUnknown_030012DC\n\t"
    "3:\n\t"
        "ldr r0, 5f\n\t"
        "ldr r0, [r0]\n\t"
        "mov r1, #0\n\t"
        "bl sub_8028A30\n\t"
    "4:\n\t"
        "ldr r0, 5f\n\t"
        "mov r8, r0\n\t"
        "ldr r4, [r0]\n\t"
        "mov r5, #0x98\n\t"
        "lsl r5, r5, #1\n\t"
        "add r0, r4, r5\n\t"
        "ldr r0, [r0]\n\t"
        "add r6, r0, #0\n\t"
        "add r6, #0x10\n\t"
        "mov r1, #0x10\n\t"
        "ldrsh r0, [r0, r1]\n\t"
        "add r4, r4, r0\n\t"
        "mov r0, #0x23\n\t"
        "bl sub_8026F38\n\t"
        "add r1, r0, #0\n\t"
        "ldr r2, [r6, #4]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_803AD80\n\t"
        "mov r1, #0xf0\n\t"
        "sub r1, r1, r0\n\t"
        "asr r1, r1, #1\n\t"
        "mov r3, r8\n\t"
        "ldr r4, [r3]\n\t"
        "mov r2, #0x87\n\t"
        "mov r3, #0x88\n\t"
        "lsl r3, r3, #1\n\t"
        "add r0, r4, r3\n\t"
        "str r1, [r0]\n\t"
        "mov r1, #0x8a\n\t"
        "lsl r1, r1, #1\n\t"
        "add r0, r4, r1\n\t"
        "str r2, [r0]\n\t"
        "add r5, r4, r5\n\t"
        "ldr r0, [r5]\n\t"
        "add r5, r0, #0\n\t"
        "add r5, #0x20\n\t"
        "mov r3, #0x20\n\t"
        "ldrsh r0, [r0, r3]\n\t"
        "add r4, r4, r0\n\t"
        "mov r0, #0x23\n\t"
        "bl sub_8026F38\n\t"
        "add r1, r0, #0\n\t"
        "ldr r2, [r5, #4]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_803AD80\n\t"
        "pop {r3}\n\t"
        "mov r8, r3\n\t"
        "pop {r4, r5, r6}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
        ".align 2, 0\n\t"
    "5: .4byte gUnknown_030012DC\n\t"
    );
}

extern u8 gStaticData_0816B138[];

/* Draws `value`'s label centered at Y=0x87, then draws a
 * highlighted/plain pair of fixed labels (0x29/0x2a, purpose
 * unconfirmed) swapping Y=0x87 vs Y=0x91 depending on `self->field_10`
 * - each pair member's slot gets a `gStaticData_0816B138` draw at its
 * *previous* position right before the real label, which reads as a
 * clear/overwrite step rather than a width probe (the return value is
 * never used).
 *
 * Written as NAKED asm, not plain C: a full C reconstruction (kept in
 * git history) got every field/branch/call right, but hit the same
 * "last mile" gcc-2.9 scratch-register nondeterminism as this file's
 * sibling functions (see this file's header comment above for the
 * general pattern) - the prologue/instruction shape was right but a handful of
 * scratch-register choices differed, and this function additionally
 * spills a constant through `ip` in the ROM, which plain C has no way
 * to request. Every instruction below is confirmed byte-identical to
 * the ROM - full NAKED transcription, like this project's other
 * hard-compiler-limitation cases (see `src/util/printf_util.c`'s
 * `sub_8000CBC` for the established pattern), is more honest than
 * continuing to chase these scratch-register choices through plain C. */
NAKED void sub_8003D3C(struct pause_options_screen *self, s32 value)
{
    asm(
        "push {r4, r5, r6, r7, lr}\n\t"
        "mov r7, sl\n\t"
        "mov r6, sb\n\t"
        "mov r5, r8\n\t"
        "push {r5, r6, r7}\n\t"
        "mov sl, r0\n\t"
        "add r6, r1, #0\n\t"
        "ldr r7, 2f\n\t"
        "ldr r0, [r7]\n\t"
        "mov r1, #0\n\t"
        "bl sub_8028A30\n\t"
        "ldr r4, [r7]\n\t"
        "mov r0, #0x98\n\t"
        "lsl r0, r0, #1\n\t"
        "mov r8, r0\n\t"
        "add r0, r4, r0\n\t"
        "ldr r0, [r0]\n\t"
        "add r5, r0, #0\n\t"
        "add r5, #0x10\n\t"
        "mov r1, #0x10\n\t"
        "ldrsh r0, [r0, r1]\n\t"
        "add r4, r4, r0\n\t"
        "add r0, r6, #0\n\t"
        "bl sub_8026F38\n\t"
        "add r1, r0, #0\n\t"
        "ldr r2, [r5, #4]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_803AD80\n\t"
        "mov r1, #0xa0\n\t"
        "sub r1, r1, r0\n\t"
        "ldr r4, [r7]\n\t"
        "mov r2, #0x87\n\t"
        "mov sb, r2\n\t"
        "mov r3, #0x88\n\t"
        "lsl r3, r3, #1\n\t"
        "add r0, r4, r3\n\t"
        "str r1, [r0]\n\t"
        "mov r1, #0x8a\n\t"
        "lsl r1, r1, #1\n\t"
        "add r0, r4, r1\n\t"
        "str r2, [r0]\n\t"
        "mov r2, r8\n\t"
        "add r0, r4, r2\n\t"
        "ldr r0, [r0]\n\t"
        "add r5, r0, #0\n\t"
        "add r5, #0x20\n\t"
        "mov r3, #0x20\n\t"
        "ldrsh r0, [r0, r3]\n\t"
        "add r4, r4, r0\n\t"
        "add r0, r6, #0\n\t"
        "bl sub_8026F38\n\t"
        "add r1, r0, #0\n\t"
        "ldr r2, [r5, #4]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_803AD80\n\t"
        "ldr r2, [r7]\n\t"
        "mov r4, sl\n\t"
        "ldr r0, [r4, #4]\n\t"
        "asr r0, r0, #2\n\t"
        "mov r1, #1\n\t"
        "and r0, r1\n\t"
        "mov r1, #2\n\t"
        "cmp r0, #0\n\t"
        "beq 1f\n\t"
        "mov r1, #1\n\t"
    "1:\n\t"
        "add r0, r2, #0\n\t"
        "bl sub_8028A30\n\t"
        "mov r1, sl\n\t"
        "ldr r0, [r1, #0x10]\n\t"
        "cmp r0, #0\n\t"
        "bne 4f\n\t"
        "ldr r0, [r7]\n\t"
        "mov r2, #0xa8\n\t"
        "mov r3, #0x88\n\t"
        "lsl r3, r3, #1\n\t"
        "add r1, r0, r3\n\t"
        "str r2, [r1]\n\t"
        "mov r4, #0x8a\n\t"
        "lsl r4, r4, #1\n\t"
        "add r1, r0, r4\n\t"
        "mov r2, sb\n\t"
        "str r2, [r1]\n\t"
        "mov r3, r8\n\t"
        "add r1, r0, r3\n\t"
        "ldr r2, [r1]\n\t"
        "mov r4, #0x20\n\t"
        "ldrsh r1, [r2, r4]\n\t"
        "add r0, r0, r1\n\t"
        "ldr r1, 3f\n\t"
        "ldr r2, [r2, #0x24]\n\t"
        "bl sub_803AD80\n\t"
        "ldr r4, [r7]\n\t"
        "mov r1, #0xb0\n\t"
        "mov r2, #0x88\n\t"
        "lsl r2, r2, #1\n\t"
        "add r0, r4, r2\n\t"
        "str r1, [r0]\n\t"
        "mov r3, #0x8a\n\t"
        "lsl r3, r3, #1\n\t"
        "add r0, r4, r3\n\t"
        "mov r1, sb\n\t"
        "str r1, [r0]\n\t"
        "mov r2, r8\n\t"
        "add r0, r4, r2\n\t"
        "ldr r0, [r0]\n\t"
        "add r5, r0, #0\n\t"
        "add r5, #0x20\n\t"
        "mov r3, #0x20\n\t"
        "ldrsh r0, [r0, r3]\n\t"
        "add r4, r4, r0\n\t"
        "mov r0, #0x29\n\t"
        "bl sub_8026F38\n\t"
        "add r1, r0, #0\n\t"
        "ldr r2, [r5, #4]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_803AD80\n\t"
        "b 5f\n\t"
        ".align 2, 0\n\t"
    "2: .4byte gUnknown_030012DC\n\t"
    "3: .4byte gStaticData_0816B138\n\t"
    "4:\n\t"
        "ldr r0, [r7]\n\t"
        "mov r2, #0xa8\n\t"
        "mov r5, #0x91\n\t"
        "mov r4, #0x88\n\t"
        "lsl r4, r4, #1\n\t"
        "add r1, r0, r4\n\t"
        "str r2, [r1]\n\t"
        "add r2, #0x6c\n\t"
        "add r1, r0, r2\n\t"
        "str r5, [r1]\n\t"
        "mov r3, r8\n\t"
        "add r1, r0, r3\n\t"
        "ldr r2, [r1]\n\t"
        "mov r4, #0x20\n\t"
        "ldrsh r1, [r2, r4]\n\t"
        "add r0, r0, r1\n\t"
        "ldr r1, 6f\n\t"
        "ldr r2, [r2, #0x24]\n\t"
        "bl sub_803AD80\n\t"
        "ldr r4, [r7]\n\t"
        "mov r1, #0xb0\n\t"
        "mov r2, #0x88\n\t"
        "lsl r2, r2, #1\n\t"
        "add r0, r4, r2\n\t"
        "str r1, [r0]\n\t"
        "mov r3, #0x8a\n\t"
        "lsl r3, r3, #1\n\t"
        "add r0, r4, r3\n\t"
        "str r5, [r0]\n\t"
        "mov r1, r8\n\t"
        "add r0, r4, r1\n\t"
        "ldr r0, [r0]\n\t"
        "add r5, r0, #0\n\t"
        "add r5, #0x20\n\t"
        "mov r2, #0x20\n\t"
        "ldrsh r0, [r0, r2]\n\t"
        "add r4, r4, r0\n\t"
        "mov r0, #0x2a\n\t"
        "bl sub_8026F38\n\t"
        "add r1, r0, #0\n\t"
        "ldr r2, [r5, #4]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_803AD80\n\t"
    "5:\n\t"
        "ldr r4, 7f\n\t"
        "ldr r0, [r4]\n\t"
        "mov r1, #0\n\t"
        "bl sub_8028A30\n\t"
        "mov r3, sl\n\t"
        "ldr r0, [r3, #0x10]\n\t"
        "cmp r0, #0\n\t"
        "bne 8f\n\t"
        "ldr r3, [r4]\n\t"
        "mov r1, #0xb0\n\t"
        "mov r2, #0x91\n\t"
        "mov r4, #0x88\n\t"
        "lsl r4, r4, #1\n\t"
        "add r0, r3, r4\n\t"
        "str r1, [r0]\n\t"
        "add r1, #0x64\n\t"
        "add r0, r3, r1\n\t"
        "str r2, [r0]\n\t"
        "add r2, #0x9f\n\t"
        "add r0, r3, r2\n\t"
        "ldr r0, [r0]\n\t"
        "add r5, r0, #0\n\t"
        "add r5, #0x20\n\t"
        "mov r1, #0x20\n\t"
        "ldrsh r4, [r0, r1]\n\t"
        "add r4, r3, r4\n\t"
        "mov r0, #0x2a\n\t"
        "bl sub_8026F38\n\t"
        "add r1, r0, #0\n\t"
        "ldr r2, [r5, #4]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_803AD80\n\t"
        "b 9f\n\t"
        ".align 2, 0\n\t"
    "6: .4byte gStaticData_0816B138\n\t"
    "7: .4byte gUnknown_030012DC\n\t"
    "8:\n\t"
        "ldr r3, [r4]\n\t"
        "mov r1, #0xb0\n\t"
        "mov r2, #0x87\n\t"
        "mov r4, #0x88\n\t"
        "lsl r4, r4, #1\n\t"
        "add r0, r3, r4\n\t"
        "str r1, [r0]\n\t"
        "add r1, #0x64\n\t"
        "add r0, r3, r1\n\t"
        "str r2, [r0]\n\t"
        "add r2, #0xa9\n\t"
        "add r0, r3, r2\n\t"
        "ldr r0, [r0]\n\t"
        "add r5, r0, #0\n\t"
        "add r5, #0x20\n\t"
        "mov r1, #0x20\n\t"
        "ldrsh r4, [r0, r1]\n\t"
        "add r4, r3, r4\n\t"
        "mov r0, #0x29\n\t"
        "bl sub_8026F38\n\t"
        "add r1, r0, #0\n\t"
        "ldr r2, [r5, #4]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_803AD80\n\t"
    "9:\n\t"
        "pop {r3, r4, r5}\n\t"
        "mov r8, r3\n\t"
        "mov sb, r4\n\t"
        "mov sl, r5\n\t"
        "pop {r4, r5, r6, r7}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
        ".align 2, 0\n\t"
    );
}

extern u8 sub_8002CE8(void *handle, s32 rowIndex);
extern void sub_8008890(void *arg0, s32 arg1, s32 arg2);
extern s32 itoa(s32 value, u8 *buffer, s32 base);

/* `rowObjA`/`rowObjB`/`rowObjC` entries (see pause_options_screen.h)
 * are small on-screen objects with just a Q8 `x`/`y` position at their
 * front - `sub_800450C` (this chunk's other remaining function,
 * currently still fully raw) allocates and positions them. */
struct row_obj {
    s32 x;
    s32 y;
};

/* Draws this settings row's three numeric stat values -
 * `statPtr->field_4`/`field_10`/`field_8` of the row's own `struct
 * settings_row_stats` (`statPtr` is `(&self->currentStats)[rowIdx]`,
 * i.e. `currentStats` and `rowStats[0..3]` read as one contiguous
 * 5-element array - `sub_8004860`/`sub_80048E0`,
 * `src/graphics/settings_menu2.c`, already establish `rowStats` as
 * this same array shape) - as plain decimal strings into
 * `self->rowObjA[rowIdx]`/`rowObjC[rowIdx]`/`rowObjB[rowIdx]`
 * respectively (each drawn via `gUnknown_030012DC`'s `record->slots[2]`
 * trampoline, and each preceded by the same highlight/dim
 * `sub_8028A30` call this chunk's other row-label functions already
 * establish - `sub_80041BC`'s own `flag` parameter selects which row
 * is "selected", matching that shared idiom). A fourth value
 * (`statPtr->field_0`) is formatted as `"NN%"` by `itoa`-ing then
 * manually scanning for the NUL terminator and overwriting it with a
 * literal `%` byte (re-terminating one byte later) - measured once via
 * `gUnknown_030012E0`'s `slots[0]` trampoline to get its pixel width,
 * then drawn a second time via that same manager's `slots[2]`
 * trampoline, right-aligned against `label1` using the measured
 * width (`posX = label1 - width + 0x1f`) - the standard
 * "measure, then right-align" idiom this ROM region uses throughout.
 *
 * Written as NAKED asm, not plain C: a full C reconstruction (kept in
 * git history, see docs/matching/issue-6-0x08003f30-overlay-ui.md for
 * the semantics derivation) confirmed every load/store/call - all four
 * positioned-draw blocks follow the exact same position/reset/format/
 * highlight/draw shape - but hit the same "several near-identical
 * unrolled blocks, each wanting the loop-carried registers in slightly
 * different places" difficulty class this file's other functions
 * document at length (see this file's header comment above),
 * compounded here by four blocks instead of two-to-three and by
 * several cross-block-live locals (`highlight`, the running `buf[]`
 * contents, the row object pointers). Every instruction below is
 * confirmed byte-identical to the ROM - full NAKED transcription, like
 * this project's other hard-compiler-limitation cases (see
 * `src/util/printf_util.c`'s `sub_8000CBC` for the established
 * pattern), is more honest than continuing to chase these
 * scratch-register choices through plain C. */
NAKED void sub_8003F30(struct pause_options_screen *self, s32 label1, s32 label2, s32 rowIdx, u8 flag)
{
    asm(
        "push {r4, r5, r6, r7, lr}\n\t"
        "mov r7, sl\n\t"
        "mov r6, sb\n\t"
        "mov r5, r8\n\t"
        "push {r5, r6, r7}\n\t"
        "sub sp, #0x1c\n\t"
        "add r7, r0, #0\n\t"
        "mov r8, r1\n\t"
        "mov sl, r2\n\t"
        "add r4, r3, #0\n\t"
        "add r0, sp, #0x3c\n\t"
        "ldrb r0, [r0]\n\t"
        "str r0, [sp, #8]\n\t"
        "lsl r1, r4, #2\n\t"
        "add r0, r1, r4\n\t"
        "lsl r0, r0, #2\n\t"
        "add r0, #0x28\n\t"
        "add r0, r7, r0\n\t"
        "str r0, [sp, #0xc]\n\t"
        "mov r5, r8\n\t"
        "add r5, #0x2b\n\t"
        "mov r6, sl\n\t"
        "add r6, #5\n\t"
        "add r0, r7, #0\n\t"
        "add r0, #0xa8\n\t"
        "add r0, r0, r1\n\t"
        "ldr r0, [r0]\n\t"
        "lsl r1, r5, #8\n\t"
        "str r1, [r0]\n\t"
        "lsl r1, r6, #8\n\t"
        "str r1, [r0, #4]\n\t"
        "mov r1, #0\n\t"
        "mov r2, #0\n\t"
        "bl sub_8008890\n\t"
        "add r5, #0xd\n\t"
        "mov r6, sl\n\t"
        "ldr r1, [sp, #0xc]\n\t"
        "ldr r0, [r1, #4]\n\t"
        "mov r1, sp\n\t"
        "mov r2, #0xa\n\t"
        "bl itoa\n\t"
        "ldr r2, [sp, #8]\n\t"
        "cmp r2, #0\n\t"
        "beq 3f\n\t"
        "ldr r0, 2f\n\t"
        "ldr r2, [r0]\n\t"
        "ldr r0, [r7, #4]\n\t"
        "asr r0, r0, #2\n\t"
        "mov r1, #1\n\t"
        "and r0, r1\n\t"
        "mov r1, #2\n\t"
        "cmp r0, #0\n\t"
        "beq 1f\n\t"
        "mov r1, #1\n\t"
    "1:\n\t"
        "add r0, r2, #0\n\t"
        "bl sub_8028A30\n\t"
        "b 4f\n\t"
        ".align 2, 0\n\t"
    "2: .4byte gUnknown_030012DC\n\t"
    "3:\n\t"
        "ldr r0, 6f\n\t"
        "ldr r0, [r0]\n\t"
        "mov r1, #0\n\t"
        "bl sub_8028A30\n\t"
    "4:\n\t"
        "ldr r3, 6f\n\t"
        "mov sb, r3\n\t"
        "ldr r2, [r3]\n\t"
        "mov r1, #0x88\n\t"
        "lsl r1, r1, #1\n\t"
        "add r0, r2, r1\n\t"
        "str r5, [r0]\n\t"
        "mov r3, #0x8a\n\t"
        "lsl r3, r3, #1\n\t"
        "add r0, r2, r3\n\t"
        "str r6, [r0]\n\t"
        "add r1, #0x20\n\t"
        "add r0, r2, r1\n\t"
        "ldr r1, [r0]\n\t"
        "mov r3, #0x20\n\t"
        "ldrsh r0, [r1, r3]\n\t"
        "add r0, r2, r0\n\t"
        "ldr r2, [r1, #0x24]\n\t"
        "mov r1, sp\n\t"
        "bl sub_803AD80\n\t"
        "mov r5, r8\n\t"
        "add r5, #7\n\t"
        "mov r6, sl\n\t"
        "add r6, #0x1e\n\t"
        "lsl r4, r4, #2\n\t"
        "add r0, r7, #0\n\t"
        "add r0, #0xd0\n\t"
        "add r0, r0, r4\n\t"
        "ldr r0, [r0]\n\t"
        "lsl r1, r5, #8\n\t"
        "str r1, [r0]\n\t"
        "lsl r1, r6, #8\n\t"
        "str r1, [r0, #4]\n\t"
        "mov r1, #0\n\t"
        "mov r2, #0\n\t"
        "bl sub_8008890\n\t"
        "add r5, #9\n\t"
        "sub r6, #7\n\t"
        "ldr r1, [sp, #0xc]\n\t"
        "ldr r0, [r1, #0x10]\n\t"
        "mov r1, sp\n\t"
        "mov r2, #0xa\n\t"
        "bl itoa\n\t"
        "str r4, [sp, #0x10]\n\t"
        "mov r2, sl\n\t"
        "add r2, #0x1e\n\t"
        "str r2, [sp, #0x18]\n\t"
        "str r6, [sp, #0x14]\n\t"
        "ldr r3, [sp, #8]\n\t"
        "cmp r3, #0\n\t"
        "beq 7f\n\t"
        "mov r0, sb\n\t"
        "ldr r2, [r0]\n\t"
        "ldr r0, [r7, #4]\n\t"
        "asr r0, r0, #2\n\t"
        "mov r1, #1\n\t"
        "and r0, r1\n\t"
        "mov r1, #2\n\t"
        "cmp r0, #0\n\t"
        "beq 5f\n\t"
        "mov r1, #1\n\t"
    "5:\n\t"
        "add r0, r2, #0\n\t"
        "bl sub_8028A30\n\t"
        "b 8f\n\t"
        ".align 2, 0\n\t"
    "6: .4byte gUnknown_030012DC\n\t"
    "7:\n\t"
        "mov r1, sb\n\t"
        "ldr r0, [r1]\n\t"
        "mov r1, #0\n\t"
        "bl sub_8028A30\n\t"
    "8:\n\t"
        "ldr r4, 10f\n\t"
        "ldr r2, [r4]\n\t"
        "mov r3, #0x88\n\t"
        "lsl r3, r3, #1\n\t"
        "add r0, r2, r3\n\t"
        "str r5, [r0]\n\t"
        "mov r1, #0x8a\n\t"
        "lsl r1, r1, #1\n\t"
        "add r0, r2, r1\n\t"
        "str r6, [r0]\n\t"
        "add r3, #0x20\n\t"
        "add r0, r2, r3\n\t"
        "ldr r1, [r0]\n\t"
        "mov r3, #0x20\n\t"
        "ldrsh r0, [r1, r3]\n\t"
        "add r0, r2, r0\n\t"
        "ldr r2, [r1, #0x24]\n\t"
        "mov r1, sp\n\t"
        "bl sub_803AD80\n\t"
        "mov r5, r8\n\t"
        "add r5, #0x2b\n\t"
        "add r0, r7, #0\n\t"
        "add r0, #0xbc\n\t"
        "ldr r1, [sp, #0x10]\n\t"
        "add r0, r0, r1\n\t"
        "ldr r0, [r0]\n\t"
        "lsl r1, r5, #8\n\t"
        "str r1, [r0]\n\t"
        "ldr r2, [sp, #0x18]\n\t"
        "lsl r1, r2, #8\n\t"
        "str r1, [r0, #4]\n\t"
        "mov r1, #0\n\t"
        "mov r2, #0\n\t"
        "bl sub_8008890\n\t"
        "add r5, #0xd\n\t"
        "ldr r6, [sp, #0x14]\n\t"
        "ldr r3, [sp, #0xc]\n\t"
        "ldr r0, [r3, #8]\n\t"
        "mov r1, sp\n\t"
        "mov r2, #0xa\n\t"
        "bl itoa\n\t"
        "ldr r0, [sp, #8]\n\t"
        "cmp r0, #0\n\t"
        "beq 12f\n\t"
        "ldr r2, [r4]\n\t"
        "ldr r0, [r7, #4]\n\t"
        "asr r0, r0, #2\n\t"
        "mov r1, #1\n\t"
        "and r0, r1\n\t"
        "mov r1, #2\n\t"
        "cmp r0, #0\n\t"
        "beq 9f\n\t"
        "mov r1, #1\n\t"
    "9:\n\t"
        "add r0, r2, #0\n\t"
        "bl sub_8028A30\n\t"
        "b 13f\n\t"
        ".align 2, 0\n\t"
    "10: .4byte gUnknown_030012DC\n\t"
    "11:\n\t"
        "mov r0, #0x25\n\t"
        "strb r0, [r1]\n\t"
        "add r0, r3, #1\n\t"
        "add r0, sp\n\t"
        "strb r2, [r0]\n\t"
        "b 15f\n\t"
    "12:\n\t"
        "ldr r0, [r4]\n\t"
        "mov r1, #0\n\t"
        "bl sub_8028A30\n\t"
    "13:\n\t"
        "ldr r0, 17f\n\t"
        "ldr r2, [r0]\n\t"
        "mov r1, #0x88\n\t"
        "lsl r1, r1, #1\n\t"
        "add r0, r2, r1\n\t"
        "str r5, [r0]\n\t"
        "mov r3, #0x8a\n\t"
        "lsl r3, r3, #1\n\t"
        "add r0, r2, r3\n\t"
        "str r6, [r0]\n\t"
        "add r1, #0x20\n\t"
        "add r0, r2, r1\n\t"
        "ldr r1, [r0]\n\t"
        "mov r3, #0x20\n\t"
        "ldrsh r0, [r1, r3]\n\t"
        "add r0, r2, r0\n\t"
        "ldr r2, [r1, #0x24]\n\t"
        "mov r1, sp\n\t"
        "bl sub_803AD80\n\t"
        "ldr r1, [sp, #0xc]\n\t"
        "ldr r0, [r1]\n\t"
        "mov r1, sp\n\t"
        "mov r2, #0xa\n\t"
        "bl itoa\n\t"
        "mov r3, #0\n\t"
        "mov r6, sl\n\t"
        "sub r6, #2\n\t"
    "14:\n\t"
        "mov r2, sp\n\t"
        "add r1, r2, r3\n\t"
        "ldrb r2, [r1]\n\t"
        "cmp r2, #0\n\t"
        "beq 11b\n\t"
        "add r3, #1\n\t"
        "cmp r3, #6\n\t"
        "ble 14b\n\t"
    "15:\n\t"
        "ldr r4, 18f\n\t"
        "ldr r0, [r4]\n\t"
        "mov r3, #0x98\n\t"
        "lsl r3, r3, #1\n\t"
        "add r1, r0, r3\n\t"
        "ldr r2, [r1]\n\t"
        "mov r3, #0x10\n\t"
        "ldrsh r1, [r2, r3]\n\t"
        "add r0, r0, r1\n\t"
        "ldr r2, [r2, #0x14]\n\t"
        "mov r1, sp\n\t"
        "bl sub_803AD80\n\t"
        "add r5, r0, #0\n\t"
        "ldr r0, [sp, #8]\n\t"
        "cmp r0, #0\n\t"
        "beq 19f\n\t"
        "ldr r2, [r4]\n\t"
        "ldr r0, [r7, #4]\n\t"
        "asr r0, r0, #2\n\t"
        "mov r1, #1\n\t"
        "and r0, r1\n\t"
        "mov r1, #2\n\t"
        "cmp r0, #0\n\t"
        "beq 16f\n\t"
        "mov r1, #1\n\t"
    "16:\n\t"
        "add r0, r2, #0\n\t"
        "bl sub_8028A30\n\t"
        "b 20f\n\t"
        ".align 2, 0\n\t"
    "17: .4byte gUnknown_030012DC\n\t"
    "18: .4byte gUnknown_030012E0\n\t"
    "19:\n\t"
        "ldr r0, [r4]\n\t"
        "mov r1, #0\n\t"
        "bl sub_8028A30\n\t"
    "20:\n\t"
        "mov r2, r8\n\t"
        "sub r1, r2, r5\n\t"
        "ldr r0, 21f\n\t"
        "ldr r2, [r0]\n\t"
        "add r1, #0x1f\n\t"
        "mov r3, #0x88\n\t"
        "lsl r3, r3, #1\n\t"
        "add r0, r2, r3\n\t"
        "str r1, [r0]\n\t"
        "mov r1, #0x8a\n\t"
        "lsl r1, r1, #1\n\t"
        "add r0, r2, r1\n\t"
        "str r6, [r0]\n\t"
        "add r3, #0x20\n\t"
        "add r0, r2, r3\n\t"
        "ldr r1, [r0]\n\t"
        "mov r3, #0x20\n\t"
        "ldrsh r0, [r1, r3]\n\t"
        "add r0, r2, r0\n\t"
        "ldr r2, [r1, #0x24]\n\t"
        "mov r1, sp\n\t"
        "bl sub_803AD80\n\t"
        "add sp, #0x1c\n\t"
        "pop {r3, r4, r5}\n\t"
        "mov r8, r3\n\t"
        "mov sb, r4\n\t"
        "mov sl, r5\n\t"
        "pop {r4, r5, r6, r7}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
        ".align 2, 0\n\t"
    "21: .4byte gUnknown_030012E0\n\t"
    );
}

/* Per docs/rom_map.md's "narrowed down which screen overlay_ui is"
 * section: one of 4 settings rows, `handle`/`selectedIndex` from the
 * 6-wrapper-caller family (sub_8004AA4 etc.,
 * src/graphics/settings_menu3.c). When `sub_8002CE8(handle, i)`
 * reports row `i` selected, draws a highlighted numeric glyph
 * (label 0x25) centered at the row's fixed position; otherwise draws
 * the row's normal label pair via sub_8003F30 (above in this file),
 * flagged if `selectedIndex == i`. The four rows' fixed anchors: row 0
 * = (0x43,0x2d)/labels(0x26,0x21)/idx 1; row 1 = (0x43,0x5f)/
 * (0x26,0x53)/idx 2; row 2 = (0xa3,0x2d)/(0x86,0x21)/idx 3; row 3 =
 * (0xa3,0x5f)/(0x86,0x53)/idx 4.
 *
 * Written as NAKED asm, not plain C: a full C reconstruction (kept in
 * git history) used a small table + loop, semantically faithful but
 * unable to reproduce the ROM's 4x-unrolled per-occurrence register
 * choices - same "last mile" gcc-2.9 scratch-register nondeterminism
 * documented in this file's header comment above, compounded by the unrolling. Every
 * instruction below is confirmed byte-identical to the ROM - full
 * NAKED transcription, like this project's other hard-compiler-
 * limitation cases (see `src/util/printf_util.c`'s `sub_8000CBC` for
 * the established pattern), is more honest than continuing to chase
 * four independent sets of per-occurrence register choices through
 * plain C. */
NAKED void sub_80041BC(struct pause_options_screen *self, void *handle, s32 selectedIndex)
{
    asm(
        "push {r4, r5, r6, r7, lr}\n\t"
        "mov r7, sb\n\t"
        "mov r6, r8\n\t"
        "push {r6, r7}\n\t"
        "sub sp, #4\n\t"
        "mov r8, r0\n\t"
        "mov sb, r1\n\t"
        "add r7, r2, #0\n\t"
        "mov r0, sb\n\t"
        "mov r1, #0\n\t"
        "bl sub_8002CE8\n\t"
        "lsl r0, r0, #0x18\n\t"
        "cmp r0, #0\n\t"
        "beq 7f\n\t"
        "mov r0, #0\n\t"
        "cmp r7, #0\n\t"
        "bne 1f\n\t"
        "mov r0, #1\n\t"
    "1:\n\t"
        "cmp r0, #0\n\t"
        "beq 4f\n\t"
        "ldr r0, 3f\n\t"
        "ldr r2, [r0]\n\t"
        "mov r1, r8\n\t"
        "ldr r0, [r1, #4]\n\t"
        "asr r0, r0, #2\n\t"
        "mov r1, #1\n\t"
        "and r0, r1\n\t"
        "mov r1, #2\n\t"
        "cmp r0, #0\n\t"
        "beq 2f\n\t"
        "mov r1, #1\n\t"
    "2:\n\t"
        "add r0, r2, #0\n\t"
        "bl sub_8028A30\n\t"
        "b 5f\n\t"
        ".align 2, 0\n\t"
    "3: .4byte gUnknown_030012DC\n\t"
    "4:\n\t"
        "ldr r0, 6f\n\t"
        "ldr r0, [r0]\n\t"
        "mov r1, #0\n\t"
        "bl sub_8028A30\n\t"
    "5:\n\t"
        "ldr r6, 6f\n\t"
        "ldr r4, [r6]\n\t"
        "mov r3, #0x98\n\t"
        "lsl r3, r3, #1\n\t"
        "add r0, r4, r3\n\t"
        "ldr r0, [r0]\n\t"
        "add r5, r0, #0\n\t"
        "add r5, #0x10\n\t"
        "mov r1, #0x10\n\t"
        "ldrsh r0, [r0, r1]\n\t"
        "add r4, r4, r0\n\t"
        "mov r0, #0x25\n\t"
        "bl sub_8026F38\n\t"
        "add r1, r0, #0\n\t"
        "ldr r2, [r5, #4]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_803AD80\n\t"
        "lsr r1, r0, #0x1f\n\t"
        "add r0, r0, r1\n\t"
        "asr r0, r0, #1\n\t"
        "mov r1, #0x43\n\t"
        "sub r1, r1, r0\n\t"
        "ldr r2, [r6]\n\t"
        "mov r3, #0x88\n\t"
        "lsl r3, r3, #1\n\t"
        "add r0, r2, r3\n\t"
        "str r1, [r0]\n\t"
        "mov r0, #0x8a\n\t"
        "lsl r0, r0, #1\n\t"
        "add r1, r2, r0\n\t"
        "mov r0, #0x2d\n\t"
        "str r0, [r1]\n\t"
        "mov r1, #0x98\n\t"
        "lsl r1, r1, #1\n\t"
        "add r0, r2, r1\n\t"
        "ldr r0, [r0]\n\t"
        "add r5, r0, #0\n\t"
        "add r5, #0x20\n\t"
        "mov r3, #0x20\n\t"
        "ldrsh r4, [r0, r3]\n\t"
        "add r4, r2, r4\n\t"
        "mov r0, #0x25\n\t"
        "bl sub_8026F38\n\t"
        "add r1, r0, #0\n\t"
        "ldr r2, [r5, #4]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_803AD80\n\t"
        "b 9f\n\t"
        ".align 2, 0\n\t"
    "6: .4byte gUnknown_030012DC\n\t"
    "7:\n\t"
        "mov r1, #0\n\t"
        "cmp r7, #0\n\t"
        "bne 8f\n\t"
        "mov r1, #1\n\t"
    "8:\n\t"
        "mov r0, sp\n\t"
        "strb r1, [r0]\n\t"
        "mov r0, r8\n\t"
        "mov r1, #0x26\n\t"
        "mov r2, #0x21\n\t"
        "mov r3, #1\n\t"
        "bl sub_8003F30\n\t"
    "9:\n\t"
        "mov r0, sb\n\t"
        "mov r1, #1\n\t"
        "bl sub_8002CE8\n\t"
        "lsl r0, r0, #0x18\n\t"
        "cmp r0, #0\n\t"
        "beq 16f\n\t"
        "mov r0, #0\n\t"
        "cmp r7, #1\n\t"
        "bne 10f\n\t"
        "mov r0, #1\n\t"
    "10:\n\t"
        "cmp r0, #0\n\t"
        "beq 13f\n\t"
        "ldr r0, 12f\n\t"
        "ldr r2, [r0]\n\t"
        "mov r1, r8\n\t"
        "ldr r0, [r1, #4]\n\t"
        "asr r0, r0, #2\n\t"
        "mov r1, #1\n\t"
        "and r0, r1\n\t"
        "mov r1, #2\n\t"
        "cmp r0, #0\n\t"
        "beq 11f\n\t"
        "mov r1, #1\n\t"
    "11:\n\t"
        "add r0, r2, #0\n\t"
        "bl sub_8028A30\n\t"
        "b 14f\n\t"
        ".align 2, 0\n\t"
    "12: .4byte gUnknown_030012DC\n\t"
    "13:\n\t"
        "ldr r0, 15f\n\t"
        "ldr r0, [r0]\n\t"
        "mov r1, #0\n\t"
        "bl sub_8028A30\n\t"
    "14:\n\t"
        "ldr r6, 15f\n\t"
        "ldr r4, [r6]\n\t"
        "mov r3, #0x98\n\t"
        "lsl r3, r3, #1\n\t"
        "add r0, r4, r3\n\t"
        "ldr r0, [r0]\n\t"
        "add r5, r0, #0\n\t"
        "add r5, #0x10\n\t"
        "mov r1, #0x10\n\t"
        "ldrsh r0, [r0, r1]\n\t"
        "add r4, r4, r0\n\t"
        "mov r0, #0x25\n\t"
        "bl sub_8026F38\n\t"
        "add r1, r0, #0\n\t"
        "ldr r2, [r5, #4]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_803AD80\n\t"
        "lsr r1, r0, #0x1f\n\t"
        "add r0, r0, r1\n\t"
        "asr r0, r0, #1\n\t"
        "mov r1, #0x43\n\t"
        "sub r1, r1, r0\n\t"
        "ldr r2, [r6]\n\t"
        "mov r3, #0x88\n\t"
        "lsl r3, r3, #1\n\t"
        "add r0, r2, r3\n\t"
        "str r1, [r0]\n\t"
        "mov r0, #0x8a\n\t"
        "lsl r0, r0, #1\n\t"
        "add r1, r2, r0\n\t"
        "mov r0, #0x5f\n\t"
        "str r0, [r1]\n\t"
        "mov r1, #0x98\n\t"
        "lsl r1, r1, #1\n\t"
        "add r0, r2, r1\n\t"
        "ldr r0, [r0]\n\t"
        "add r5, r0, #0\n\t"
        "add r5, #0x20\n\t"
        "mov r3, #0x20\n\t"
        "ldrsh r4, [r0, r3]\n\t"
        "add r4, r2, r4\n\t"
        "mov r0, #0x25\n\t"
        "bl sub_8026F38\n\t"
        "add r1, r0, #0\n\t"
        "ldr r2, [r5, #4]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_803AD80\n\t"
        "b 18f\n\t"
        ".align 2, 0\n\t"
    "15: .4byte gUnknown_030012DC\n\t"
    "16:\n\t"
        "mov r1, #0\n\t"
        "cmp r7, #1\n\t"
        "bne 17f\n\t"
        "mov r1, #1\n\t"
    "17:\n\t"
        "mov r0, sp\n\t"
        "strb r1, [r0]\n\t"
        "mov r0, r8\n\t"
        "mov r1, #0x26\n\t"
        "mov r2, #0x53\n\t"
        "mov r3, #2\n\t"
        "bl sub_8003F30\n\t"
    "18:\n\t"
        "mov r0, sb\n\t"
        "mov r1, #2\n\t"
        "bl sub_8002CE8\n\t"
        "lsl r0, r0, #0x18\n\t"
        "cmp r0, #0\n\t"
        "beq 25f\n\t"
        "mov r0, #0\n\t"
        "cmp r7, #2\n\t"
        "bne 19f\n\t"
        "mov r0, #1\n\t"
    "19:\n\t"
        "cmp r0, #0\n\t"
        "beq 22f\n\t"
        "ldr r0, 21f\n\t"
        "ldr r2, [r0]\n\t"
        "mov r1, r8\n\t"
        "ldr r0, [r1, #4]\n\t"
        "asr r0, r0, #2\n\t"
        "mov r1, #1\n\t"
        "and r0, r1\n\t"
        "mov r1, #2\n\t"
        "cmp r0, #0\n\t"
        "beq 20f\n\t"
        "mov r1, #1\n\t"
    "20:\n\t"
        "add r0, r2, #0\n\t"
        "bl sub_8028A30\n\t"
        "b 23f\n\t"
        ".align 2, 0\n\t"
    "21: .4byte gUnknown_030012DC\n\t"
    "22:\n\t"
        "ldr r0, 24f\n\t"
        "ldr r0, [r0]\n\t"
        "mov r1, #0\n\t"
        "bl sub_8028A30\n\t"
    "23:\n\t"
        "ldr r6, 24f\n\t"
        "ldr r4, [r6]\n\t"
        "mov r3, #0x98\n\t"
        "lsl r3, r3, #1\n\t"
        "add r0, r4, r3\n\t"
        "ldr r0, [r0]\n\t"
        "add r5, r0, #0\n\t"
        "add r5, #0x10\n\t"
        "mov r1, #0x10\n\t"
        "ldrsh r0, [r0, r1]\n\t"
        "add r4, r4, r0\n\t"
        "mov r0, #0x25\n\t"
        "bl sub_8026F38\n\t"
        "add r1, r0, #0\n\t"
        "ldr r2, [r5, #4]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_803AD80\n\t"
        "lsr r1, r0, #0x1f\n\t"
        "add r0, r0, r1\n\t"
        "asr r0, r0, #1\n\t"
        "mov r1, #0xa3\n\t"
        "sub r1, r1, r0\n\t"
        "ldr r2, [r6]\n\t"
        "mov r3, #0x88\n\t"
        "lsl r3, r3, #1\n\t"
        "add r0, r2, r3\n\t"
        "str r1, [r0]\n\t"
        "mov r0, #0x8a\n\t"
        "lsl r0, r0, #1\n\t"
        "add r1, r2, r0\n\t"
        "mov r0, #0x2d\n\t"
        "str r0, [r1]\n\t"
        "mov r1, #0x98\n\t"
        "lsl r1, r1, #1\n\t"
        "add r0, r2, r1\n\t"
        "ldr r0, [r0]\n\t"
        "add r5, r0, #0\n\t"
        "add r5, #0x20\n\t"
        "mov r3, #0x20\n\t"
        "ldrsh r4, [r0, r3]\n\t"
        "add r4, r2, r4\n\t"
        "mov r0, #0x25\n\t"
        "bl sub_8026F38\n\t"
        "add r1, r0, #0\n\t"
        "ldr r2, [r5, #4]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_803AD80\n\t"
        "b 27f\n\t"
        ".align 2, 0\n\t"
    "24: .4byte gUnknown_030012DC\n\t"
    "25:\n\t"
        "mov r1, #0\n\t"
        "cmp r7, #2\n\t"
        "bne 26f\n\t"
        "mov r1, #1\n\t"
    "26:\n\t"
        "mov r0, sp\n\t"
        "strb r1, [r0]\n\t"
        "mov r0, r8\n\t"
        "mov r1, #0x86\n\t"
        "mov r2, #0x21\n\t"
        "mov r3, #3\n\t"
        "bl sub_8003F30\n\t"
    "27:\n\t"
        "mov r0, sb\n\t"
        "mov r1, #3\n\t"
        "bl sub_8002CE8\n\t"
        "lsl r0, r0, #0x18\n\t"
        "cmp r0, #0\n\t"
        "beq 34f\n\t"
        "mov r0, #0\n\t"
        "cmp r7, #3\n\t"
        "bne 28f\n\t"
        "mov r0, #1\n\t"
    "28:\n\t"
        "cmp r0, #0\n\t"
        "beq 31f\n\t"
        "ldr r0, 30f\n\t"
        "ldr r2, [r0]\n\t"
        "mov r1, r8\n\t"
        "ldr r0, [r1, #4]\n\t"
        "asr r0, r0, #2\n\t"
        "mov r1, #1\n\t"
        "and r0, r1\n\t"
        "mov r1, #2\n\t"
        "cmp r0, #0\n\t"
        "beq 29f\n\t"
        "mov r1, #1\n\t"
    "29:\n\t"
        "add r0, r2, #0\n\t"
        "bl sub_8028A30\n\t"
        "b 32f\n\t"
        ".align 2, 0\n\t"
    "30: .4byte gUnknown_030012DC\n\t"
    "31:\n\t"
        "ldr r0, 33f\n\t"
        "ldr r0, [r0]\n\t"
        "mov r1, #0\n\t"
        "bl sub_8028A30\n\t"
    "32:\n\t"
        "ldr r6, 33f\n\t"
        "ldr r4, [r6]\n\t"
        "mov r3, #0x98\n\t"
        "lsl r3, r3, #1\n\t"
        "add r0, r4, r3\n\t"
        "ldr r0, [r0]\n\t"
        "add r5, r0, #0\n\t"
        "add r5, #0x10\n\t"
        "mov r1, #0x10\n\t"
        "ldrsh r0, [r0, r1]\n\t"
        "add r4, r4, r0\n\t"
        "mov r0, #0x25\n\t"
        "bl sub_8026F38\n\t"
        "add r1, r0, #0\n\t"
        "ldr r2, [r5, #4]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_803AD80\n\t"
        "lsr r1, r0, #0x1f\n\t"
        "add r0, r0, r1\n\t"
        "asr r0, r0, #1\n\t"
        "mov r1, #0xa3\n\t"
        "sub r1, r1, r0\n\t"
        "ldr r2, [r6]\n\t"
        "mov r3, #0x88\n\t"
        "lsl r3, r3, #1\n\t"
        "add r0, r2, r3\n\t"
        "str r1, [r0]\n\t"
        "mov r0, #0x8a\n\t"
        "lsl r0, r0, #1\n\t"
        "add r1, r2, r0\n\t"
        "mov r0, #0x5f\n\t"
        "str r0, [r1]\n\t"
        "mov r1, #0x98\n\t"
        "lsl r1, r1, #1\n\t"
        "add r0, r2, r1\n\t"
        "ldr r0, [r0]\n\t"
        "add r5, r0, #0\n\t"
        "add r5, #0x20\n\t"
        "mov r3, #0x20\n\t"
        "ldrsh r4, [r0, r3]\n\t"
        "add r4, r2, r4\n\t"
        "mov r0, #0x25\n\t"
        "bl sub_8026F38\n\t"
        "add r1, r0, #0\n\t"
        "ldr r2, [r5, #4]\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_803AD80\n\t"
        "b 36f\n\t"
        ".align 2, 0\n\t"
    "33: .4byte gUnknown_030012DC\n\t"
    "34:\n\t"
        "mov r1, #0\n\t"
        "cmp r7, #3\n\t"
        "bne 35f\n\t"
        "mov r1, #1\n\t"
    "35:\n\t"
        "mov r0, sp\n\t"
        "strb r1, [r0]\n\t"
        "mov r0, r8\n\t"
        "mov r1, #0x86\n\t"
        "mov r2, #0x53\n\t"
        "mov r3, #4\n\t"
        "bl sub_8003F30\n\t"
    "36:\n\t"
        "add sp, #4\n\t"
        "pop {r3, r4}\n\t"
        "mov r8, r3\n\t"
        "mov sb, r4\n\t"
        "pop {r4, r5, r6, r7}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
        ".align 2, 0\n\t"
    );
}
