#include "core.h"

/* GAX2 per-channel note-trigger routine (issue #68's last raw pair,
 * docs/status/audio.md), called by the matched-but-NAKED
 * `sub_80395A4`/`sub_803A158` (both `self+0xc == 0` tail calls) as
 * `sub_8039B44(self, info, arg1, arg2, info->0->0x18, flag)`. `self`
 * (r6) is the channel object shared with the rest of this cluster
 * (`sub_8039818`/`sub_8039FFC`/`sub_803A104`/... - `self+0x2a` is the
 * same signed-halfword "current note" field `sub_803A104` arms with the
 * `0x8AD0` "no note" sentinel); `info` (r4) is the shared handler
 * object.
 *
 * Bails out early (returns 0) when `self+0x3c` (the bound instrument
 * table pointer) is NULL, when `self+0x2a` still holds the `0x8AD0`
 * "no note" sentinel, or when `self+0x10` (voice-table row index) is
 * out of the 0-3 range, or when the instrument row's own flag byte
 * (`instrument[self+0x10+1]`) is 0. Otherwise it derives a base pitch
 * from `self+0x2a`/`+0x2e`/`+0x21`/`+0x26`/`+0x11` plus the instrument
 * row's signed transpose byte, clamps it into `gStaticData_085A62DC`'s
 * period-lookup table (capped at `0xEF3`), derives a per-voice volume
 * by chaining `self+0x16`/`+0x17`/`+0x15`/`+0x18`/`info->0->0x18->8`
 * multiplies (each `0xff`-sentineled to "skip"), calls `sub_8037ECC`
 * (the 64-bit-division-backed pitch/period helper, `src/util/
 * math_div64_util.c`) on the result, then builds a stack work-item and
 * forwards it through `sub_800014C`. The remainder (from ROM label
 * `0x08039CDE` on, i.e. `sub_8039E50`'s half of this physical function)
 * loops the instrument's per-row envelope/pan table
 * (`gStaticData_0803A818`-relative row math against `self+0x3c`) while
 * `self+0x11` (a signed priority-looking byte) stays positive, updating
 * `gUnknown_03001630->0x44`'s pan/volume output halfword each
 * iteration via one of several `self+0xd`/`self+0x12`/`self+0x13`-gated
 * paths, calling `sub_8037F3C` once per row when `self+0xd` is set, and
 * finally re-arms the `0x8AD0` "no note" sentinel into `self+0x2a` (and
 * clears `self+0x2c`) once the loop's row count (`self+0x4`->`+0x4`,
 * a halfword) is exhausted, returning 1. Voice/instrument object shape
 * isn't modeled yet (same situation as the rest of this GAX2 cluster) -
 * kept as raw offsets throughout, matching the neighboring functions in
 * this directory.
 *
 * Written as NAKED asm, not plain C, for a structural reason rather
 * than a register-allocation one: the ROM's own compiler split this
 * single logical function into two disassembly labels,
 * `sub_8039B44`/`sub_8039E50`, glued together by the same manual
 * return-address-trampoline idiom already documented for
 * `sub_803A278`/`sub_803A2C8`/`sub_803A324`/`sub_803A5A8`
 * (`gax_unknownc_play.c`) - `mov r2, pc; adds r2, #5; mov lr, r2;
 * bx r1` computes a Thumb-tagged return address by hand and jumps
 * through `r1` (`gUnknown_03001630`'s own `+0x44` function-pointer
 * slot, an interworked callback) instead of a normal `bl`, since
 * ARMv4T Thumb has no `blx reg`. That trampoline's return address
 * lands exactly at `sub_8039E50`'s first instruction - a `nop`
 * (`mov r8, r8`) alignment pad, the same tell already seen at
 * `sub_803A2C8`'s landing into `sub_803A318` - so the two ROM labels
 * are one physical function, not two independently callable ones; this
 * idiom itself is not expressible in portable C at all, regardless of
 * register pressure, so no real-C attempt was made for the trampoline
 * sequence. `sub_8039E50` keeps its own `.thumb_func`/`.global` label
 * pair purely so its ROM address still carries its name for anyone
 * disassembling the object (it is never itself called from anywhere in
 * the ROM - checked every `asm/*.s`/`expected/*.s`/`src/*` file for a
 * `bl sub_8039E50`/`.4byte sub_8039E50` reference, none exists), not as
 * a second callable C function - matching this project's established
 * NAKED-fused-pair policy (docs/status/audio.md's "Parked - NAKED asm
 * transcription(s)" section). Mechanical, byte-verified transcription
 * of the ROM's own instructions (translated from the disassembler's
 * unified syntax to this project's established NAKED plain/divided
 * syntax, local labels renumbered per
 * docs/matching/issue-4-sio-settings-sync.md's convention, using a
 * scratch Python script rather than by hand given this function's
 * size - ~380 real instructions - to avoid transcription-typo risk the
 * same way that convention's `sub_8002114` did), not an inferred
 * control-flow guess. This is PARKED, not matched, per this project's
 * NAKED-transcription policy: byte-correct but not real decompiled C. */
NAKED u32 sub_8039B44(void *self, void *info, u32 arg1, u32 arg2, u32 arg5, u32 flag)
{
    asm(
        "push {r4, r5, r6, r7, lr}\n\t"
        "mov r7, sl\n\t"
        "mov r6, sb\n\t"
        "mov r5, r8\n\t"
        "push {r5, r6, r7}\n\t"
        "sub sp, #0x5c\n\t"
        "add r6, r0, #0\n\t"
        "add r4, r1, #0\n\t"
        "str r2, [sp, #0x50]\n\t"
        "ldr r0, [sp, #0x80]\n\t"
        "lsl r0, r0, #0x18\n\t"
        "lsr r5, r0, #0x18\n\t"
        "ldr r3, [r6, #0x3c]\n\t"
        "cmp r3, #0\n\t"
        "beq 1f\n\t"
        "mov r0, #0x2a\n\t"
        "ldrsh r1, [r6, r0]\n\t"
        "ldr r0, 2f\n\t"
        "cmp r1, r0\n\t"
        "beq 1f\n\t"
        "ldrb r0, [r6, #0x10]\n\t"
        "cmp r0, #3\n\t"
        "bhi 1f\n\t"
        "ldrb r2, [r6, #0x10]\n\t"
        "add r0, r3, #1\n\t"
        "add r0, r0, r2\n\t"
        "ldrb r0, [r0]\n\t"
        "lsl r0, r0, #3\n\t"
        "ldr r1, [sp, #0x7c]\n\t"
        "ldr r1, [r1, #0x14]\n\t"
        "add r1, r1, r0\n\t"
        "str r1, [sp, #0x54]\n\t"
        "ldr r0, [r1]\n\t"
        "mov sb, r2\n\t"
        "cmp r0, #0\n\t"
        "bne 3f\n\t"
        "1:\n\t"
        "mov r0, #0\n\t"
        "b 57f\n\t"
        ".align 2, 0\n\t"
        "2: .4byte 0xFFFF8AD0\n\t"
        "3:\n\t"
        "mov r1, #0x2a\n\t"
        "ldrsh r0, [r6, r1]\n\t"
        "mov r2, #0x2e\n\t"
        "ldrsh r1, [r6, r2]\n\t"
        "add r2, r0, r1\n\t"
        "add r0, r6, #0\n\t"
        "add r0, #0x21\n\t"
        "ldrb r0, [r0]\n\t"
        "cmp r0, #0\n\t"
        "bne 4f\n\t"
        "mov r3, #0x26\n\t"
        "ldrsh r0, [r6, r3]\n\t"
        "add r2, r2, r0\n\t"
        "cmp r5, #0\n\t"
        "bne 4f\n\t"
        "ldr r1, [r6]\n\t"
        "mov r3, #0x14\n\t"
        "ldrsh r0, [r4, r3]\n\t"
        "ldr r1, [r1, #0x18]\n\t"
        "lsl r0, r0, #2\n\t"
        "add r0, r0, r1\n\t"
        "ldrb r0, [r0, #2]\n\t"
        "lsl r0, r0, #0x18\n\t"
        "asr r0, r0, #0x18\n\t"
        "lsl r0, r0, #5\n\t"
        "add r2, r2, r0\n\t"
        "4:\n\t"
        "ldr r0, [r6, #0x3c]\n\t"
        "mov r3, sb\n\t"
        "lsl r1, r3, #3\n\t"
        "sub r1, r1, r3\n\t"
        "lsl r1, r1, #2\n\t"
        "add r1, r0, r1\n\t"
        "mov r3, #0x26\n\t"
        "ldrsh r1, [r1, r3]\n\t"
        "ldr r3, 13f\n\t"
        "add r1, r2, r1\n\t"
        "ldr r2, 14f\n\t"
        "mov r8, r0\n\t"
        "cmp r1, r2\n\t"
        "bls 5f\n\t"
        "add r1, r2, #0\n\t"
        "5:\n\t"
        "lsl r0, r1, #2\n\t"
        "add r0, r0, r3\n\t"
        "ldr r1, [r0]\n\t"
        "ldrb r0, [r6, #0x16]\n\t"
        "mov r7, #0x80\n\t"
        "lsl r7, r7, #1\n\t"
        "cmp r0, #0xff\n\t"
        "beq 6f\n\t"
        "add r7, r0, #0\n\t"
        "6:\n\t"
        "ldrb r0, [r6, #0x17]\n\t"
        "cmp r0, #0xff\n\t"
        "beq 7f\n\t"
        "mul r0, r7, r0\n\t"
        "lsr r7, r0, #8\n\t"
        "7:\n\t"
        "ldrb r0, [r6, #0x15]\n\t"
        "cmp r0, #0xff\n\t"
        "beq 8f\n\t"
        "mul r0, r7, r0\n\t"
        "lsr r7, r0, #8\n\t"
        "8:\n\t"
        "ldrb r0, [r6, #0x18]\n\t"
        "cmp r0, #0xff\n\t"
        "beq 9f\n\t"
        "mul r0, r7, r0\n\t"
        "lsr r7, r0, #8\n\t"
        "9:\n\t"
        "ldrb r0, [r4, #0x1f]\n\t"
        "cmp r0, #0xff\n\t"
        "beq 10f\n\t"
        "mul r0, r7, r0\n\t"
        "lsr r7, r0, #8\n\t"
        "10:\n\t"
        "cmp r5, #0\n\t"
        "bne 11f\n\t"
        "ldr r0, [r4]\n\t"
        "ldr r0, [r0, #0x18]\n\t"
        "ldrh r0, [r0, #8]\n\t"
        "mul r0, r7, r0\n\t"
        "lsr r7, r0, #8\n\t"
        "11:\n\t"
        "add r4, r1, #0\n\t"
        "asr r5, r1, #0x1f\n\t"
        "ldr r0, 15f\n\t"
        "ldr r2, [r0]\n\t"
        "ldr r3, [r0, #4]\n\t"
        "add r1, r5, #0\n\t"
        "add r0, r4, #0\n\t"
        "bl sub_8037ECC\n\t"
        "add r4, r1, #0\n\t"
        "mov sl, r4\n\t"
        "ldr r4, [sp, #0x54]\n\t"
        "ldr r3, [r4, #4]\n\t"
        "mov r0, #0\n\t"
        "str r0, [sp, #0x58]\n\t"
        "mov r1, sb\n\t"
        "lsl r0, r1, #3\n\t"
        "sub r0, r0, r1\n\t"
        "lsl r2, r0, #2\n\t"
        "mov r4, r8\n\t"
        "add r0, r4, r2\n\t"
        "ldrb r0, [r0, #0xc]\n\t"
        "cmp r0, #0\n\t"
        "bne 12f\n\t"
        "mov r1, r8\n\t"
        "add r1, #0x14\n\t"
        "add r1, r1, r2\n\t"
        "mov r0, r8\n\t"
        "add r0, #0x18\n\t"
        "add r0, r0, r2\n\t"
        "ldr r1, [r1]\n\t"
        "ldr r0, [r0]\n\t"
        "cmp r1, r0\n\t"
        "bge 12f\n\t"
        "mov r0, #1\n\t"
        "str r0, [sp, #0x58]\n\t"
        "12:\n\t"
        "ldr r0, [r6, #4]\n\t"
        "ldrh r2, [r0, #4]\n\t"
        "ldr r1, [sp, #0x54]\n\t"
        "ldr r0, [r1]\n\t"
        "ldr r1, [r6, #0x44]\n\t"
        "mov r4, sp\n\t"
        "str r0, [sp, #0x28]\n\t"
        "ldr r0, [sp, #0x50]\n\t"
        "str r0, [sp, #0x2c]\n\t"
        "str r1, [sp, #0x30]\n\t"
        "lsl r0, r3, #0xb\n\t"
        "str r0, [sp, #0x34]\n\t"
        "str r2, [sp, #0x38]\n\t"
        "mov r0, #0\n\t"
        "str r0, [sp, #0x3c]\n\t"
        "str r7, [sp, #0x40]\n\t"
        "mov r1, sl\n\t"
        "str r1, [sp, #0x44]\n\t"
        "str r0, [sp, #0x48]\n\t"
        "ldrb r0, [r6, #0x12]\n\t"
        "cmp r0, #0\n\t"
        "beq 16f\n\t"
        "ldr r1, [r6, #0x3c]\n\t"
        "ldrb r2, [r6, #0x10]\n\t"
        "lsl r0, r2, #3\n\t"
        "sub r0, r0, r2\n\t"
        "lsl r0, r0, #2\n\t"
        "add r1, #0x1c\n\t"
        "add r1, r1, r0\n\t"
        "ldr r0, [r1]\n\t"
        "lsl r0, r0, #0xb\n\t"
        "b 17f\n\t"
        ".align 2, 0\n\t"
        "13: .4byte gStaticData_085A62DC\n\t"
        "14: .4byte 0x00000EF3\n\t"
        "15: .4byte gUnknown_03001618\n\t"
        "16:\n\t"
        "mov r0, #0\n\t"
        "17:\n\t"
        "str r0, [sp, #0x4c]\n\t"
        "add r1, sp, #0x28\n\t"
        "add r0, r4, #0\n\t"
        "mov r2, #0x28\n\t"
        "bl sub_800014C\n\t"
        "ldr r1, [r6, #4]\n\t"
        "ldr r0, [sp, #0x14]\n\t"
        "ldrh r1, [r1, #4]\n\t"
        "cmp r0, r1\n\t"
        "blo 18f\n\t"
        "b 56f\n\t"
        "18:\n\t"
        "ldr r0, 20f\n\t"
        "ldr r7, 21f\n\t"
        "sub r0, r0, r7\n\t"
        "add r5, r0, #2\n\t"
        "19:\n\t"
        "mov r0, #0x11\n\t"
        "ldrsb r0, [r6, r0]\n\t"
        "cmp r0, #0\n\t"
        "ble 35f\n\t"
        "ldr r2, [sp, #0x58]\n\t"
        "cmp r2, #0\n\t"
        "beq 22f\n\t"
        "ldr r2, [r6, #0x3c]\n\t"
        "ldrb r1, [r6, #0x10]\n\t"
        "lsl r0, r1, #3\n\t"
        "sub r0, r0, r1\n\t"
        "lsl r0, r0, #2\n\t"
        "add r2, #0x18\n\t"
        "add r2, r2, r0\n\t"
        "ldr r0, [r2]\n\t"
        "b 24f\n\t"
        ".align 2, 0\n\t"
        "20: .4byte gStaticData_0803A874\n\t"
        "21: .4byte gStaticData_0803A818\n\t"
        "22:\n\t"
        "ldrb r0, [r6, #0x12]\n\t"
        "cmp r0, #0\n\t"
        "beq 23f\n\t"
        "ldr r2, [r6, #0x3c]\n\t"
        "ldrb r1, [r6, #0x10]\n\t"
        "lsl r0, r1, #3\n\t"
        "sub r0, r0, r1\n\t"
        "lsl r0, r0, #2\n\t"
        "add r2, #0x1c\n\t"
        "add r2, r2, r0\n\t"
        "ldr r0, [r6, #0x48]\n\t"
        "ldr r1, [r2]\n\t"
        "add r0, r0, r1\n\t"
        "b 24f\n\t"
        "23:\n\t"
        "ldr r3, [sp, #0x54]\n\t"
        "ldr r0, [r3, #4]\n\t"
        "24:\n\t"
        "lsl r0, r0, #0xb\n\t"
        "str r0, [sp, #0xc]\n\t"
        "ldrb r0, [r6, #0xd]\n\t"
        "cmp r0, #0\n\t"
        "beq 29f\n\t"
        "mov r0, #0\n\t"
        "str r0, [sp, #0x20]\n\t"
        "ldr r3, 25f\n\t"
        "ldr r1, [r3]\n\t"
        "lsr r0, r5, #0x1f\n\t"
        "add r0, r5, r0\n\t"
        "asr r0, r0, #1\n\t"
        "ldr r2, [r1, #0x44]\n\t"
        "lsl r0, r0, #1\n\t"
        "add r0, r0, r2\n\t"
        "ldr r4, 26f\n\t"
        "add r1, r4, #0\n\t"
        "strh r1, [r0]\n\t"
        "ldr r0, 27f\n\t"
        "sub r0, r0, r7\n\t"
        "add r0, #2\n\t"
        "lsr r1, r0, #0x1f\n\t"
        "add r0, r0, r1\n\t"
        "asr r0, r0, #1\n\t"
        "lsl r0, r0, #1\n\t"
        "add r0, r0, r2\n\t"
        "ldr r2, 28f\n\t"
        "b 41f\n\t"
        ".align 2, 0\n\t"
        "25: .4byte gUnknown_03001630\n\t"
        "26: .4byte 0x0000E082\n\t"
        "27: .4byte gStaticData_0803A884\n\t"
        "28: .4byte 0x0000BAFF\n\t"
        "29:\n\t"
        "add r0, r6, #0\n\t"
        "add r0, #0x52\n\t"
        "ldrb r0, [r0]\n\t"
        "str r0, [sp, #0x20]\n\t"
        "ldr r3, 30f\n\t"
        "ldr r2, [r3]\n\t"
        "ldr r0, 31f\n\t"
        "sub r0, r0, r7\n\t"
        "add r0, #2\n\t"
        "lsr r1, r0, #0x1f\n\t"
        "add r0, r0, r1\n\t"
        "asr r0, r0, #1\n\t"
        "ldr r2, [r2, #0x44]\n\t"
        "lsl r0, r0, #1\n\t"
        "add r0, r0, r2\n\t"
        "ldr r4, 32f\n\t"
        "add r1, r4, #0\n\t"
        "strh r1, [r0]\n\t"
        "ldr r0, 33f\n\t"
        "sub r0, r0, r7\n\t"
        "add r0, #2\n\t"
        "lsr r1, r0, #0x1f\n\t"
        "add r0, r0, r1\n\t"
        "asr r0, r0, #1\n\t"
        "lsl r0, r0, #1\n\t"
        "add r0, r0, r2\n\t"
        "ldr r2, 34f\n\t"
        "b 41f\n\t"
        ".align 2, 0\n\t"
        "30: .4byte gUnknown_03001630\n\t"
        "31: .4byte gStaticData_0803A8B4\n\t"
        "32: .4byte 0x0000E082\n\t"
        "33: .4byte gStaticData_0803A8C4\n\t"
        "34: .4byte 0x0000BAFF\n\t"
        "35:\n\t"
        "ldr r2, [r6, #0x3c]\n\t"
        "ldrb r1, [r6, #0x10]\n\t"
        "lsl r0, r1, #3\n\t"
        "sub r0, r0, r1\n\t"
        "lsl r0, r0, #2\n\t"
        "add r2, #0x14\n\t"
        "add r2, r2, r0\n\t"
        "ldr r3, [r2]\n\t"
        "lsl r0, r3, #0xb\n\t"
        "str r0, [sp, #0xc]\n\t"
        "ldrb r0, [r6, #0xd]\n\t"
        "cmp r0, #0\n\t"
        "beq 39f\n\t"
        "mov r0, #0\n\t"
        "str r0, [sp, #0x20]\n\t"
        "ldr r3, 36f\n\t"
        "ldr r1, [r3]\n\t"
        "lsr r0, r5, #0x1f\n\t"
        "add r0, r5, r0\n\t"
        "asr r0, r0, #1\n\t"
        "ldr r2, [r1, #0x44]\n\t"
        "lsl r0, r0, #1\n\t"
        "add r0, r0, r2\n\t"
        "ldr r4, 37f\n\t"
        "add r1, r4, #0\n\t"
        "strh r1, [r0]\n\t"
        "ldr r0, 38f\n\t"
        "b 40f\n\t"
        ".align 2, 0\n\t"
        "36: .4byte gUnknown_03001630\n\t"
        "37: .4byte 0x0000E042\n\t"
        "38: .4byte gStaticData_0803A884\n\t"
        "39:\n\t"
        "mov r0, #1\n\t"
        "str r0, [sp, #0x20]\n\t"
        "ldr r3, 42f\n\t"
        "ldr r2, [r3]\n\t"
        "ldr r0, 43f\n\t"
        "sub r0, r0, r7\n\t"
        "add r0, #2\n\t"
        "lsr r1, r0, #0x1f\n\t"
        "add r0, r0, r1\n\t"
        "asr r0, r0, #1\n\t"
        "ldr r2, [r2, #0x44]\n\t"
        "lsl r0, r0, #1\n\t"
        "add r0, r0, r2\n\t"
        "ldr r4, 44f\n\t"
        "add r1, r4, #0\n\t"
        "strh r1, [r0]\n\t"
        "ldr r0, 45f\n\t"
        "40:\n\t"
        "sub r0, r0, r7\n\t"
        "add r0, #2\n\t"
        "lsr r1, r0, #0x1f\n\t"
        "add r0, r0, r1\n\t"
        "asr r0, r0, #1\n\t"
        "lsl r0, r0, #1\n\t"
        "add r0, r0, r2\n\t"
        "ldr r2, 46f\n\t"
        "41:\n\t"
        "add r1, r2, #0\n\t"
        "strh r1, [r0]\n\t"
        "mov r4, sp\n\t"
        "ldr r3, [r3]\n\t"
        "ldr r3, [r3, #0x44]\n\t"
        "add r1, r3, #0\n\t"
        "add r0, r4, #0\n\t"
        "mov r2, pc\n\t"
        "add r2, #5\n\t"
        "mov lr, r2\n\t"
        "bx r1\n\t"
        ".thumb_func\n\t"
        ".global sub_8039E50\n\t"
        "sub_8039E50:\n\t"
        "nop\n\t"
        "ldr r0, [r6, #4]\n\t"
        "ldrh r2, [r0, #4]\n\t"
        "ldr r0, [sp, #20]\n\t"
        "cmp r0, r2\n\t"
        "beq 56f\n\t"
        "ldr r3, [sp, #88]\n\t"
        "cmp r3, #0\n\t"
        "beq 50f\n\t"
        "ldr r3, [r6, #60]\n\t"
        "ldrb r1, [r6, #16]\n\t"
        "lsl r0, r1, #3\n\t"
        "sub r0, r0, r1\n\t"
        "lsl r2, r0, #2\n\t"
        "add r0, r3, r2\n\t"
        "ldrb r0, [r0, #13]\n\t"
        "cmp r0, #0\n\t"
        "beq 49f\n\t"
        "mov r0, #17\n\t"
        "ldrsb r0, [r6, r0]\n\t"
        "ldrb r2, [r6, #17]\n\t"
        "cmp r0, #0\n\t"
        "ble 47f\n\t"
        "mov r4, sl\n\t"
        "lsl r1, r4, #1\n\t"
        "ldr r0, [sp, #8]\n\t"
        "sub r0, r0, r1\n\t"
        "b 48f\n\t"
        "42: .4byte gUnknown_03001630\n\t"
        "43: .4byte gStaticData_0803A8B4\n\t"
        "44: .4byte 0x0000E042\n\t"
        "45: .4byte gStaticData_0803A8C4\n\t"
        "46: .4byte 0x0000CAFF\n\t"
        "47:\n\t"
        "mov r0, sl\n\t"
        "lsl r1, r0, #1\n\t"
        "ldr r0, [sp, #8]\n\t"
        "add r0, r0, r1\n\t"
        "48:\n\t"
        "str r0, [sp, #8]\n\t"
        "mvn r0, r2\n\t"
        "strb r0, [r6, #17]\n\t"
        "b 55f\n\t"
        "49:\n\t"
        "add r1, r3, #0\n\t"
        "add r1, #24\n\t"
        "add r1, r1, r2\n\t"
        "add r0, r3, #0\n\t"
        "add r0, #20\n\t"
        "add r0, r0, r2\n\t"
        "ldr r1, [r1, #0]\n\t"
        "ldr r0, [r0, #0]\n\t"
        "sub r1, r1, r0\n\t"
        "b 51f\n\t"
        "50:\n\t"
        "ldrb r4, [r6, #18]\n\t"
        "cmp r4, #0\n\t"
        "beq 52f\n\t"
        "ldr r2, [r6, #60]\n\t"
        "ldrb r1, [r6, #16]\n\t"
        "lsl r0, r1, #3\n\t"
        "sub r0, r0, r1\n\t"
        "lsl r0, r0, #2\n\t"
        "add r2, #28\n\t"
        "add r2, r2, r0\n\t"
        "ldr r1, [r2, #0]\n\t"
        "51:\n\t"
        "lsl r1, r1, #11\n\t"
        "ldr r0, [sp, #8]\n\t"
        "sub r0, r0, r1\n\t"
        "str r0, [sp, #8]\n\t"
        "b 55f\n\t"
        "52:\n\t"
        "ldrb r0, [r6, #13]\n\t"
        "cmp r0, #0\n\t"
        "beq 53f\n\t"
        "ldr r0, [sp, #20]\n\t"
        "lsl r0, r0, #1\n\t"
        "ldr r1, [sp, #80]\n\t"
        "add r0, r1, r0\n\t"
        "ldr r1, [sp, #20]\n\t"
        "sub r1, r2, r1\n\t"
        "add r1, #1\n\t"
        "lsl r1, r1, #1\n\t"
        "bl sub_8037F3C\n\t"
        "53:\n\t"
        "ldr r0, 54f\n\t"
        "strh r0, [r6, #42]\n\t"
        "strh r4, [r6, #44]\n\t"
        "mov r0, #128\n\t"
        "lsl r0, r0, #24\n\t"
        "str r0, [r6, #76]\n\t"
        "b 56f\n\t"
        "54: .4byte 0x8ad0\n\t"
        "55:\n\t"
        "ldr r1, [r6, #4]\n\t"
        "ldr r0, [sp, #20]\n\t"
        "ldrh r1, [r1, #4]\n\t"
        "cmp r0, r1\n\t"
        "bcs 56f\n\t"
        "b 19b\n\t"
        "56:\n\t"
        "ldr r0, [sp, #8]\n\t"
        "str r0, [r6, #0x44]\n\t"
        "mov r0, #1\n\t"
        "57:\n\t"
        "add sp, #0x5c\n\t"
        "pop {r3, r4, r5}\n\t"
        "mov r8, r3\n\t"
        "mov sb, r4\n\t"
        "mov sl, r5\n\t"
        "pop {r4, r5, r6, r7}\n\t"
        "pop {r1}\n\t"
        "bx r1\n\t"
        ".align 2, 0\n\t"
    );
}
