#include "core.h"

/* Per-tick voice-envelope/pattern-note scheduler: reads the next 16-bit
 * command word from a per-channel pattern-data stream (`self->0x3c->0x88`,
 * indexed by `self->0x36`, an event counter bounds-checked against
 * `self->0x3c->0x85`), splits it into a delay byte (high byte) and a
 * parameter byte (low byte), and either arms a fresh note (delay byte ==
 * 0: sets pitch/instrument-index fields, then a "priority steal" check
 * over a second parallel table - `self+0x10`/`+0x14`/`+0x18`/`+0x1c`/
 * `+0x20`, cross-referenced with the current song's `curChannelIdx`-scaled
 * slot arrays via `sb`), or - once the delay expires (`self->0x1e`) -
 * dispatches the parameter byte through a small jump table of per-command
 * handlers (portamento, volume/pan set, tremolo/vibrato depth, stop). The
 * channel/voice/pattern-stream object shapes aren't modeled yet - kept as
 * raw offsets throughout, matching the neighboring GAX2 engine internals
 * in this directory.
 *
 * Written as NAKED asm, not plain C: keeps `r8`/`sb` live as genuine
 * scratch (a running "steal" candidate index/slot-array base pair) across
 * the whole priority-steal block and the 15-way command jump table - the
 * same many-register gcc-2.9 allocation ceiling already documented
 * throughout this ROM region (docs/status/audio.md). Mechanical,
 * byte-verified transcription of the ROM's own instructions (including
 * its 15-entry jump table, `mov pc, r0`) - not an inferred control-flow
 * guess. */
NAKED void sub_80398DC(void *self)
{
    asm(
        "push {r4, r5, r6, r7, lr}\n\t"
        "mov r7, sb\n\t"
        "mov r6, r8\n\t"
        "push {r6, r7}\n\t"
        "add r3, r0, #0\n\t"
        "ldr r1, [r3, #0x3c]\n\t"
        "add r0, r1, #0\n\t"
        "add r0, #0x88\n\t"
        "ldrh r4, [r3, #0x36]\n\t"
        "lsl r2, r4, #3\n\t"
        "ldr r0, [r0]\n\t"
        "add r0, r0, r2\n\t"
        "mov ip, r0\n\t"
        "add r1, #0x85\n\t"
        "ldrb r1, [r1]\n\t"
        "cmp r4, r1\n\t"
        "blo L98DC_0\n\t"
        "mov r0, #0\n\t"
        "strb r0, [r3, #0x1e]\n\t"
        "b L98DC_1\n\t"
        "L98DC_0:\n\t"
        "add r0, r4, #1\n\t"
        "strh r0, [r3, #0x36]\n\t"
        "mov r1, ip\n\t"
        "ldrb r0, [r1]\n\t"
        "cmp r0, #0\n\t"
        "beq L98DC_2\n\t"
        "sub r0, #2\n\t"
        "lsl r0, r0, #5\n\t"
        "strh r0, [r3, #0x2a]\n\t"
        "ldrb r0, [r1, #1]\n\t"
        "add r1, r3, #0\n\t"
        "add r1, #0x21\n\t"
        "strb r0, [r1]\n\t"
        "mov r2, ip\n\t"
        "ldrb r0, [r2, #2]\n\t"
        "cmp r0, #0\n\t"
        "beq L98DC_2\n\t"
        "sub r0, #1\n\t"
        "strb r0, [r3, #0x10]\n\t"
        "mov r0, #0\n\t"
        "str r0, [r3, #0x44]\n\t"
        "mov r0, #1\n\t"
        "mov r8, r0\n\t"
        "mov r1, r8\n\t"
        "strb r1, [r3, #0x11]\n\t"
        "mov r0, #0xff\n\t"
        "strb r0, [r3, #0x17]\n\t"
        "mov r0, #0\n\t"
        "strb r0, [r3, #0x12]\n\t"
        "ldr r2, [r3, #0x3c]\n\t"
        "ldrb r1, [r3, #0x10]\n\t"
        "lsl r0, r1, #3\n\t"
        "sub r0, r0, r1\n\t"
        "lsl r5, r0, #2\n\t"
        "add r6, r2, r5\n\t"
        "ldrb r0, [r6, #0xc]\n\t"
        "add r4, r2, #0\n\t"
        "cmp r0, #0\n\t"
        "beq L98DC_3\n\t"
        "add r0, r4, #0\n\t"
        "add r0, #0x14\n\t"
        "add r0, r0, r5\n\t"
        "mov r2, #0x18\n\t"
        "add r2, r2, r4\n\t"
        "mov sb, r2\n\t"
        "add r1, r2, r5\n\t"
        "ldr r2, [r0]\n\t"
        "ldr r0, [r1]\n\t"
        "cmp r2, r0\n\t"
        "bge L98DC_3\n\t"
        "add r7, r4, #0\n\t"
        "add r7, #0x1c\n\t"
        "add r0, r7, r5\n\t"
        "ldr r0, [r0]\n\t"
        "cmp r0, #0\n\t"
        "ble L98DC_3\n\t"
        "ldrh r0, [r6, #0x24]\n\t"
        "cmp r0, #0\n\t"
        "beq L98DC_3\n\t"
        "add r0, r4, #0\n\t"
        "add r0, #0x20\n\t"
        "add r0, r0, r5\n\t"
        "ldr r0, [r0]\n\t"
        "cmp r0, #0\n\t"
        "ble L98DC_3\n\t"
        "mov r0, r8\n\t"
        "strb r0, [r3, #0x12]\n\t"
        "ldrb r0, [r3, #0x10]\n\t"
        "lsl r1, r0, #3\n\t"
        "sub r1, r1, r0\n\t"
        "lsl r1, r1, #2\n\t"
        "add r0, r4, #0\n\t"
        "add r0, #0x10\n\t"
        "add r0, r0, r1\n\t"
        "ldr r2, [r0]\n\t"
        "str r2, [r3, #0x48]\n\t"
        "lsl r0, r2, #0xb\n\t"
        "str r0, [r3, #0x44]\n\t"
        "ldrb r1, [r3, #0x10]\n\t"
        "lsl r0, r1, #3\n\t"
        "sub r0, r0, r1\n\t"
        "lsl r0, r0, #2\n\t"
        "add r0, r4, r0\n\t"
        "ldrh r0, [r0, #0x24]\n\t"
        "strb r0, [r3, #0x14]\n\t"
        "mov r1, r8\n\t"
        "strb r1, [r3, #0x13]\n\t"
        "ldrb r1, [r3, #0x10]\n\t"
        "lsl r0, r1, #3\n\t"
        "sub r0, r0, r1\n\t"
        "lsl r0, r0, #2\n\t"
        "add r1, r7, r0\n\t"
        "ldr r1, [r1]\n\t"
        "add r2, r2, r1\n\t"
        "add r0, sb\n\t"
        "ldr r0, [r0]\n\t"
        "cmp r2, r0\n\t"
        "ble L98DC_2\n\t"
        "mov r0, #0xff\n\t"
        "strb r0, [r3, #0x13]\n\t"
        "b L98DC_2\n\t"
        "L98DC_3:\n\t"
        "ldrb r0, [r3, #0x10]\n\t"
        "lsl r1, r0, #3\n\t"
        "sub r1, r1, r0\n\t"
        "lsl r1, r1, #2\n\t"
        "add r0, r4, #0\n\t"
        "add r0, #0x10\n\t"
        "add r0, r0, r1\n\t"
        "ldr r0, [r0]\n\t"
        "lsl r0, r0, #0xb\n\t"
        "str r0, [r3, #0x44]\n\t"
        "L98DC_2:\n\t"
        "mov r0, #0\n\t"
        "strh r0, [r3, #0x1c]\n\t"
        "strh r0, [r3, #0x2c]\n\t"
        "mov r4, #0\n\t"
        "L98DC_4:\n\t"
        "lsl r0, r4, #1\n\t"
        "add r0, ip\n\t"
        "ldrh r0, [r0, #4]\n\t"
        "lsr r1, r0, #8\n\t"
        "mov r2, #0xff\n\t"
        "and r2, r2, r0\n\t"
        "sub r0, r1, #1\n\t"
        "cmp r0, #0xe\n\t"
        "bhi L98DC_5\n\t"
        "lsl r0, r0, #2\n\t"
        "ldr r1, L98DC_6\n\t"
        "add r0, r0, r1\n\t"
        "ldr r0, [r0]\n\t"
        "mov pc, r0\n\t"
        ".align 2, 0\n\t"
        "L98DC_6: .4byte L98DC_JT\n\t"
        "L98DC_JT:\n\t"
        ".4byte L98DC_C0\n\t"
        ".4byte L98DC_C1\n\t"
        ".4byte L98DC_5\n\t"
        ".4byte L98DC_5\n\t"
        ".4byte L98DC_C4\n\t"
        ".4byte L98DC_C5\n\t"
        ".4byte L98DC_5\n\t"
        ".4byte L98DC_5\n\t"
        ".4byte L98DC_5\n\t"
        ".4byte L98DC_C9\n\t"
        ".4byte L98DC_C10\n\t"
        ".4byte L98DC_C11\n\t"
        ".4byte L98DC_5\n\t"
        ".4byte L98DC_5\n\t"
        ".4byte L98DC_C14\n\t"
        "L98DC_C0:\n\t"
        "strh r2, [r3, #0x2c]\n\t"
        "b L98DC_5\n\t"
        "L98DC_C1:\n\t"
        "neg r0, r2\n\t"
        "strh r0, [r3, #0x2c]\n\t"
        "b L98DC_5\n\t"
        "L98DC_C4:\n\t"
        "add r1, r3, #0\n\t"
        "add r1, #0x20\n\t"
        "ldrb r0, [r1]\n\t"
        "cmp r0, #0\n\t"
        "beq L98DC_7\n\t"
        "sub r0, #1\n\t"
        "strb r0, [r1]\n\t"
        "lsl r0, r0, #0x18\n\t"
        "cmp r0, #0\n\t"
        "beq L98DC_5\n\t"
        "L98DC_7:\n\t"
        "strh r2, [r3, #0x36]\n\t"
        "b L98DC_5\n\t"
        "L98DC_C5:\n\t"
        "add r0, r3, #0\n\t"
        "add r0, #0x20\n\t"
        "ldrb r1, [r0]\n\t"
        "cmp r1, #0\n\t"
        "bne L98DC_5\n\t"
        "cmp r2, #0\n\t"
        "beq L98DC_8\n\t"
        "add r1, r2, #1\n\t"
        "b L98DC_9\n\t"
        "L98DC_8:\n\t"
        "mov r1, #0\n\t"
        "L98DC_9:\n\t"
        "strb r1, [r0]\n\t"
        "b L98DC_5\n\t"
        "L98DC_C9:\n\t"
        "strh r2, [r3, #0x1c]\n\t"
        "b L98DC_5\n\t"
        "L98DC_C10:\n\t"
        "neg r0, r2\n\t"
        "strh r0, [r3, #0x1c]\n\t"
        "b L98DC_5\n\t"
        "L98DC_C11:\n\t"
        "strb r2, [r3, #0x17]\n\t"
        "b L98DC_5\n\t"
        "L98DC_C14:\n\t"
        "strb r2, [r3, #0x1e]\n\t"
        "L98DC_5:\n\t"
        "add r4, #1\n\t"
        "cmp r4, #1\n\t"
        "bls L98DC_4\n\t"
        "L98DC_1:\n\t"
        "pop {r3, r4}\n\t"
        "mov r8, r3\n\t"
        "mov sb, r4\n\t"
        "pop {r4, r5, r6, r7}\n\t"
        "pop {r0}\n\t"
        "bx r0\n\t"
    );
}
