#!/usr/bin/env python3
"""Turns a binary file into the body of a C array initializer (comma-
separated hex bytes), for a src/data/*.c file to `#include` inside its own
`const u8 gFoo[] = { ... };`. The declaration (name, type, comment) stays in
the hand-written .c file; only the bytes are generated.

    tools/bin2c.py IN OUT [--lz]

--lz: IN is a GBA LZ77 stream (tag 0x10). gbagfx pads its output to a
multiple of 4 bytes, but the ROM's streams are packed back to back with no
such padding, so the array is trimmed to the stream's real length (the
bytes the BIOS decompressor actually reads). Only zero padding may be
trimmed; anything else is an error.
"""
import sys


def lz77_stream_length(data):
    if len(data) < 4 or data[0] != 0x10:
        sys.exit("bin2c: --lz input is not an LZ77 stream (tag 0x10)")
    size = int.from_bytes(data[1:4], "little")
    out = 0
    pos = 4
    while out < size:
        flags = data[pos]
        pos += 1
        for bit in range(7, -1, -1):
            if out >= size:
                break
            if flags >> bit & 1:
                out += (data[pos] >> 4) + 3
                pos += 2
            else:
                out += 1
                pos += 1
    if out != size or pos > len(data):
        sys.exit("bin2c: malformed LZ77 stream")
    return pos


def main():
    args = sys.argv[1:]
    lz = "--lz" in args
    args = [a for a in args if a != "--lz"]
    if len(args) != 2:
        sys.exit(__doc__)
    data = open(args[0], "rb").read()
    if lz:
        end = lz77_stream_length(data)
        if any(data[end:]):
            sys.exit(f"bin2c: {args[0]}: non-zero bytes after the LZ77 stream")
        data = data[:end]
    lines = []
    for i in range(0, len(data), 16):
        lines.append("\t" + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
    with open(args[1], "w") as f:
        f.write(f"/* generated by tools/bin2c.py from {args[0]}: {len(data)} bytes */\n")
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
