#!/usr/bin/env python3
"""The two boss pictures drawn on an affine BG (gStaticData_08167CD4, four
frames of N. Gin's airship, and gStaticData_08169CE8, Cortex's
hovercraft; see docs/data.md "Boss pictures").

In the ROM a picture is {s16 cols, s16 rows}, then per frame a tile
count, a `cols * rows` map of u16 tile indices and that many 4bpp tiles.
All frames share one tile pool: a frame's new tiles are appended after
the previous frames' ones. The maps are exactly what deduplicating the
frames' cells in reading order gives (the first identical tile, no
flips, frame by frame), so the frames are kept as whole pictures and the
tiles and maps are built from them again.

    tools/boss_pictures.py extract [baserom.gba]
        Writes graphics/boss_pictures/<addr>_frameN.png (indexed 4bpp,
        cols*8 x rows*8, with the 16 colours the game loads for them) and
        checks that packing them gives the ROM's bytes.

    tools/boss_pictures.py pack OUT.inc OUT.h --name NAME --cols N TILES...
        TILES is grit's 4bpp tile output (-gt -gB4 -ftb) of each frame's
        PNG, in frame order. Writes the frames as the body of the
        picture struct's initializer (after {cols, rows}), and a header
        with NAME_COLS, NAME_ROWS and each frame's NAME_FRAMEn_TILES.
"""
import argparse
import struct
import sys
from pathlib import Path

ROM_BASE = 0x08000000

# (picture, end, palette): the palette's first 16 colours are what the
# game DMAs to BG palette 1, which the tiles are drawn with.
PICTURES = [
    (0x08167CD4, 0x08169AE8, 0x08167AD4),
    (0x08169CE8, 0x0816A810, 0x08169AE8),
]


def build(frames, cols):
    """frames: list of tile-byte strings (row-major cells) -> list of
    (tile count, map, new tiles)."""
    pool = {}
    out = []
    for tiles in frames:
        if len(tiles) % 32 or len(tiles) // 32 % cols:
            sys.exit("boss_pictures: a frame isn't a whole number of rows of tiles")
        new = bytearray()
        mp = []
        for c in range(len(tiles) // 32):
            t = bytes(tiles[c * 32:(c + 1) * 32])
            if t not in pool:
                pool[t] = len(pool)
                new += t
            mp.append(pool[t])
        out.append((len(new) // 32, mp, bytes(new)))
    return out


def rom_frames(rom, start, end):
    cols, rows = struct.unpack_from("<hh", rom, start - ROM_BASE)
    cells = cols * rows
    pos = start - ROM_BASE + 4
    pool, frames = [], []
    while pos < end - ROM_BASE:
        (n,) = struct.unpack_from("<i", rom, pos)
        mp = struct.unpack_from(f"<{cells}H", rom, pos + 4)
        tiles = rom[pos + 4 + cells * 2:pos + 4 + cells * 2 + n * 32]
        pool += [tiles[i * 32:(i + 1) * 32] for i in range(n)]
        frames.append(b"".join(pool[i] for i in mp))
        pos += 4 + cells * 2 + n * 32
    if pos != end - ROM_BASE or cells % 2:
        sys.exit(f"boss_pictures: {start:#x}: the frames don't fill the picture")
    return cols, rows, frames


def encode(cols, rows, built):
    out = struct.pack("<hh", cols, rows)
    for n, mp, new in built:
        out += struct.pack("<i", n) + struct.pack(f"<{len(mp)}H", *mp) + new
    return out


def extract(rom_path):
    from PIL import Image

    rom = Path(rom_path).read_bytes()
    for start, end, pal in PICTURES:
        cols, rows, frames = rom_frames(rom, start, end)
        if encode(cols, rows, build(frames, cols)) != rom[start - ROM_BASE:end - ROM_BASE]:
            sys.exit(f"boss_pictures: {start:#x} does not rebuild")
        palette = []
        for i in range(16):
            (c,) = struct.unpack_from("<H", rom, pal - ROM_BASE + 2 * i)
            palette += [((c >> s) & 31) * 255 // 31 for s in (0, 5, 10)]
        for f, tiles in enumerate(frames):
            img = Image.new("P", (cols * 8, rows * 8), 0)
            px = img.load()
            for t in range(cols * rows):
                tx, ty = t % cols * 8, t // cols * 8
                for i in range(64):
                    px[tx + i % 8, ty + i // 8] = tiles[t * 32 + i // 2] >> (4 * (i & 1)) & 0xF
            img.putpalette(palette)
            path = Path(f"graphics/boss_pictures/{start - ROM_BASE:06x}_frame{f}.png")
            path.parent.mkdir(parents=True, exist_ok=True)
            img.save(path, bits=4)
            print(f"{path}: {cols}x{rows} cells")


def pack(args):
    frames = [Path(p).read_bytes() for p in args.tiles]
    cols = args.cols
    rows = len(frames[0]) // 32 // cols
    if any(len(f) != len(frames[0]) for f in frames) or (cols * rows) % 2:
        sys.exit("boss_pictures: the frames must be the same size, with an even number of cells")
    built = build(frames, cols)
    src = ", ".join(args.tiles)
    lines = [f"/* generated by tools/boss_pictures.py from {src} */"]
    for f, (n, mp, new) in enumerate(built):
        lines.append(f"\t{{ /* frame {f} */")
        lines.append(f"\t\t{n},")
        lines.append("\t\t{")
        lines += ["\t\t\t" + ", ".join(f"{v}" for v in mp[i:i + cols]) + "," for i in range(0, len(mp), cols)]
        lines.append("\t\t},")
        lines.append("\t\t{")
        lines += ["\t\t\t" + ", ".join(f"0x{b:02X}" for b in new[i:i + 16]) + "," for i in range(0, len(new), 16)]
        lines.append("\t\t},")
        lines.append("\t},")
    Path(args.output).write_text("\n".join(lines) + "\n")
    hdr = [f"/* generated by tools/boss_pictures.py from {src} */",
           f"#define {args.name}_COLS {cols}",
           f"#define {args.name}_ROWS {rows}"]
    hdr += [f"#define {args.name}_FRAME{f}_TILES {n}" for f, (n, _, _) in enumerate(built)]
    Path(args.header).write_text("\n".join(hdr) + "\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = ap.add_subparsers(dest="mode", required=True)
    ex = sub.add_parser("extract")
    ex.add_argument("rom", nargs="?", default="baserom.gba")
    pk = sub.add_parser("pack")
    pk.add_argument("output")
    pk.add_argument("header")
    pk.add_argument("--name", required=True)
    pk.add_argument("--cols", type=int, required=True)
    pk.add_argument("tiles", nargs="+")
    args = ap.parse_args()
    if args.mode == "extract":
        extract(args.rom)
    else:
        pack(args)


if __name__ == "__main__":
    main()
