#!/usr/bin/env python3
"""Turns grit's binary output for the actor-category backgrounds (the BG0
cell animations and the BG1 pictures, see docs/data.md "Category
backgrounds") into C initializer bodies that a src/data/*.c file
`#include`s. grit does every pixel, palette and map conversion; this only
splits and interleaves its output into the ROM's record layout.

    tools/grit_bg.py map MAP OUT
        MAP is a grit map (`-m -mRtp -mLf -ftb`). Writes its tile-index half:
        one u16 per entry with the palette-bank bits (12-15) cleared.

    tools/grit_bg.py banks MAP OUT
        The palette-bank half of the same map: one 4-bit bank per entry,
        two per byte, low nibble first (what sub_802F7B0 ORs back into
        bits 12-15). An odd count is padded with a zero nibble.

    tools/grit_bg.py frames TILES OUT --cells N [--banks MAP]
        TILES is grit's 4bpp tile output (`-gt -gB4 -ftb`) of a tall strip
        of animation frames, N tiles each. Writes one `{ { tiles }, },`
        initializer per frame. With --banks, each frame also gets its
        cells' palette banks, packed as for `banks` and padded to
        (N+7)/8*4 bytes, the side-data size sub_8029890 steps over:
        `{ { tiles }, { banks } },`.
"""
import argparse
import struct
import sys


def read_map(path):
    data = open(path, "rb").read()
    if len(data) % 2:
        sys.exit(f"grit_bg: {path}: odd map size")
    return struct.unpack(f"<{len(data) // 2}H", data)


def pack_nibbles(values, size=None):
    values = list(values)
    if len(values) % 2:
        values.append(0)
    out = bytes(values[i] | values[i + 1] << 4 for i in range(0, len(values), 2))
    if size is not None:
        out = out.ljust(size, b"\0")
    return out


def byte_lines(data, indent="\t"):
    return [indent + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ","
            for i in range(0, len(data), 16)]


def write(path, source, lines):
    with open(path, "w") as f:
        f.write(f"/* generated by tools/grit_bg.py from {source} */\n")
        f.write("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("mode", choices=("map", "banks", "frames"))
    ap.add_argument("input")
    ap.add_argument("output")
    ap.add_argument("--cells", type=int)
    ap.add_argument("--banks", dest="banks_map")
    args = ap.parse_args()

    if args.mode == "map":
        entries = read_map(args.input)
        lines = ["\t" + ", ".join(f"0x{e & 0x0FFF:04X}" for e in entries[i:i + 8]) + ","
                 for i in range(0, len(entries), 8)]
        write(args.output, args.input, lines)
    elif args.mode == "banks":
        entries = read_map(args.input)
        write(args.output, args.input, byte_lines(pack_nibbles(e >> 12 for e in entries)))
    else:
        if not args.cells:
            sys.exit("grit_bg: frames needs --cells")
        tiles = open(args.input, "rb").read()
        frame_size = args.cells * 32
        if len(tiles) % frame_size:
            sys.exit(f"grit_bg: {args.input}: {len(tiles)} bytes is not a whole number of {args.cells}-tile frames")
        count = len(tiles) // frame_size
        banks = None
        if args.banks_map:
            entries = read_map(args.banks_map)
            if len(entries) != count * args.cells:
                sys.exit(f"grit_bg: {args.banks_map}: {len(entries)} map entries for {count} frames of {args.cells} cells")
            banks = [e >> 12 for e in entries]
        lines = []
        for f in range(count):
            lines.append(f"\t/* frame {f} */ {{")
            lines.append("\t\t{")
            lines += byte_lines(tiles[f * frame_size:(f + 1) * frame_size], "\t\t\t")
            lines.append("\t\t},")
            if banks is not None:
                side = pack_nibbles(banks[f * args.cells:(f + 1) * args.cells],
                                    (args.cells + 7) // 8 * 4)
                lines.append("\t\t{")
                lines += byte_lines(side, "\t\t\t")
                lines.append("\t\t},")
            lines.append("\t},")
        write(args.output, args.input, lines)


if __name__ == "__main__":
    main()
