"""Build sound/sfx_table.bin from the editable sound/sfx_table.json source.

This is the GAX2 "sound effect" trigger table (originally at ROM address
0x0816AA6C): 99 fixed-size entries, one per sound effect ID. PlaySfx
(src/audio/audio.c, called ~264 times from all over the game's logic - jumping,
menus, hits, pickups, etc.) looks up the SFX ID in this table and uses it to
steal a mixing voice and play a note from the GAX2 sound-effect data set
(sound/gax_sfx_manifest.json, sound/sfx_samples/ - not the music's pool; see
docs/audio.md, "Sound effects").

Each entry is 3 little-endian signed 32-bit words:
  slot_id      - the sound-effect instrument to play (1-87; written into the
                 voice at offset 0x25 by GAX_fx_ex)
  pitch_offset - really GAX_fx_ex's priority argument (struct
                 SfxTableEntry.chanArg), the voice-steal threshold
  volume       - 8.8 fixed-point volume scale (0x100 == 1.0)

Field names describe what's empirically observable from the data and the
code that reads it; the deeper mixer semantics of slot_id/pitch_offset
haven't been fully reversed.

An entry may also have a `name` and a `comment`: `--constants OUT` writes
them as the SFX_<name> #defines of constants/sfx.h (build/include), and the
top-level `none_comment` documents SFX_NONE, the ID one past the table.
"""
import json
import struct
import sys

ENTRY_COUNT = 99
ENTRY_SIZE = 12


def build(json_path, out_path):
    manifest = json.load(open(json_path))
    entries = manifest['entries']
    assert len(entries) == ENTRY_COUNT, f"expected {ENTRY_COUNT} entries, got {len(entries)}"

    out = bytearray()
    for e in entries:
        out += struct.pack('<iii', e['slot_id'], e['pitch_offset'], e['volume'])

    assert len(out) == ENTRY_COUNT * ENTRY_SIZE
    open(out_path, 'wb').write(out)


def define_lines(rows):
    """[(name, value, comment)] -> aligned #define lines."""
    width = max(len(n) + len(v) for n, v, _ in rows)
    return ["#define %s %s%s// %s" % (n, v, " " * (width - len(n) - len(v) + 1), c) for n, v, c in rows]


def write_constants(json_path, out_path):
    """constants/sfx.h: the SFX_* name of each named entry, by ID."""
    manifest = json.load(open(json_path))
    entries = manifest['entries']
    rows = [('SFX_' + e['name'], '%#x' % i, e['comment']) for i, e in enumerate(entries) if 'name' in e]
    rows.append(('SFX_NONE', '%#x' % len(entries), manifest['none_comment']))
    names = [n for n, _, _ in rows]
    assert len(set(names)) == len(names), f"{json_path}: duplicate sound-effect names"
    out = [
        f'/* Generated by tools/sfx_table.py from {json_path}. Do not edit. */',
        '#ifndef GUARD_CONSTANTS_SFX_H',
        '#define GUARD_CONSTANTS_SFX_H',
        '',
        '/*',
        ' * Sound-effect IDs: the index into gSfxTable (sound/sfx_table.json, 99',
        ' * entries) that PlaySfx, PlayAmbientSfx and StopSfx take. Neither the',
        ' * ROM nor the GAX sound-effect set (sound/gax_sfx_manifest.json) names',
        ' * them, so each name comes from where the game plays it; the comment',
        " * says where. An ID whose sound isn't clear from its callers isn't",
        ' * named yet, and its call sites keep the number',
        ' * (`tools/magic_numbers.py --topic sfx` lists them).',
        ' */',
        '',
        *define_lines(rows),
        '',
        '#endif /* GUARD_CONSTANTS_SFX_H */',
        '',
    ]
    with open(out_path, 'w') as f:
        f.write('\n'.join(out))


if __name__ == '__main__':
    if len(sys.argv) >= 3 and sys.argv[1] == '--constants':
        write_constants(sys.argv[3] if len(sys.argv) > 3 else 'sound/sfx_table.json', sys.argv[2])
        sys.exit(0)
    out_path = sys.argv[1]
    json_path = sys.argv[2] if len(sys.argv) > 2 else 'sound/sfx_table.json'
    build(json_path, out_path)
