#include "core.h"
#include "level_data.h"

/*
 * ROM 0x0824B638-0x08270F08: the level data of 33 of the 41 rooms (the
 * other 8 are in level_rooms_2b91d0.c), between level tile sets 3 and 4.
 * Per room, in ROM order: the entity parameter records and their
 * offsets, the layers' chunk grids, the BG palette, the per-type entity
 * counts, the entity links, the `struct level_desc`, the entity list
 * header, the layer descriptors, the entity groups and the entities.
 * gStaticData_0816CD80's room records point at each room's palette and
 * descriptor. See docs/levels.md.
 *
 * The definitions are generated by tools/levels.py from data/levels/
 * (levels.json names the rooms in this region, in ROM order).
 */
#include "level_rooms_24b638.inc"
