extern "C" {
#include "core.h"
#include "level_data.h"
}

/*
 * ROM 0x082B91D0-0x082BF120: the level data of 8 of the 41 rooms, between
 * level tile set 5 and the sprite tile pool. Same layout as
 * level_rooms_24b638.cpp; see docs/levels.md.
 *
 * The definitions are generated by tools/levels.py from data/levels/
 * (levels.json names the rooms in this region, in ROM order).
 */
#include "level_rooms_2b91d0.inc"
